### ISSUE TITLE
GRUB entries unable to rebuild bootable entries during and following upgrade

### ISSUE THREAD

**Issue by ylluminate** [cpanel/elevate#101]
Had an interesting situation, pretty much successfully moved through the migration except for a problem with Python and another strangely unknown issue that was kind of resolved after a reboot, but I had to manually enter the GRUB boot args. I've documented the issue below and wanted to report it here as well for your awareness and assistance to resolve:
https://almalinux.discourse.group/t/how-to-repair-rebuild-grub-following-a-cross-upgrade-from-centos-7-to-almalinux-8/1268

**Comment by ylluminate** [comment]
It appears as though the problem was that `/etc/default/grub` needs to have `GRUB_ENABLE_BLSCFG=false` instead of `true` in context of running cPanel with AlmaLinux 8 and the upgrade on Linode:
```
$ nano /etc/default/grub
### set: GRUB_ENABLE_BLSCFG=false
$ grub2-mkconfig -o /boot/grub2/grub.cfg
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.18.0-372.9.1.el8.x86_64
Found initrd image: /boot/initramfs-4.18.0-372.9.1.el8.x86_64.img
Found linux image: /boot/vmlinuz-0-rescue-4f09fa5fdd3642fa85221d7c11370603
Found initrd image: /boot/initramfs-0-rescue-4f09fa5fdd3642fa85221d7c11370603.img
done
```

**Comment by ylluminate** [comment]
Another possible thing that could have happened - and something I could not previously explain - just before the boot failure, I did notice that ELevate failed somehow, but it was too quick and in a mode where I could not isolate it from the logging. It's likely that the grub installation failed as per this:
https://almalinux.discourse.group/t/how-to-repair-rebuild-grub-following-a-cross-upgrade-from-centos-7-to-almalinux-8/1268/11

It seems that a good bit more testing and logic needs to be implemented to cover grub / boot issues, especially in cases where virtual machines (which is a large (majority?) amount of cPanel installs today) are involved...

**Comment by sloanebernstein** [comment]
One thing I observed while researching this is that [Linode has encountered this problem before](https://www.linode.com/community/questions/18148/node-unbootable-after-in-place-upgrade-to-fedora-30-converted-grub-config-to-bls). The [Linode documentation](https://www.linode.com/docs/guides/managing-the-kernel-on-a-linode/#viewing-and-modifying-the-kernel-in-the-cloud-manager) suggests that Linode defaults to using its own GRUB2 but can also use the system-provided boot loader. Do you happen to know which of these methods your system used?

Until AlmaLinux and/or we get a better handle on this, we will be blocking the upgrade process unless `GRUB_ENABLE_BLSCFG=false` is set before starting, or unless a flag (`--skip-disable-blscfg`) is passed to the script. See #112.

**Comment by ylluminate** [comment]
Thanks @sloanebernstein. Indeed and in fact the Linode was using the Linode GRUB2 loader by default and seems to in essentially any supported OS scenarios. There definitely has to be some handling of this situation since it's a hard one to isolate without really knowing how to research.
