### ISSUE TITLE
Corrective action needed for cPanel IMAP: Dovecot fails to start with "key too small" - mkcert use too short bit length

### ISSUE THREAD

**Issue by ylluminate** [cpanel/elevate#105]
Following an upgrade from CentOS 7 to AlmaLinux 8 it appears that this bug is encountered with cPanel:
https://bugzilla.redhat.com/show_bug.cgi?id=1882939

If things are not corrected, users will see something like the following:
```
Jun 19 10:12:04 linode dovecot[xxx]: imap-login: Error: Failed to initialize SSL server context: Can't load DH parameters (ssl_dh setting): error:1408518A:SSL routines:ssl3_ctx_ctrl:dh key too small: user=<>, rip=xxx.xxx.xxx.xxx, lip=xxx.xxx.xxx.xxx, session=<xxxxxxxxx>
```

**Comment by sloanebernstein** [comment]
Hello,

This has been resolved in CPANEL-40684. [A fix has been released in cPanel 104.0.4.](https://docs.cpanel.net/changelogs/104-change-log/#104-0-4) However, thank you for letting us know.

**Comment by ylluminate** [comment]
@sloanebernstein thanks for your attention, however I'm running 104.0.4 and it appears I'm experiencing this problem presently. I've created a support ticket as well to explore further (id 94457707) if you'd like to review.

**Comment by sloanebernstein** [comment]
I am getting someone in our Support department to handle your ticket.

**Comment by ylluminate** [comment]
@sloanebernstein Thomas is investigating - resolved the issue, but is trying to understand what happened. I pointed him to this ticket and suspect you may wish to coordinate with him on details so as to verify or resolve this, etc.
