### ISSUE TITLE
1 package(s) installed from unsupported YUM repo 'elasticsearch-7.x'

### ISSUE THREAD

**Issue by coolrecep** [cpanel/elevate#108]
Hi,

After fixing all the other blockers, I'm left with this one. I don't think it's a big issue but could you please also take a look?

Regards

`info [elevate-cpanel] Successfully verified signature for cpanel (key types: release).
* 15-15:53:32 (3008) [WARN] Unsupported YUM repo enabled 'centos-sclo-rh' without packages installed from /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
* 15-15:53:32 (3008) [WARN] Unsupported YUM repo enabled 'centos-sclo-sclo' without packages installed from /etc/yum.repos.d/CentOS-SCLo-scl.repo
* 15-15:53:32 (2998) [ERROR] 1 package(s) installed from unsupported YUM repo 'elasticsearch-7.x' from /etc/yum.repos.d/elastic-7.x.repo
* 15-15:53:32 (2998) [ERROR] 1 package(s) installed from unsupported YUM repo 'remi-safe' from /etc/yum.repos.d/remi-safe.repo
* 15-15:53:32 (2492) [WARN] *** Elevation Blocker detected: ***
One or more enabled YUM repo are currently unsupported.
You should disable these repositories and remove packages installed from them
before continuing the update.

Consider reporting this limitation to https://github.com/cpanel/elevate/issues

* 15-15:54:06 (2906) [INFO] Checking if your system is up to date:
* 15-15:54:06 (3327) [INFO] Running: /usr/bin/yum clean all
* 15-15:54:06 (3328) [INFO]
* 15-15:54:06 (3338) [INFO] Loaded plugins: fastestmirror, getpagespeed, universal-hooks
* 15-15:54:06 (3338) [INFO] Cleaning repos: EA4 cpanel-addons-production-feed cpanel-plugins MariaDB106 base
* 15-15:54:06 (3338) [INFO]               : centos-sclo-rh centos-sclo-sclo elasticsearch-7.x epel extras
* 15-15:54:06 (3338) [INFO]               : imunify360 imunify360-rollout-1 imunify360-rollout-2
* 15-15:54:06 (3338) [INFO]               : imunify360-rollout-3 imunify360-rollout-4 kernelcare
* 15-15:54:06 (3338) [INFO]               : mysql-connectors-community mysql-tools-community
* 15-15:54:06 (3338) [INFO]               : mysql57-community remi-safe updates wp-toolkit-cpanel
* 15-15:54:06 (3338) [INFO]               : wp-toolkit-thirdparties
* 15-15:54:06 (3338) [INFO] Cleaning up list of fastest mirrors
* 15-15:54:06 (3338) [INFO] Other repos take up 36 M of disk space (use --verbose for details)
* 15-15:54:06 (3348) [INFO]
* 15-15:54:06 (3327) [INFO] Running: /usr/bin/yum check-update
* 15-15:54:06 (3328) [INFO]
* 15-15:54:06 (3338) [INFO] Loaded plugins: fastestmirror, getpagespeed, universal-hooks
* 15-15:54:06 (3338) [INFO] Determining fastest mirrors
* 15-15:54:14 (3338) [INFO]  * EA4: 178.18.193.52
* 15-15:54:14 (3338) [INFO]  * cpanel-addons-production-feed: 178.18.193.52
* 15-15:54:14 (3338) [INFO]  * cpanel-plugins: 178.18.193.52
* 15-15:54:14 (3338) [INFO]  * base: mirror.netdirekt.com.tr
* 15-15:54:14 (3338) [INFO]  * centos-sclo-rh: kozyatagi.mirror.guzel.net.tr
* 15-15:54:14 (3338) [INFO]  * centos-sclo-sclo: mirror.bursabil.com.tr
* 15-15:54:14 (3338) [INFO]  * epel: repo.boun.edu.tr
* 15-15:54:14 (3338) [INFO]  * extras: kozyatagi.mirror.guzel.net.tr
* 15-15:54:14 (3338) [INFO]  * remi-safe: mirrors.netix.net
* 15-15:54:14 (3338) [INFO]  * updates: mirror.bursabil.com.tr
* 15-15:54:29 (3348) [INFO]
* 15-15:54:29 (2913) [INFO] Checking /scripts/sysup
* 15-15:54:29 (3327) [INFO] Running: /scripts/sysup
* 15-15:54:29 (3328) [INFO]
* 15-15:54:29 (3338) [INFO] checkyum version 22.3  (excludes: bind-chroot)
* 15-15:54:30 (3338) [INFO]   All Needed Packages are already installed.
* 15-15:54:30 (3348) [INFO]
* 15-15:54:30 (2786) [INFO] Checking EasyApache profile compatibility with Almalinux 8.
* 15-15:54:30 (1436) [INFO] Running: /usr/local/bin/ea_current_to_profile --target-os=AlmaLinux_8
* 15-15:54:30 (1457) [INFO] Backed up EA4 profile to /etc/cpanel/ea4/profiles/custom/current_state_at_2022-07-15_15:54:30_modified_for_AlmaLinux_8.json
* 15-15:54:31 (568) [WARN] Please fix the detected issues before performing the elevation process.
`

**Comment by itonix** [comment]
hello,
I came across the same repo as a blocker. Can I remove this repo? or not? Please shed some lights 
* 2024-01-26 11:42:24 [INFO] Unsupported YUM repo enabled 'centos-sclo-sclo' without packages installed from /etc/yum.repos.d/CentOS-SCLo-scl.repo, these will be disabled before ELevation
* 2024-01-26 11:42:24 [ERROR] 10 package(s) installed from unsupported YUM repo 'XXXX' from /etc/yum.repos.d/XXX.repo
* 2024-01-26 11:42:24 [ERROR] 8 package(s) installed from unsupported YUM repo 'centos-sclo-rh' from /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo

**Comment by toddr** [comment]
This has been resolved for a while. 

## **2023-09-09** - version 14

* Vet elasticsearch-7.x repo.
