### ISSUE TITLE
installation with centos CentOS v7.9 reporting [FATAL] This script is designed to only run on CentOS 7 servers

### ISSUE THREAD

**Issue by cobaltool** [cpanel/elevate#114]
I have an installation with centos CentOS v7.9.2009. I am following the instructions to use cPanel ELevate Project and to update them to almalinux.
After downloading the tool I ran / scripts / elevate-cpanel --check.
I get this error:
[FATAL] This script is designed to only run on CentOS 7 servers.
This despite my version of centos is 7
![2022-08-06_162618](https://user-images.githubusercontent.com/110815052/183374141-ccc21677-0c35-454c-b9ba-1677e5fd99d7.jpg)

**Comment by sloanebernstein** [comment]
Hello,

What version of cPanel is being used? Additionally, can you provide the output of `stat /var/cpanel/caches/Cpanel-OS` as run in the shell?

**Comment by cobaltool** [comment]
hello!
cpanel version: cPanel & WHM v104.0.7 (STANDARD) 

[root@server19 ~]# stat /var/cpanel/caches/Cpanel-OS
  File: ‘/var/cpanel/caches/Cpanel-OS’ -> ‘linux|centos|7|9|2009’
  Size: 21              Blocks: 0          IO Block: 4096   symbolic link
Device: 802h/2050d      Inode: 11797709    Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-12-09 09:58:31.921026928 +0100
Modify: 2021-12-09 09:58:31.921026928 +0100
Change: 2021-12-09 09:58:31.921026928 +0100
 Birth: -

**Comment by sloanebernstein** [comment]
This is caused by a flaw in the program. Line 603 should be comparing `Cpanel::OS::distro()` against `centos` (all lowercase) rather than `Centos`. #116 will fix this. Alternatively, it should not happen on cPanel version 106 and forward, because those know explicitly whether the distro supports ELevate. Thank you for letting us know about this issue.
