### ISSUE TITLE
One or more enabled YUM repo are currently unsupported

### ISSUE THREAD

**Issue by chopinesque** [cpanel/elevate#115]
Got this from Security advisor

One or more enabled YUM repo are currently unsupported. You should disable these repositories and remove packages installed from them before continuing the update. Consider reporting this limitation to https://github.com/cpanel/elevate/issues

**Comment by sloanebernstein** [comment]
Hello,

Can you provide us with the contents of the `/var/cpanel/elevate-blockers.security-advisor` file on your server?

**Comment by chopinesque** [comment]
1. elasticsearch is used by one of the server sites.
2. Not sure how to "provide those network interface cards new names"

```
{
   "blockers" : [
      {
         "id" : 14,
         "msg" : "One or more enabled YUM repo are currently unsupported.\nYou should disable these repositories and remove packages installed from them\nbefore continuing the update.\n\nConsider reporting this limitation to https://github.com/cpanel/elevate/issues\n",
         "repos" : [
            "EA4-experimental",
            "elasticsearch-5.x"
         ]
      },
      {
         "id" : 103,
         "msg" : "Your machine has multiple network interface cards (NICs) using kernel-names (ethX).\nSince the upgrade process cannot guarantee their stability after upgrade, you cannot upgrade.\n\nPlease provide those interfaces new names before continuing the update.\n"
      }
   ]
}

```

**Comment by toddr** [comment]
We explicitly did not support `EA4-experimental` in our original plan. Are you able to switch to EA4? do you use that repo?

**Comment by chopinesque** [comment]
It was installed a long time ago, so maybe EA4-experimental is not needed for it to work. How do I find out whether EA4 supports it? Can there be a switch on the repo without affecting current elasticsearch installation?

**Comment by gitcory** [comment]
We don't support EA4-experimental and it is not needed to run EasyApache4, only the EA4.repo is needed. You can disable EA4-experimental by disabling in the EA4-experimental file:

enabled=0

There are only a handful of packages there but none of them will affect elasticsearch.

**Comment by gitcory** [comment]
Just of note, in both cases, you can likely just enable=0 for both repos, then enable=1 after elevate is completed and do an update to get any packages that might need updating.

**Comment by chopinesque** [comment]
I have both EA4-experimental and elasticsearch.repo to **enabled=0**. When running the script, shouldn't elasticsearch be excluded from warnings as per https://github.com/cpanel/elevate/issues/63? Or should I ignore and just do as commented above (update despite the repo warning).

/scripts/elevate-cpanel --check
* 18-11:14:05 (315) [INFO] Successfully verified signature for cpanel (key types: release).
* 18-11:14:06 (3425) [ERROR] 1 package(s) installed from unsupported YUM repo 'elasticsearch-5.x' from /etc/yum.repos.d/.elasticsearch.repo
* 18-11:14:06 (2671) [WARN] *** Elevation Blocker detected: ***
One or more enabled YUM repo are currently unsupported.
You should disable these repositories and remove packages installed from them
before continuing the update.

**Comment by toddr** [comment]
I agree it shouldn't be complaining about stuff that's enabled=0. We can put a fix in for that. In the meantime, try just moving the repo file to `EA4-experimental.repo.off` and the code should ignore it.

**Comment by toddr** [comment]
Closing for now as I assume you've moved past this. we have opened #151 to address the `enabled` issue.
