### ISSUE TITLE
AlmaLinux 8 does not add new kernels to GRUB2's menu when BLS is disabled

### ISSUE THREAD

**Issue by sloanebernstein** [cpanel/elevate#117]
In #112, the script blocks if upgrading from CentOS 7 to AlmaLinux 8 will result in the system being configured to use the BLS format for storing boot entries, instead of the native GRUB2 format. This allows ELevate to upgrade the system, but it also results in future kernel updates not being listed in GRUB2's menu when they are installed to the system once on AlmaLinux 8. The reason for this is that the tools which have replaced the `grubby` program, which previously directly handled the changes to the GRUB2 configuration files but which no longer exists, only understand BLS.

Therefore, the solution adopted in #112 is unsustainable without further additions or changes.

**Comment by sloanebernstein** [comment]
The provider in question (Linode) [documents](https://www.linode.com/docs/guides/install-a-custom-distribution-on-a-linode/#configure-grub) that their version of GRUB2 uses `/boot/grub` as the value of `$prefix`, which matches the Debian convention, while RHEL-derived distros use `/boot/grub2` as `$prefix`. The provider [fixed](https://www.linode.com/community/questions/18148/node-unbootable-after-in-place-upgrade-to-fedora-30-converted-grub-config-to-bls#answer-68899) it by not just symlinking `/boot/grub/grub.cfg` to point to `/boot/grub2/grub.cfg`, but by symlinking the entire `/boot/grub` directory.

The implication is that if just the config file is symlinked, we can conclude that a stock Linode image of CentOS 7 is in use. This is what a current image does. The only other content of `/boot/grub` was a gzip-encoded XPM image.

```
# ls -l /boot/grub*
/boot/grub:
total 4
lrwxrwxrwx. 1 root root   20 May  3 14:02 grub.cfg -> /boot/grub2/grub.cfg
-rw-r--r--. 1 root root 1350 Nov 15  2011 splash.xpm.gz

/boot/grub2:
total 32
-rw-r--r--. 1 root root    64 May  3 14:02 device.map
drwxr-xr-x. 2 root root  4096 May  3 14:02 fonts
-rw-r--r--. 1 root root  3103 May  3 14:02 grub.cfg
-rw-r--r--. 1 root root  1024 May  3 14:02 grubenv
drwxr-xr-x. 2 root root 12288 May  3 14:02 i386-pc
drwxr-xr-x. 2 root root  4096 May  3 14:02 locale
```

If that is the state in which `/boot/grub` is found, we can safely perform the same mitigation by symlinking directories. There are several corner cases, however, which can still result in failure, both through action and inaction. We can also perform a WHOIS lookup on the IP cPanel reports as the licensed IP and match against a list of providers (again, in this case, just Linode).

Ideally, we could drop a shell script into `/etc/grub.d/` which emits a GRUB2 configuration script which saves the value of `$prefix` to the `grubenv` file and then read that out of the file when the system boots up again, but there's no way to do that without rebooting the system, which is to be avoided during an `elevate-cpanel --check` run. Furthermore, there's no trivial way to directly test whether GRUB can load the BLS module, because there doesn't appear to be an equivalent of `$()` in the GRUB config language, and `$?` isn't usefully set by commands which interact with GRUB modules.

**Comment by toddr** [comment]
What if we do:
```perl
return unless -e '/boot/grub';
die if anything besides grub.cfg in /boot/grub is in /boot/grub2
rename '/boot/grub', '/boot/grub.bak';
symlink('grub2', '/boot/grub');
cp /boot/grub.bak/* /boot/grub2/ # Except /boot/grub.bak/grub.cfg
```

**Comment by toddr** [comment]
I have removed all of the logic originally added to main related to #101. The code from 101 proved to create new problems we don't want to have to deal with long term.
