### ISSUE TITLE
BLOCKER (ish): warn of what EA4 profile items will not be available on 8

### ISSUE THREAD

**Issue by toddr** [cpanel/elevate#12]

**Comment by toddr** [comment]
What we want to know when we run `/usr/local/bin/ea_current_to_profile --target-os=AlmaLinux_8`

1. We need advice from ZC if we should be blocking on the presence of experimental packages.
2. If the package is not available on 8 because it's part of the distro, it's noise that we complain about this. We shouldn't be warning and the new json file should not include these packages.
3. If the package is available on 7 but not 8, we should block the elevation.

**Comment by atoomic** [comment]
Question: `exp` covers the group -1- Does `reg` covers 2 & 3 or -3- only?
Answer: 3 only, group 2 is silently ignored across the board (you won’t need ea-openssl (group 2), you may care that PHP 7.1 is not available (group 3))

Question: Does EA recommends to abort an elevation process when using some unsupported experimental c7 packages?
Answer: We shouldn’t abort

**Comment by toddr** [comment]
At this time, we think this case is working with the latest release of EA4.
