### ISSUE TITLE
CloudLinux 7 upgrade to CloudLinux 8

### ISSUE THREAD

**Issue by DouweXXL** [cpanel/elevate#125]
Hi, 

ELevate also supports elevating from CloudLinux 7 to CloudLinux 8. However, when running the elevate script on my CL7 development environment, I get the following error

```
[root@mycoolserver ~]# /scripts/elevate-cpanel --check
* 29-09:10:57 (597) [FATAL] This script is designed to only run on CentOS 7 servers.
```
Is it on the roadmap to support CL installations as well?

**Comment by toddr** [comment]
To our knowledge, it is not yet possible to upgrade from CL7 to CL8. until they do, we will not be able to support it. Rumor is they're in late-stage testing, and it may be sooner than later.
