### ISSUE TITLE
Tolerate out of date kernel for upgrade check.

### ISSUE THREAD

**Issue by toddr** [cpanel/elevate#130]
--check seems to be throwing a blocker if the system is not up to date. Does it need to do this? We auto-upgrade anyway before we run elevate? If nothing else it shouldn't block on kernels being out of date given cPanel usually blocks this for automatic upgrades.

**Comment by toddr** [comment]
Actually, let's only warn about it being out of date considering the upgrade will do a yum update anyway.

**Comment by atoomic** [comment]
```perl
sub _blocker_system_update ($self) {
    $self->has_blocker( 101, q[System is not up to date] ) unless _system_update_check();

    return 0;
}
```
