### ISSUE TITLE
One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8. Please remove these packages before continuing the update. - ea-apache24-mod-passenger

### ISSUE THREAD

**Issue by fabiot2** [cpanel/elevate#138]
Actually have the Nginx package and dont allow me to unninstall  ea-apache24-mod-passenger, also it says that 

 The system detected the following issues which would prevent cPanel ELevate from upgrading the system to AlmaLinux 8:
One or more enabled YUM repo are currently unsupported. You should disable these repositories and remove packages installed from them before continuing the update. Consider reporting this limitation to https://github.com/cpanel/elevate/issues
Issue with sshd configuration
System is not up to date
One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8. Please remove these packages before continuing the update. - ea-apache24-mod-passenger

**Comment by toddr** [comment]
You would need to remove `ea-apache24-mod-passenger` and all of its dependencies before you would be allowed to upgrade.
