### ISSUE TITLE
The system detected the following issues which would prevent cPanel ELevate from upgrading the system to AlmaLinux 8:

### ISSUE THREAD

**Issue by TheOldMan2000** [cpanel/elevate#143]
One or more enabled YUM repo are currently unsupported. You should disable these repositories and remove packages installed from them before continuing the update. Consider reporting this limitation to https://github.com/cpanel/elevate/issues
yum is not stable
cPanel thinks that this is a container-like environment, which this script cannot support at this time.
One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8. Please remove these packages before continuing the update. - ea-apache24-mod-cloudflare - ea-openssl-devel - ea-php80-php-libsodium - ea-php80-php-redis - ea-php81-php-redis

CentOS v7.9.2009 STANDARD virtuozzo
WHM 106.0.9
Cloud hosted VPS with Inmotion Hosting

**Comment by toddr** [comment]
Sorry but this is a limitation of container environments like virtuozzo. In cases where the instance is not fully virtualized, the leapp project we are based on cannot convert CentOS 7 to AlmaLinux 8.
