### ISSUE TITLE
User nobody can't execute files with kernelcare symlink patch installed

### ISSUE THREAD

**Issue by subz9tech** [cpanel/elevate#145]
A few servers that upgraded to Almalinux cannot complete AutoSSL DCV checks. 

Apache error_log returns the following during an AutoSSL DCV test.

```
[Tue Oct 04 16:48:53.x 2022] [cgi:error] [pid x] [client x:x] AH01215: (2)No such file or directory: exec of '/usr/local/cpanel/cgi-priv/get_local.cgi' failed: /usr/local/cpanel/cgi-priv/get_local.cgi
[Tue Oct 04 16:48:53.x 2022] [cgi:error] [pid x] [client x:x] End of script output before headers: get_local.cgi
```

We found that the user nobody can't execute files when the symlink patch for kernelcare is enabled.

```
[root@x ~]# su -s /bin/bash nobody -c '/bin/echo hello'
su: failed to execute /bin/bash: No such file or directory
[root@x ~]# kcarectl --unload
KernelCare protection disabled. Your kernel might not be safe
[root@x ~]# su -s /bin/bash nobody -c '/bin/echo hello'
hello
```

The issue doesn't appear to impact all servers upgrading to Almalinux, as the issue couldn't be reproduced. The kernelcare team expects to have a patch for the issue released early next week.

**Comment by toddr** [comment]
Hi, It appears that elevate upgraded your server but you are now having problems on 8. Please open a ticket with support for further investigation.
