### ISSUE TITLE
cpanel only postgresql-server Elevation blocker

### ISSUE THREAD

**Issue by danFbach** [cpanel/elevate#152]
Hello,

I've reduced my elevation blockers to the postgres warning only.

```
* 30-16:07:56 (2671) [WARN] *** Elevation Blocker detected: ***
You have postgresql-server version 9.2 installed.
This is upgraded irreversably to version 10.0 when you switch to AlmaLinux 8
We recommend data backup and removal of all postgresql packages before upgrade to AlmaLinux 8.
To re-install postgresql 9 on AlmaLinux 8, you can run: `dnf -y module enable postgresql:9.6; dnf -y install postgresql-server`
```

I ONLY have the cpanel postgres version installed.

```
yum list installed | grep postgres
cpanel-postgresql.x86_64                       9.2.24-1.cp1198       installed
cpanel-postgresql-libs.x86_64                  9.2.24-1.cp1198       installed
postgresql.x86_64                              9.2.24-8.el7_9        @updates
postgresql-devel.x86_64                        9.2.24-8.el7_9        @updates
postgresql-libs.x86_64                         9.2.24-8.el7_9        @updates
postgresql-server.x86_64                       9.2.24-8.el7_9        @updates
```

Will the cpanel postgres server be irreversibly upgraded as the message states, or since it is a cpanel package will it be handled differently?

- If i do not actually need to worry about this, perhaps the WARN can mitigated for cpanel packages so that users aren't given a false positive.
- If i do indeed need to backup the cpanel data and restore it after the upgrade, where are the files located that need to be backed/restored? And then will cpanel install the cpanel postgres 9.x package all on its own, or will i still need to run `dnf -y module enable postgresql:9.6; dnf -y install postgresql-server`?

**Comment by atoomic** [comment]
You currently have two versions of PostgreSQL: one from cPanel `cpanel-postgresql` and one from the distro `postgresql-server`.  The warning concerns the `postgresql-server` package only. The `cpanel-postgresql` package will be handled by cPanel during the upgrade. 

We recommend performing a backup of your databases for sanity purpose.
Keep in mind as mentioned in our disclaimer: https://cpanel.github.io/elevate/

> We recommend you back up (and ideally snapshot) your system so it can be easily restored before continuing.

Note that the current message  is a warning, not a blocker.
Without any other actions, your system `postgresql-server` will be upgraded to 10.

If you need to stay on a 9.x flavor, the hints provide you advice for that.

Hope this helps

**Comment by danFbach** [comment]
I'm sorry, i misread the output and should have instead used `yum list postgre*` to list the installed packages.
I don't actually use postgres for anything on my server, so i was only concerned about damaging the cpanel installation/package.
I've removed postgresql and the warning is gone, so i'm all good.
And yes, i have taken sufficient backups of my system.
Thank you for you help.
