### ISSUE TITLE
One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8.

### ISSUE THREAD

**Issue by sehost123** [cpanel/elevate#164]
One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8. Please remove these packages before continuing the update. - ea-php74-php-debuginfo - ea-php74-php-memcache-debuginfo - ea-php74-php-memcached-debuginfo 

So do we need to remove these PHP extensions?
php74-php-memcache
php74-php-memcached

and what is this one referring to? - ea-php74-php-debuginfo

**Comment by atoomic** [comment]
Reformatting for readability. The following packages are not available from EasyApache 4 on AlmaLinux 8
- ea-php74-php-debuginfo
- ea-php74-php-memcache-debuginfo 
- ea-php74-php-memcached-debuginfo

Will come back to you soon with a better answer.
thanks for your understanding

**Comment by atoomic** [comment]
Could you please run:
`/usr/local/bin/ea_current_to_profile --target-os=AlmaLinux_8`
and dump here the content of the `.json` file produced by this command?

thanks

**Comment by sehost123** [comment]
this?
{
   "version" : "1.0",
   "os_upgrade" : {
      "target_obs_project" : "CentOS_8",
      "source_os" : "CentOS v7.9.2009",
      "dropped_pkgs" : {
         "ea-php74-php-debuginfo" : "reg",
         "ea-php74-php-memcache-debuginfo" : "reg",
         "ea-php74-php-memcached-debuginfo" : "reg"
      },
      "target_os" : "AlmaLinux_8"
   },
   "tags" : [
      "Apache 2.4",
      "PHP 7.4",
      "PHP 8.1"
   ],
   "pkgs" : [
      "ea-apache24",
      "ea-apache24-config",
      "ea-apache24-config-runtime",
      "ea-apache24-mod_brotli",
      "ea-apache24-mod_bwlimited",
      "ea-apache24-mod_cache",
      "ea-apache24-mod_cache_disk",
      "ea-apache24-mod_cgid",
      "ea-apache24-mod_deflate",
      "ea-apache24-mod_file_cache",
      "ea-apache24-mod_headers",
      "ea-apache24-mod_http2",
      "ea-apache24-mod_mpm_event",
      "ea-apache24-mod_pagespeed",
      "ea-apache24-mod_proxy",
      "ea-apache24-mod_proxy_fcgi",
      "ea-apache24-mod_proxy_http",
      "ea-apache24-mod_proxy_wstunnel",
      "ea-apache24-mod_ssl",
      "ea-apache24-mod_suphp",
      "ea-apache24-mod_version",
      "ea-apache24-tools",
      "ea-apr",
      "ea-apr-util",
      "ea-brotli",
      "ea-cpanel-tools",
      "ea-documentroot",
      "ea-libargon2",
      "ea-libicu",
      "ea-libmemcached",
      "ea-libnghttp2",
      "ea-libtidy",
      "ea-libxml2",
      "ea-libzip",
      "ea-nghttp2",
      "ea-oniguruma",
      "ea-oniguruma-devel",
      "ea-openssl11",
      "ea-openssl11-devel",
      "ea-php-cli",
      "ea-php-cli-lsphp",
      "ea-php74",
      "ea-php74-libc-client",
      "ea-php74-pear",
      "ea-php74-php-bcmath",
      "ea-php74-php-bz2",
      "ea-php74-php-calendar",
      "ea-php74-php-cli",
      "ea-php74-php-common",
      "ea-php74-php-curl",
      "ea-php74-php-dba",
      "ea-php74-php-dbg",
      "ea-php74-php-devel",
      "ea-php74-php-enchant",
      "ea-php74-php-exif",
      "ea-php74-php-fileinfo",
      "ea-php74-php-fpm",
      "ea-php74-php-ftp",
      "ea-php74-php-gd",
      "ea-php74-php-gettext",
      "ea-php74-php-gmp",
      "ea-php74-php-iconv",
      "ea-php74-php-imap",
      "ea-php74-php-intl",
      "ea-php74-php-ioncube10",
      "ea-php74-php-ldap",
      "ea-php74-php-litespeed",
      "ea-php74-php-mbstring",
      "ea-php74-php-memcache",
      "ea-php74-php-memcached",
      "ea-php74-php-mysqlnd",
      "ea-php74-php-odbc",
      "ea-php74-php-opcache",
      "ea-php74-php-pdo",
      "ea-php74-php-pgsql",
      "ea-php74-php-posix",
      "ea-php74-php-process",
      "ea-php74-php-pspell",
      "ea-php74-php-snmp",
      "ea-php74-php-soap",
      "ea-php74-php-sockets",
     "ea-php74-php-tidy",
      "ea-php74-php-xml",
      "ea-php74-php-xmlrpc",
      "ea-php74-php-zip",
      "ea-php74-runtime",
      "ea-php81",
      "ea-php81-pear",
      "ea-php81-php",
      "ea-php81-php-bcmath",
      "ea-php81-php-bz2",
      "ea-php81-php-calendar",
      "ea-php81-php-cli",
      "ea-php81-php-common",
      "ea-php81-php-curl",
      "ea-php81-php-dba",
      "ea-php81-php-devel",
      "ea-php81-php-enchant",
      "ea-php81-php-exif",
      "ea-php81-php-fileinfo",
      "ea-php81-php-fpm",
      "ea-php81-php-ftp",
      "ea-php81-php-gd",
      "ea-php81-php-gmp",
      "ea-php81-php-iconv",
      "ea-php81-php-intl",
      "ea-php81-php-litespeed",
      "ea-php81-php-mbstring",
      "ea-php81-php-mysqlnd",
      "ea-php81-php-opcache",
      "ea-php81-php-pdo",
      "ea-php81-php-posix",
      "ea-php81-php-pspell",
      "ea-php81-php-soap",
      "ea-php81-php-xml",
      "ea-php81-php-zip",
      "ea-php81-runtime"
   ],
   "desc" : "Auto Generated profile",
   "name" : "Current EA4 State at 2022-12-13 12:14:24 +1030 modified for AlmaLinux_8"
}

**Comment by atoomic** [comment]
yes, thanks for providing your ea4 profile.
Could you also provide the content of your ea4 repo? probably the content of the file `/etc/yum.repos.d/EA4.repo`?

**Comment by sehost123** [comment]
[root@host2 ~]# ^V
bash: $'\026': command not found
[root@host2 ~]#

**Comment by drmuey** [comment]
@sehost123 Interesting, those `debuginfo` pkgs are not available for C7 so I wonder where they came from for you 🤔

Can you run the following commands on your C7 box in question and let us know the output?

1. `yum info ea-php74-php-debuginfo ea-php74-php-memcache-debuginfo ea-php74-php-memcached-debuginfo`
2. `cat /etc/yum.repos.d/EA4.repo`
3. `ls -l /etc/yum.repos.d/*.repo`
4. `grep -i ea4 /etc/yum.repos.d/*.repo`
5. `cat cat /etc/os-release`

Thanks!

**Comment by drmuey** [comment]
@sehost123 we have a fix coming to avoid this, meantime you can get around it by simply removing those packages (they are only useful for devs/admins debugging super low level package issues).

`yum erase -y ea-php74-php-debuginfo ea-php74-php-memcache-debuginfo ea-php74-php-memcached-debuginfo`

**Comment by drmuey** [comment]
`-debuginfo` pkgs will be ignored during elevate under `ea-cpanel-tools` v1.0-64

If you hit this problem either update `ea-cpanel-tools` to v1.0-64 or newer or uninstall the `-debuginfo` pkgs in question.

**Comment by drmuey** [comment]
**Solution**: If you hit this problem either update `ea-cpanel-tools` to v1.0-64 or newer or uninstall the `-debuginfo` pkgs in question.

**Comment by atoomic** [comment]
@sehost123 You should be unlock by removing the `*debuginfo` packages as suggested by @drmuey.
In the next few days one `ea-cpanel-tools` release will address the issue for any other users.

I'm going to close this case. If you think you need more support, please feel free to reopen it.

sincerely
nicolas

**Comment by atoomic** [comment]
Note: you can monitor the ea4 release from https://docs.cpanel.net/ea4/information/easyapache-4-release-notes/
