### ISSUE TITLE
 Your machine has multiple network interface cards (NICs)

### ISSUE THREAD

**Issue by graz68a** [cpanel/elevate#166]
Hello

when I execute this
/scripts/elevate-cpanel --check --upgrade-to=almalinux

I receive only this error

* 2022-12-14 09:24:24 [WARN] *** Elevation Blocker detected: ***
  Your machine has multiple network interface cards (NICs) using kernel-names (ethX).
  Since the upgrade process cannot guarantee their stability after upgrade, you cannot upgrade.
  Please provide those interfaces new names before continuing the update.

any idea how to remove this error ?
Thank you

**Comment by douwezijlstra-frl** [comment]
Allright - yes, what I would do;

1. Add the MAC address of eth0 to that interface using HWADDRESS=mac, you can get the mac address using 
```
ip link show eth0 | grep ether | awk '{print $2}
```
2. Rename DEVICE="eth0" to DEVICE="public_ipv4" (or whatever you want to call it) 

3. Move /etc/sysconfig/network-scripts/ifcfg-eth0 to /etc/sysconfig/network-scripts/ifcfg-public_ipv4 

and then either reboot or use 

```
ip link down eth0
ip link set eth0 name public_ipv4
ip link set up public_ipv4
```

That is how I do it, testing this out right now as well on a test server. But I am not from the cPanel/Elevate team - I would like them to clear this up/to somehow automate this. Adding the current hwaddress should be sufficient to prevent the mixing up of interfaces after upgrade I think, but that isn't enough to pass the checks.

**Comment by rklrkl** [comment]
I get this issue too (I suspect it's very common for CentOS 7 installs!) and I feel the cPanel elevate tool should explain how to rename interfaces because it's not obvious how to do it (even if it just displayed the URL of this issue, that might be good enough!).

Note that I have an AlmaLinux 8 VM install and it used the bizarre "ens18" and "ens19" for its two network interfaces I have on it. Those are the names I'm going to use to replace "eth0" and "eth1" respectively on my CentOS 7 cPanel install (which is also a VM, so I'll be using a virtual console onto it rather than ssh'ing into it when I do the interface renaming).

As has been said, it would be nice if the cPanel elevate tool would auto-rename network interfaces that it's currently fatally complaining about (i.e. the --check option turns it into a warning, telling the end-user what the old to new network interface renames will be so that they can ensure that things would be ready for the new interface names prior to running the upgrade for real).

**Comment by toddr** [comment]
Renaming these interfaces is complicated. We were loathed to give advice that might lead people to lose access to their servers. Can you tell me what online resources you used to make this happen?

**Comment by douwezijlstra-frl** [comment]
Hi Todd,

I used these sources;

https://tekneed.com/how-to-rename-nic-in-linux-centos-rhel-7-8/￼
How To Rename NIC In Linux (CentOS / RHEL 7 & 8)
tekneed.com
https://unix.stackexchange.com/questions/205010/centos-7-rename-network-interface-without-rebooting￼
CentOS 7 - Rename network interface without rebooting
unix.stackexchange.com
 
A potential approach to this could be to let a script;
- Back-up the interface configuration files
- Change the interface settings and restart interfaces/networking. In my case, bringing the old interface down and the interface with the new name up, didn’t close the ssh session
- Ask the user wether networking still works. If the user replies with ‘Y’ within, let’s say, 60 seconds, continue, else restore networking configuration. If the user loses connection, they obviously can’t even answer yes

But I do understand that not every configuration is equal, but (in my opinion) you may assume that the user performing ELevate is a sysadmin who has a back-up ready to be restored in case anything goes wrong.

**Comment by graz68a** [comment]
it's a very good idea your approach , anyone can code  it ?

**Comment by edbergavera** [comment]
@douwezijlstra-frl thank you for this. I will try this out. I'm on DigitalOcean, so hopefully, everything will be fine. I'll post my update here.

**Comment by chagwood** [comment]
> @douwezijlstra-frl thank you for this. I will try this out. I'm on DigitalOcean, so hopefully, everything will be fine. I'll post my update here soon.

I'm on DigitalOcean also. Eagerly awaiting your results!

**Comment by mattgroves** [comment]
I was able to get this to work on a DigitalOcean instance with the following whilst logged in via the console - not sure whether all these steps are necessary but including them for brevity:

```
mv /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/ifcfg-ens0
mv /etc/sysconfig/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts/ifcfg-ens1
ip link set eth0 name ens0
ip link set eth1 name ens1
sed -i 's/eth0/ens0/g' /etc/sysconfig/network-scripts/ifcfg-ens0
sed -i 's/eth1/ens1/g' /etc/sysconfig/network-scripts/ifcfg-ens1
sed -i 's/eth0/ens0/g' /etc/udev/rules.d/70-persistent-net.rules
sed -i 's/eth1/ens1/g' /etc/udev/rules.d/70-persistent-net.rules
reboot
```
The server came up fine:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether PRIVATE brd ff:ff:ff:ff:ff:ff
    inet PRIVATE/18 brd 178.62.127.255 scope global ens0
       valid_lft forever preferred_lft forever
    inet PRIVATE/16 brd PRIVATE scope global ens0
       valid_lft forever preferred_lft forever
    inet6 PRIVATE/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::3077:41ff:fe62:3a41/64 scope link 
       valid_lft forever preferred_lft forever
3: ens1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether PRIVATE brd ff:ff:ff:ff:ff:ff
    inet <PRIVATE>/16 brd PRIVATE scope global ens1
       valid_lft forever preferred_lft forever
    inet6 fe80::5c3e:3ff:fe78:133c/64 scope link 
       valid_lft forever preferred_lft forever
```
I believe that /etc/udev/rules.d/70-persistent-net.rules is key, otherwise the interface names will be reset.

**Comment by AndresReyesDev** [comment]
Hi Guys, I made a post a few months ago about this and some users have used it with no problems. Tested on multiple DigitalOcean servers.

[Resolving the ‘Multiple NICs Using ethX’ Error: Updating cPanel on CentOS 7 to Almalinux 8 / Rocky Linux 8](https://www.linkedin.com/pulse/resolving-multiple-nics-using-ethx-error-updating-7-8-reyes-galgani/)
