### ISSUE TITLE
Issue with sshd configuration

### ISSUE THREAD

**Issue by 1-2-1** [cpanel/elevate#167]
Running security advisor I see:

SSH direct root logins are permitted.
Manually edit /etc/ssh/sshd_config and change PermitRootLogin to “without-password” or “no”, then restart SSH.

- I checked and verified that PermitRootLogin  was set to no.
- I changed PermitRootLogin  to without-password & restarted the SSH service.  (same issue reported, so I reverted back to my previous 'no' setting)

I'm not sure how to resolve this.

**Comment by toddr** [comment]
Can you confirm you didn't change a commented line? you shouldn't have even needed to restart for the warning to go away.

**Comment by 1-2-1** [comment]
Thanks for that. How embarrassing for me.  That's exactly what the issue was. I completely overlooked that it was commented out.
I removed the # and saved the change, restarted SSH & verified this resolved.  Thanks Todd.

**Comment by toddr** [comment]
:) glad it was easy! Good luck!
