### ISSUE TITLE
One or more enabled YUM repo are currently unsupported.

### ISSUE THREAD

**Issue by 1-2-1** [cpanel/elevate#168]
Is there a command or script I can run to determine what repo or package is not supported?

If so, 
What is the command?

**Comment by toddr** [comment]
`/scripts/elevate-cpanel --check` should tell you what is unsupported.

**Comment by 1-2-1** [comment]
Thanks Todd. That identified the issue being with the cPkernel. 

* 2022-12-15 11:40:37 [WARN] Unsupported YUM repo enabled 'cPkernel' without packages installed from /etc/yum.repos.d/cPkernel.repo
* 2022-12-15 11:40:37 [WARN] *** Elevation Blocker detected: ***
  One or more enabled YUM repo are currently unsupported.
  You should disable these repositories and remove packages installed from them before continuing the update.


I'm still searching to see how I can fix cPkernel .  If you already know, please relay.

Thanks again for your help!

**Comment by 1-2-1** [comment]
I found this article & will be following it to remove the cPkernel.repo.

https://docs.cpanel.net/knowledge-base/security/how-to-manually-remove-the-cpanel-provided-hardened-kernel/

Thanks again Todd!
