### ISSUE TITLE
mysql config lost upon completion

### ISSUE THREAD

**Issue by danFbach** [cpanel/elevate#170]
I just realized today that after I migrated from CENTOS 7.9 to Alma my mariadb config file was replaced with the default config.
My mariadb version stayed the same, 10.5.

If this is intended to work this way - I don't remember a warning stating that this would happen. Some warnings would be nice as i would have definitely backed up my config file. transaction log settings were lost, query cache settings were lost, among many others.

If this is unintended - a my.cnf backup/restore should be executed. 

I don't see any reason why the config file should be replaced with the default, especially if the version is remaining the same.

**Comment by atoomic** [comment]
Thanks @danFbach for reaching out. Replacing that `my.cnf` file was definitively not intended.
We should at minimum provide a backup for that file.

Were you able to fix your server and restore the missing configuration?
So in your case, you were using mariadb-10.5 on C7 before starting the migration.
I wonder if the installation of the c8 package did not replaced the configuration file as this was not an upgrade but a new installation.

**Comment by danFbach** [comment]
I just rebuilt the configuration to the best of my ability. 
It isn't exactly what it was but it's good enough for now.
I was using mariadb-10.5 on C7 and am still using mariadb 10.5 on Alma.
I can confirm that this happened on the server that I elevated at the end on november (using elevate v2) as well as the one I completed last week, using elevate v3.
