### ISSUE TITLE
/scripts/elevate-cpanel --continue should fail if not in progress

### ISSUE THREAD

**Issue by toddr** [cpanel/elevate#174]
#173 opened a ticket and appeared to be running leapp directly and then later someone suggested they run continue. We need to be sure elevate-cpanel fails if it's not already in progress.

**Comment by sloanebernstein** [comment]
`get_stage()` returns `0` when the `stage_number` property can't be found in the stage file. This takes care of the pre-stage. `continue_elevation()` takes care of the `success` state, as well as re-running the entirety of stage 1 when this is returned, to ensure that the service is installed.

I think that means that the concern is in fact already addressed.

**Comment by toddr** [comment]
we don't believe this is actually still a problem after testing.
