### ISSUE TITLE
Monitoring existing upgrade (stage=4) process via: tail -f /var/log/elevate-cpanel.log

### ISSUE THREAD

**Issue by uyumsuzSami** [cpanel/elevate#178]
Hello

It stays like this, 1 hour has passed, but it doesn't do anything, what do you think is the problem?

`[root@server ~]# /scripts/elevate-cpanel --continue
* 2023-01-16 20:35:04 [WARN] The service elevate-cpanel.service is still running. Please wait for it to finish before restarting it.
* 2023-01-16 20:35:04 [INFO] # Monitoring existing upgrade (stage=4) process via: tail -f /var/log/elevate-cpanel.log
* 2023-01-16 19:59:13 (3897) [INFO] Running: /usr/bin/systemctl enable tailwatchd
* 2023-01-16 19:59:13 (3898) [INFO]
* 2023-01-16 19:59:13 (3912) [INFO] Created symlink /etc/systemd/system/multi-user.target.wants/tailwatchd.service → /etc/systemd/system/tailwatchd.service.
* 2023-01-16 19:59:13 (3929) [INFO]
* 2023-01-16 19:59:13 (3897) [INFO] Running: /usr/bin/systemctl stop tailwatchd
* 2023-01-16 19:59:13 (3898) [INFO]
* 2023-01-16 19:59:13 (3929) [INFO]
* 2023-01-16 19:59:13 (3897) [INFO] Running: /scripts/restartsrv_tailwatchd --stop
* 2023-01-16 19:59:13 (3898) [INFO]
* 2023-01-16 19:59:13 (3912) [INFO] Service “tailwatchd” is already stopped.
* 2023-01-16 19:59:13 (3912) [INFO]
* 2023-01-16 19:59:13 (3912) [INFO] tailwatchd stopped successfully.
* 2023-01-16 19:59:13 (3929) [INFO]
* 2023-01-16 19:59:13 (3897) [INFO] Running: /scripts/restartsrv_dovecot --stop
* 2023-01-16 19:59:13 (3898) [INFO]
* 2023-01-16 19:59:13 (3912) [INFO] Service “dovecot” is already stopped.
* 2023-01-16 19:59:13 (3912) [INFO]
* 2023-01-16 19:59:13 (3912) [INFO] dovecot stopped successfully.
* 2023-01-16 19:59:13 (3929) [INFO]
* 2023-01-16 19:59:13 (3897) [INFO] Running: /scripts/restartsrv_exim --stop
* 2023-01-16 19:59:13 (3898) [INFO]
* 2023-01-16 19:59:14 (3912) [INFO] Service “exim” is already stopped.
* 2023-01-16 19:59:14 (3912) [INFO]
* 2023-01-16 19:59:14 (3912) [INFO] Log Messages
* 2023-01-16 19:59:14 (3912) [INFO]     2023-01-16 19:43:44 exim 4.96 daemon started: pid=657, -q15m, listening for SMTP on port 25 (IPv6 and IPv4) port 587 (IPv6 and IPv4) and for SMTPS on port 465 (IPv6 and IPv4)
* 2023-01-16 19:59:14 (3912) [INFO]
* 2023-01-16 19:59:14 (3912) [INFO] exim stopped successfully.
* 2023-01-16 19:59:14 (3929) [INFO]
* 2023-01-16 19:59:14 (3897) [INFO] Running: /usr/bin/rm -rf /root/.cpanel/datastore
* 2023-01-16 19:59:14 (3898) [INFO]
* 2023-01-16 19:59:14 (3929) [INFO]
* 2023-01-16 19:59:14 (3897) [INFO] Running: /usr/local/bin/ea_install_profile --install /etc/cpanel/ea4/profiles/custom/current_state_at_2023-01-16_19:50:17_modified_for_AlmaLinux_8.json
* 2023-01-16 19:59:14 (3898) [INFO]
* 2023-01-16 19:59:41 (415) [INFO] # Monitoring existing upgrade (stage=4) process via: tail -f /var/log/elevate-cpanel.log
* 2023-01-16 20:06:36 (415) [INFO] # Monitoring existing upgrade (stage=4) process via: tail -f /var/log/elevate-cpanel.log
* 2023-01-16 20:29:23 (415) [INFO] # Monitoring existing upgrade (stage=4) process via: tail -f /var/log/elevate-cpanel.log
* 2023-01-16 20:33:52 (459) [WARN] The service elevate-cpanel.service is still running. Please wait for it to finish before restarting it.
* 2023-01-16 20:33:52 (415) [INFO] # Monitoring existing upgrade (stage=4) process via: tail -f /var/log/elevate-cpanel.log
* 2023-01-16 20:35:04 (459) [WARN] The service elevate-cpanel.service is still running. Please wait for it to finish before restarting it.
* 2023-01-16 20:35:04 (415) [INFO] # Monitoring existing upgrade (stage=4) process via: tail -f /var/log/elevate-cpanel.log

`

[root@server ~]# /scripts/elevate-cpanel --status
Running stage 4 / 5
[root@server ~]#

**Comment by uyumsuzSami** [comment]
* 2023-01-16 20:51:21 (653) [INFO] Sending notification: Fail to update to AlmaLinux 8
* 2023-01-16 20:51:21 (658) [ERROR] The elevation process failed during stage 4.
* 2023-01-16 20:51:21 (658) [ERROR]
* 2023-01-16 20:51:21 (658) [ERROR] You can continue the process after fixing the errors by running:
* 2023-01-16 20:51:21 (658) [ERROR]
* 2023-01-16 20:51:21 (658) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel --continue
* 2023-01-16 20:51:21 (658) [ERROR]
* 2023-01-16 20:51:21 (658) [ERROR] You can check the error log by running:
* 2023-01-16 20:51:21 (658) [ERROR]
* 2023-01-16 20:51:21 (658) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel
* 2023-01-16 20:51:21 (658) [ERROR]
* 2023-01-16 20:51:21 (658) [ERROR] Last Error:
* 2023-01-16 20:51:21 (658) [ERROR]
* 2023-01-16 20:51:21 (658) [ERROR] Fail to restore MySQL 10.6 at /usr/local/cpanel/scripts/elevate-cpanel line 1827.
* 2023-01-16 20:51:31 (525) [FATAL] Fail to restore MySQL 10.6 at /usr/local/cpanel/scripts/elevate-cpanel line 1827.

**Comment by atoomic** [comment]
thanks for providing some details, it looks like that the installation of MySQL 10.6 failed
This is performed using the following command:
```
/usr/local/cpanel/bin/whmapi1 start_background_mysql_upgrade version=10.6
```
You should be able to find the mysql update log from (where you need to provide the `~ID~` )
```
 /var/cpanel/logs/mysql_upgrade.~ID~/unattended_background_upgrade.log
```

Would you mind providing the mysql upgrade log so we can check what went wrong?
Depending on the issue, it s also possible that running the upgrade process a second time fixed it.

Once MySQL is restored you would then be able to run: `/scripts/elevate-cpanel --continue`

**Comment by uyumsuzSami** [comment]
Hello

```
[root@server ~]# /usr/local/cpanel/bin/whmapi1 start_background_mysql_upgrade version=10.6
/usr/local/cpanel/whostmgr/bin/.xml-api: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory
Use of uninitialized value in subroutine entry at /usr/local/cpanel/Cpanel/UTF8/Strict.pm line 36.
Cpanel::Exception::JSONParseError/(XID qweph4) The system failed to parse the JSON stream data “” for the caller “bin::apitool::run” because of an error: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/local/cpanel/Cpanel/JSON.pm line 128.

 at /usr/local/cpanel/C
panel/JSON.pm line 147.
        Cpanel::JSON::_throw_json_error("malformed JSON string, neither tag, array, object, number, st"..., undef, SCALAR(0x8f18e8)) called at /usr/local/cpanel/Cpanel/JSON.pm line 128
        Cpanel::JSON::Load("") called at bin/apitool.pl line 380
        bin::apitool::_json_utf8_safe_load_ref(SCALAR(0x8f18e8)) called at bin/apitool.pl line 323
        bin::apitool::_generate_result_in_output_format("yaml", SCALAR(0x8f18e8)) called at bin/apitool.pl line 369
        bin::apitool::_run_whm_function(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, HASH(0x8f09a0), HASH(0x10b2010)) called at bin/apitool.pl line 230
        bin::apitool::_whm_api_handler(HASH(0x10ca2e0)) called at bin/apitool.pl line 121
        bin::apitool::run("start_background_mysql_upgrade", "version=10.6") called at bin/apitool.pl line 39
[root@server ~]#

```


[unattended_upgrade.log](https://github.com/cpanel/elevate/files/10434950/unattended_upgrade.log)

I did 8 servers, it was a problem, this one exploded and there is no sql backup.

**Comment by atoomic** [comment]
Please open a cPanel support ticket so we can investigate. Having the file `whostmgr/bin/.xml-api` is strange and probably indicates an incorrect license.
thanks
