### ISSUE TITLE
Google Compute Engine: unsupported YUM repos

### ISSUE THREAD

**Issue by lukwam** [cpanel/elevate#182]
I'm getting the following errors about the elevate upgrade running on a Google Cloud GCE instance.  These are the packages that Google installs on their CENTOS 7 base images to support working with GCP resources. Also I have Docker installed on this host. 

```
# sudo /scripts/elevate-cpanel --check
* 2023-01-25 16:35:31 [ERROR] 5 package(s) installed from unsupported YUM repo 'google-compute-engine' from /etc/yum.repos.d/google-cloud.repo
* 2023-01-25 16:35:31 [ERROR] 1 package(s) installed from unsupported YUM repo 'google-cloud-sdk' from /etc/yum.repos.d/google-cloud.repo
* 2023-01-25 16:35:31 [ERROR] 1 package(s) installed from unsupported YUM repo 'google-cloud-ops-agent' from /etc/yum.repos.d/google-cloud-ops-agent.repo
* 2023-01-25 16:35:31 [ERROR] 6 package(s) installed from unsupported YUM repo 'docker-ce-stable' from /etc/yum.repos.d/docker-ce.repo
* 2023-01-25 16:35:31 [WARN] Unsupported YUM repo enabled 'google-cloud-logging' without packages installed from /etc/yum.repos.d/google-cloud-logging.repo
* 2023-01-25 16:35:31 [WARN] Unsupported YUM repo enabled 'google-cloud-monitoring' without packages installed from /etc/yum.repos.d/google-cloud-monitoring.repo
* 2023-01-25 16:35:31 [WARN] *** Elevation Blocker detected: ***
  One or more enabled YUM repo are currently unsupported.
  You should disable these repositories and remove packages installed from them
  before continuing the update.
```

Problematic repos:
* `google-compute-engine`
* `google-cloud-sdk`
* `google-cloud-ops-agent`
* `docker-ce-stable`
* `google-cloud-logging`
* `google-cloud-monitoring`

I don't know if anyone has tried doing an in-place os upgrade on a GCE-hosted cpanel instance before, but I'm willing to try it with this test instance I have.

**Comment by toddr** [comment]
We recommend you remove those repos and their related RPMs, if possible, and then re-run the upgrade. My one caution to you will be that you be sure there is no data loss associated with the packages before you begin. At which point, you can re-install them when you're done. This is essentially how `elevate-cpanel` works on stuff we support.

**Comment by toddr** [comment]
@lukwam did this solve your issue?

**Comment by lukwam** [comment]
Thanks for your help! I haven't gone the route of trying the in-place upgrade yet.  I still have until 2024 to get off centos7. So I spent a little time trying out some of the newer Linuxen, such as ArchLinux and Rocky Linux. One I figure out the best option for me to use on GCP, I'll do a blog post about it.  But we can close this issue in the meantime!
