### ISSUE TITLE
Command line option to use development leapp repository

### ISSUE THREAD

**Issue by toddr** [cpanel/elevate#183]
Regarding the elevate-cpanelscript that is used for upgrading systems with cPanel: would introducing a switch to select where to install the leapp-upgradepackage from be acceptable?

More specifically, AlmaLinux maintains two repositories with that package and dependencies - one is the main https://repo.almalinux.org/elevate/ repo, and the other is https://repo.almalinux.org/elevate/testing/.

The modifications that make upgrading from CloudLinux are only present in the testing repo, which is why I'm bringing up the whole thing.

**Comment by atoomic** [comment]
We should provide an option to use any custom repo url
