### ISSUE TITLE
Detect absolute symlinks from / and block

### ISSUE THREAD

**Issue by toddr** [cpanel/elevate#188]
this blocker was seen in #186 cpanel-elevate should detect and block on this.

```
Risk Factor: high (inhibitor)
Title: Upgrade requires links in root directory to be relative
Summary: After rebooting, parts of the upgrade process can fail if symbolic links in / point to absolute paths.
Please change these links to relative ones.
Remediation: [command] sh -c ln -snf var/lib/snapd/snap /snap
Key: 3d895ad37ceaf4157864d439edb6bd75562061fa
```

**Comment by RicRey1988** [comment]
Placing this command does nothing more than output an error that does not exist ln

`sh -c ln -snf var/lib/snapd/snap /snap`

**Comment by toddr** [comment]
Regardless of the bad advice from leapp, it appears to not like root symlinks to point to absolute paths. We can detect and block on this in elevate-cpanel which prevents customers from being left in a partially upgraded state.

**Comment by toddr** [comment]
This is the change you're trying to make:

```
$>ln -s /var/lib/snapd/snap /snap
$>ls -ld /snap
lrwxrwxrwx 1 root root 19 Jan 30 16:24 /snap -> /var/lib/snapd/snap

# Then...
$>ln -snf var/lib/snapd/snap /snap
$>ls -ld /snap                    
lrwxrwxrwx 1 root root 18 Jan 30 16:24 /snap -> var/lib/snapd/snap
```

**Comment by selvauth** [comment]
I am not able to see this folder in my vm var/lib/snapd/snap
