### ISSUE TITLE
"One or more enabled YUM repo are currently unsupported."

### ISSUE THREAD

**Issue by macsrwe** [cpanel/elevate#189]
Here is the entirety of the informational message I am receiving:

```
The system detected the following issues which would prevent cPanel ELevate from upgrading the system 
to AlmaLinux 8:
One or more enabled YUM repo are currently unsupported. You should disable these repositories and 
remove packages installed from them before continuing the update. Consider reporting this limitation to 
https://github.com/cpanel/elevate/issues
```

I am not a professional sysadmin, nor a yum devotee. It sure would be helpful if this message would provide some guidance as to HOW to identify WHICH repo(s) are unsupported, and HOW to disable and remove them. A link to a document page would be super. No such existing documentation is returned when doing a web search for this error message.

**Comment by PHPism** [comment]
I faced the same issue today.
Logged in as root, use SSH or terminal from WHM.
1-Run the check command: 
`/scripts/elevate-cpanel --check --upgrade-to=almalinux`
It will give you more information about these packages and repo name.
2- search these packages (Replace repoName with the name that appear in the check results):
`yum list installed | grep @repoName`
You may find empty packages names if their names are very long. In that case use this command to show them:
`yum list installed | grep -B1 repoName`
3- (Replace packageName with the packages name from previous command):
`yum remove packageName`
4- search for the exact repo name to remove:
`rpm -qa | grep repoName`
5- Remove the repo itself since it will re-appear as a warning again:
yum remove exactRepoName
--
Then re-run the check.
I have done it for 7 servers this morning, so I believe I ran into almost all the issues ^_^

**Comment by macsrwe** [comment]
Thank you -- you're a gentleman and a scholar.

The bogey repos identified are called ul, ul_justhost, and hgdedi. Given they contain the strings "justhost" and "dedi", I was reluctant to proceed to the "remove" step out of fear that they may contain code specific to my hosting provider, and I didn't want to damage my configuration. 

Is it safe to remove these or not? 
Do I need to replace them with a supported version, will they replace themselves, or are they just vestigial?

Thanks for your help.

**Comment by PHPism** [comment]
@macsrwe : You are welcome. I'm glad that I helped.
However, I ran into some servers from some of my clients hosted in different data centers and yes indeed they had some custom configurations.
I prefer that you remove only packages that you manually installed and know what they do and either find a compatible replacement or remove unused packages (At least that was my case).
So, I recommend that you contact your host first and search these packages name to understand what they do and remove when you are sure that it won't break your machine.
At least now you know what you are looking for.
Best regards.

**Comment by macsrwe** [comment]
@PHPism Thanks. I manually installed nothing here, it was a provided VM. Hence I'm not really familiar with the intricacies of yum. So I will ask my provider what they recommend before proceeding.

**Comment by fogelfish** [comment]
In case someone else is in a similar situation as me (your VM is hosted by DigitalOcean as a "Droplet") and hasn't yet talked with DO support, you won't be able to elevate to AlmaLinux.:  _"Changing the network interface is not possible and it may render your Droplets network broken. An in-place upgrade of your CentOS distribution to AlmaLinux is not something we recommend or can support."_ 

Also there's this:

> 1 package(s) installed from unsupported YUM repo 'digitalocean-agent' from /etc/yum.repos.d/digitalocean-agent.repo`

**Comment by macsrwe** [comment]
@fogelfish Right... I was already told by justhost not to worry about the actual elevation, they would take care of it "when it's time." I just wanted to correct the annoying weekly nag mail about running on unsupported repos.

**Comment by Harwerp** [comment]
Hi, I just got this same message.

* 2023-08-13 23:34:51 [WARN] Your system is not up to date please run: /usr/bin/yum update
* 2023-08-13 23:34:51 [WARN] *** Elevation Blocker detected: ***
System is not up to date
* 2023-08-13 23:35:25 [ERROR] 5 package(s) installed from unsupported YUM repo 'google-compute-engine' from /etc/yum.repos.d/google-cloud.repo
* 2023-08-13 23:35:25 [ERROR] 1 package(s) installed from unsupported YUM repo 'google-cloud-sdk' from /etc/yum.repos.d/google-cloud.repo
* 2023-08-13 23:35:25 [ERROR] 1 package(s) installed from unsupported YUM repo 'google-cloud-ops-agent' from /etc/yum.repos.d/google-cloud-ops-agent.repo
* 2023-08-13 23:35:25 [WARN] *** Elevation Blocker detected: ***
One or more enabled YUM repo are currently unsupported and have installed packages.
You should disable these repositories and remove packages installed from them
before continuing the update.

any idea?
I'm using gcloud GCP

**Comment by toddr** [comment]
Hi, we encourage you to open a ticket with cPanel support for further assistance.
