### ISSUE TITLE
Support for upgrades from CloudLinux 7

### ISSUE THREAD

**Issue by commandhost** [cpanel/elevate#192]
This project currently only supports upgrades from Centos 7, CloudLinux 7 is not currently supported.

The CloudLinux Elevate project supports upgrading from CloudLinux 7 to CloudLinux 8, BUT only without cPanel.

**Comment by sloanebernstein** [comment]
Hello,

The banner reporting this in WHM is being fixed in cPanel as case ID CPANEL-42362. When the fix to 108 is published, that ID will appear in our [108 Changelog](https://docs.cpanel.net/changelogs/108-change-log/).

**Comment by commandhost** [comment]
> 

So is CloudLinux 7 supported currently ?

**Comment by sloanebernstein** [comment]
CloudLinux 7 is not currently supported, but our intent is to have this working in the future. We cannot give an estimate as to when that support will be ready.

**Comment by commandhost** [comment]
If support for CloudLinux 7 is planned why not leave this issue open until its supported?

At least then people can subscribe to notifications on this issue.
