### ISSUE TITLE
Possible locale issues makes upgrade behave unexpectedly? (Lost bash after the 4th reboot, elevate won't continue)

### ISSUE THREAD

**Issue by cglmicro** [cpanel/elevate#197]
Hi.
Around the 4th reboot, the bash stop working and the elevate process can't continu. Basic commands like "ls" aren't working:
`Last login: Sat Feb 18 20:36:02 2023
# -----------------------------------------------------------------------------
#
# /!\ ELEVATE IN PROGRESS /!\
#
# Do not make any changes until it's complete
# you can check the current process status by running:
#
#           /scripts/elevate-cpanel --status
#
# Or monitor the progress by running:
#
#           /scripts/elevate-cpanel --log
#
# -----------------------------------------------------------------------------
-bash: /usr/local/cpanel/3rdparty/bin/perl: No such file or directory
-bash: tr: No such file or directory
-bash: readlink : commande introuvable
-bash: basename : commande introuvable
-bash: /usr/local/cpanel/3rdparty/bin/perl: No such file or directory
-bash: /usr/local/cpanel/3rdparty/bin/perl: No such file or directory
[root@agrico ~]# ls
-bash: ls : commande introuvable`

This is a test upgrade, and I have a snapshot of the VM. I tried it twice with the same result, but I can try something else if you need me to.
Thanks !

**Comment by toddr** [comment]
Do you have any logs we could look at? If possible, please open a ticket with support.

**Comment by toddr** [comment]
What is your locale/lang set to on a basic shell pre-upgrade? `export | grep L`

**Comment by atoomic** [comment]
Would you mind providing the following files:
- /var/log/leapp/leapp-upgrade.log
- /var/log/leapp/leapp-report.txt
- /var/log/leapp/leapp-report.json

**Comment by atoomic** [comment]
The output from the `elevate.service` would also be useful you can get it via 
`journalctl -n1000 -u elevate-cpanel.service`

**Comment by cglmicro** [comment]
I can’t run the journalctl command, bash is not working.

De : ℕicolas ℝ. ***@***.***>
Envoyé : 20 février 2023 12:52
À : cpanel/elevate ***@***.***>
Cc : info ***@***.***>; Author ***@***.***>
Objet : Re: [cpanel/elevate] Lost bash after the 4th reboot, elevate won't continue (Issue #197)


The output from the elevate.service would also be useful you can get it via
journalctl -n1000 -u elevate-cpanel.service

**Comment by cglmicro** [comment]
Here is the 3 files.

For the "journalctl" command, bash is not working so I can't provide.

For the "export | grep L", this is what I have PRE-UPGRADE:
declare -x LANG="fr_CA.UTF-8"
...
declare -x SHELL="/bin/bash"

[leapp-upgrade.zip](https://github.com/cpanel/elevate/files/10788428/leapp-upgrade.zip)

Thank you !

**Comment by toddr** [comment]
We speculate that you can make this go away by clearing LANG or setting it to "C". 

If so this is a bug on our part. Or maybe leapp. We thought we had protections in place for this already. If you'd like to try clearing it in your files and attempting an upgrade, we'd love to know if it fixes things for you. 

You might try `grep -Rl fr_CA /` and temporarily changing the places that set the lang It might be a global file not just root's bash files.

**Comment by cglmicro** [comment]
Hi toddr.
I'm really sorry, but I don't understand what I need to do.
Where should I run the grep mentionned, in / or in a subfolder?
What am I looking for and what do I need to change?
Here is a result of the grep in the /root folder:
`[root@agrico ~]# pwd
/root
[root@agrico ~]# grep -Rl fr_CA
anaconda-ks.cfg
.cpanm/work/1594997978.15302/version-0.9924/t/07locale.t
.cpanm/latest-build/version-0.9924/t/07locale.t
test-mysqldump.sql
`

Just in case and while I wait for your answer, I did 
localectl set-locale LANG=en_US.utf8
then I rebooted and I'll try another upgrade to almalinux.

Thank you.

**Comment by cglmicro** [comment]
For your information, even with localectl set-locale LANG=en_US.utf8 it's stuck at the same step without a working bash.
What should I do next?
Thank you.

**Comment by cglmicro** [comment]
It finally work about 1 hours later. I left the server running and I received an email at 21h37 confirming that the update was finished. The previous attempt did not concluded even when I left the server running hours.
bash
I don't know if it's a normal behaviour that bash can't be used midway in the procedure, letting me beleive it's broken?

**Comment by atoomic** [comment]
note setting the locale would not really help as we perform multiple reboot.
If we want to fix locale correctly we should set an environment variable in the service used for elevate

**Comment by toddr** [comment]
Thanks for your response. We're going to spend some time to see if we can reproduce this issue. Our working theory is that your `LANG="fr_CA.UTF-8"` might have caused something to misbehave.

Glad you've upgraded to 8 and are good to go!
