### ISSUE TITLE
Need a manual update blocker 

### ISSUE THREAD

**Issue by jasonmpotter** [cpanel/elevate#198]
I work as a Senior Linux SA with a major cPanel partner and we are starting to see customers shooting themselves in the foot trying to upgrade their production systems without consulting support first. 

As a matter of policy, we do not offer OS upgrades due to the various headaches they can cause for seasoned technical staff let alone less sophisticated customers who trust cPanel and see the notices for ELevate as a solution they can trust. So they charge forward and inadvertently brick their systems. 

I would like to see a manual update blocker built-in to the ELevate project. Just a simple /etc/disableelevate or similar that will cause the script to abort early with the failure message like: 

ELevate has been disabled on this server. Please contact your server provider support for assistance with upgrading to Alma/Rocky Linux.

It's a low lift solution that we can't get out in the wild fast enough as it can save many hours of frustration on both sides of the technical support coin. Thanks for your time.

**Comment by jasonmpotter** [comment]
Even better, have the failure message be read right out of the /etc/disableelevate blocker file. Then hosting providers of all brands can manage the message they want to display to customers.

**Comment by jasonmpotter** [comment]
After more digging into this feature request, I was able to partially implement in on our end, but it relies on making the blocker files immutable. This will suffice, but a  solution for custom blockers should still be a light lift solution and completely doable. It's essentially a mirror of of the OVH blockers, just one where we can specify the message and the detecting file path. 

----i--------e-- /var/cpanel/elevate-blockers.security-advisor
----i--------e-- /var/cpanel/elevate-blockers

the security advisor file, accept HTML in the msg while the other relies on \n

**Comment by toddr** [comment]
Thank you for the request. We are loathed to tell someone with root that they cannot upgrade. A compromise we intend to implement is that if the file `/var/cpanel/elevate-noc-recommendations` is present when they have started their upgrade, it will emit the contents of the file to the console and give them a `proceed? (yes/no)`. 

Hopefully, this will provide mitigation for your concern?

**Comment by jasonmpotter** [comment]
HI Todd, thanks for the response and the compromise. It's a good one for sure and I understand your position with denying someone with root from performing any operation. Unfortunately, server owners are granted root regardless of skill level due to needing to access WHM to manage the server. We offer fully managed cPanel servers so we are confident that customers will prefer our stance on non-in-place upgrades in favor of a dedicated migrations team. This is how we've always operated, so it won't be jarring to our customer base.

Unfortunately, we've already had several customers blunder into this already, hence the urgency tone in my initial request.  We realize that these situations are indeed the fault of the user who did not do their do diligence before disembarking on the upgrade journey. But we feel the project itself is too problematic for our mostly unsophisticated userbase. 

I will close this out with your compromise as an accepted solution and fully appreciate your attention and work done on the project thus far. Maybe several months down the road, the upgrade process will be better positioned to handle the various edge cases that cause systems to brick themselves during these upgrades. The easyapache upgrade from 3 to 4 was something we had to quarantine from users as well until it had worked out most the kinks and we had a proper set of "undo" procedures. I'm confident you and the team will end up there on this one as well.

Good luck and thanks for the support!

**Comment by jasonmpotter** [comment]
Had difficulty testing this, but now that I reread it, this isn't implemented yet. It will indeed be an acceptable solution for us, just need it working so I'll leave this open until it's actually resolved.
