### ISSUE TITLE
error /usr/bin/leapp upgrade

### ISSUE THREAD

**Issue by mohamedtl4s** [cpanel/elevate#199]
* 2023-02-23 15:17:23 (1412) [INFO] ******************************************************************************************
* 2023-02-23 15:17:23 (1413) [INFO] *
* 2023-02-23 15:17:23 (1414) [INFO] * Starting stage 3 of 5
* 2023-02-23 15:17:23 (1415) [INFO] *
* 2023-02-23 15:17:23 (1416) [INFO] ******************************************************************************************
* 2023-02-23 15:17:23 (1169) [INFO] Stage 3: skipping prep_for_leapp (already run)
* 2023-02-23 15:17:23 (1713) [INFO] Running leapp upgrade
* 2023-02-23 15:17:23 (4078) [INFO] Running: /usr/bin/leapp upgrade
* 2023-02-23 15:17:23 (4079) [INFO] 
* 2023-02-23 15:17:23 (4093) [INFO] Traceback (most recent call last):
* 2023-02-23 15:17:23 (4093) [INFO]   File "/usr/bin/leapp", line 5, in <module>
* 2023-02-23 15:17:23 (4093) [INFO]     from pkg_resources import load_entry_point
* 2023-02-23 15:17:23 (4093) [INFO]   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
* 2023-02-23 15:17:23 (4093) [INFO]     import packaging.requirements
* 2023-02-23 15:17:23 (4093) [INFO]   File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 60, in <module>
* 2023-02-23 15:17:23 (4093) [INFO]     MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
* 2023-02-23 15:17:23 (4093) [INFO] TypeError: __call__() takes exactly 2 arguments (1 given)
* 2023-02-23 15:17:23 (4110) [INFO] 
* 2023-02-23 15:17:23 (657) [INFO] Sending notification: Fail to update to AlmaLinux 8
* 2023-02-23 15:17:23 (662) [ERROR] The elevation process failed during stage 3.
* 2023-02-23 15:17:23 (662) [ERROR] 
* 2023-02-23 15:17:23 (662) [ERROR] You can continue the process after fixing the errors by running:
* 2023-02-23 15:17:23 (662) [ERROR] 
* 2023-02-23 15:17:23 (662) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel --continue
* 2023-02-23 15:17:23 (662) [ERROR] 
* 2023-02-23 15:17:23 (662) [ERROR] You can check the error log by running:
* 2023-02-23 15:17:23 (662) [ERROR] 
* 2023-02-23 15:17:23 (662) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel
* 2023-02-23 15:17:23 (662) [ERROR] 
* 2023-02-23 15:17:23 (662) [ERROR] Last Error:
* 2023-02-23 15:17:23 (662) [ERROR] 
* 2023-02-23 15:17:23 (662) [ERROR] The 'leapp upgrade' process failed.
* 2023-02-23 15:17:23 (662) [ERROR] 
* 2023-02-23 15:17:23 (662) [ERROR] Please investigate, resolve then re-run the following command to continue the update:
* 2023-02-23 15:17:23 (662) [ERROR] 
* 2023-02-23 15:17:23 (662) [ERROR]     /scripts/elevate-cpanel --continue
* 2023-02-23 15:17:23 (529) [FATAL] The 'leapp upgrade' process failed.

**Comment by toddr** [comment]
We recommend you open a ticket with cPanel support for further assistance. Thanks!

**Comment by toddr** [comment]
This may be an upstream issue. I've reported it to upstream via https://github.com/AlmaLinux/leapp-repository/issues/70

**Comment by maverick85** [comment]
I got this error as well exact same but in the end the problem was openssl11-libs installed. Removing it fixed the problem. The `leapp-upgrade.log` file had the answer
