### ISSUE TITLE
Stage/success file should record which version(s) performed the upgrade

### ISSUE THREAD

**Issue by sloanebernstein** [cpanel/elevate#202]
As a developer for the `cpanel-elevate` script and for the cPanel/WHM software, I would like to be able to reliably know which version (or versions) of the script coordinated the upgrade operation.

#190 presented a problem which not only needed to be fixed in the script but also needed an autofixer to adjust upgrades performed prior to fixing that bug. It turns out that there is an indirect way to determine that information, but it relies upon the fact that only upgrades from EL7 to EL8 are supported at this time, and it also assumes that the administrator did not manually invoke `elevate-cpanel --update` after conversion. By recording this information into the stage file, any future issues which may require fixing after the fact could learn this information easily and with complete certainty.

At the very least, the version should be recorded at one known point during the upgrade, but there may also be utility in recording it at multiple points, in case an update during the process is required to bring it to completion.

**Comment by toddr** [comment]
RE-87
