### ISSUE TITLE
elevate-blockers Yum package "panopta.repo" and EasyApache 4 "ea-apache24-mod-passenger"

### ISSUE THREAD

**Issue by garn222** [cpanel/elevate#203]
I am having some warnings, I have tried disabling "ea-apache24-mod-passenger" in EasyApache 4 but without any luck, when I mark disable/uninstall and go to Review/Provision it do not seem to register it.
Due to my limited technical knowledge I am not sure how to disable the unsupported Yum package "panopta.repo" and what it does exactly, as the setup suggested reporting it I thought I would report it while trying to figure out what it is exactly and how to remove it..

elevate-blockers (var/cpanel):
`{
   "blockers" : [
      {
         "id" : 14,
         "msg" : "One or more enabled YUM repo are currently unsupported.\nYou should disable these repositories and remove packages installed from them\nbefore continuing the update.\n\nConsider reporting this limitation to https://github.com/cpanel/elevate/issues\n",
         "repos" : [
            "panopta.repo"
         ]
      },
      {
         "id" : 104,
         "msg" : "One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8.\nPlease remove these packages before continuing the update.\n- ea-apache24-mod-passenger\n"
      }
   ]
}
`

**Comment by toddr** [comment]
We recommend you open a ticket with cPanel support for further assistance. Thanks!
