### ISSUE TITLE
Supported Way to Alter the WHM Display Banner regarding Elevate

### ISSUE THREAD

**Issue by zackpreuss** [cpanel/elevate#204]
Hello

We would like to have a method to alter the messaging within the banner which appears within WHM. Currently the banner includes a button which will then take a user to a pathway for which they can attempt to update their server to a more current operating system

We would like for cPanel to create a method to either allow us to easily alter the messaging within the banner, or to remove the information regarding the elevate process on the server as to prevent our customers from attempting this process. 

I've attached screenshots which detail what the current messaging is and what we would like to be able to alter the messaging too. 

![elevate current](https://user-images.githubusercontent.com/127252501/223549214-13fa6e14-553d-4c80-8240-aff282950819.png)

![elevate desired](https://user-images.githubusercontent.com/127252501/223549262-10078ad1-9267-4dd9-8f60-ac9423438e92.png)

**Comment by toddr** [comment]
This project deals with the script itself, not cPanel interfaces. We have mitigated this partially via #201. This is as far as we can address the issue you're raising here.
