### ISSUE TITLE
GitLab Community Edition repo not supported

### ISSUE THREAD

**Issue by odingalt** [cpanel/elevate#208]
root /home/user #/scripts/elevate-cpanel --check --upgrade-to=almalinux
* 2023-03-10 08:47:23 [INFO] Successfully verified signature for cpanel (key types: release).
* 2023-03-10 08:47:40 [WARN] Unsupported YUM repo enabled 'packages-microsoft-com-prod' without packages installed from /etc/yum.repos.d/msprod.repo
* 2023-03-10 08:47:40 [WARN] Unsupported YUM repo enabled 'gitlab_gitlab-ce' without packages installed from /etc/yum.repos.d/gitlab_gitlab-ce.repo
* 2023-03-10 08:47:40 [WARN] Unsupported YUM repo enabled 'couchdb' without packages installed from /etc/yum.repos.d/couchdb.repo
* 2023-03-10 08:47:40 [WARN] *** Elevation Blocker detected: ***

**Comment by toddr** [comment]
@odingalt If you are you able to remove these packages and re-install them after upgrade, you will be able to proceed with elevate. Be sure that any configuration data you have associated with those packages is backed up first in the event that package removal leads to removal of the configuration files. 

You can also open a ticket with cPanel support for further assistance. Thanks!

**Comment by odingalt** [comment]
> @odingalt If you are you able to remove these packages and re-install them after upgrade, you will be able to proceed with elevate. Be sure that any configuration data you have associated with those packages is backed up first in the event that package removal leads to removal of the configuration files.
> 
> You can also open a ticket with cPanel support for further assistance. Thanks!

Thanks or your efforts folks, but this elevation seems a bit dubious, I think when the time comes I'll just do a traditional migration to a new server.  Safer, allows for nearly zero downtime.  (Production/test)
