### ISSUE TITLE
Display NOC Recommendations Warning during --check phase & in Security Advisor

### ISSUE THREAD

**Issue by jasonmpotter** [cpanel/elevate#210]
I'm glad we finally got the `/var/cpanel/elevate-noc-recommendations` file implemented in the released version. Thank you very much for pushing that through.  We are already working to apply our recommendations file to the appropriate servers on our network. 

However, our testing has indicated the message is only displayed when running the `--start` phase of an upgrade. 
This makes sense for the `Accept (Y/N)` functionality needing to be confirmed before processing. However, We would like our recommendation message to be displayed during the `--check` phase as well as the `--start` phase,  since that is when the user is actively troubleshooting potential blockers and is less apt to ignore the message. 

We hope this will also allow for the message to be displayed as part of the Security Advisor elevate `--check` as well.  This could be achieved by wrapping the message in `<pre></pre>` tags to preserve formatting when displayed on the Security Advisor page.  The hope here is to reduce the amount of users from attempting the upgrade portion sooner. Elevate Security Advisor messages are one of the ways users find out about the project so earlier display of our recommendations message is preferred to reduce overall confusion from customers. 

Related to #198

**Comment by jasonmpotter** [comment]
Thanks Sloane,

I am familiar with the `elevate-blockers` and
`elevate-blockers.security-advisor` JSON files and experimentation with
immutable state to force the message to show up in the Security Advisor
page as an informational warning worked as expected.Accomplishing this
behavior without such a heavy handed approach as immutable state files
would definitely be the ideal solution.

So it makes sense to add an exists check that dumps the contents of the
`elevate-noc-recommendations` file into these JSON files proper during the
`--check` subroutines makes the most sense to me logistically and would
simultaneously resolve both aspects of this Ask.

The only caveat that I encountered with adding the contents of
`elevate-noc-recommendations` into the `elevate-blockers.security-advisor`
JSON files was that html tags were necessary to correct display issues with
the raw message. So we would need to at-minimum reconcile line endings with
`</br>` to properly display the notice on the security advisor page.
`<pre></pre>` tags would also probably work to satisfy formatting problems
as well.

This does beg the question if it would be preferential to use a separate
`elevate-noc-recommendations.security-advisor` file specifically for
passing an HTML formatted message to the Security Advisor page instead of
attempting to reconcile formatting issues. This would allow for more
elegant branded messages to appear in WHM

Thanks again for your time, effort, and consideration of my requests.

**Comment by jasonmpotter** [comment]
@toddr There were two parts to this ask

1. **Primary Ask:** Display contents of `elevate-noc-recommendations` during `--check` routines
2. **Additional:** Display contents of `elevate-noc-recommendations` in cPanel Security Advisor Page. 

- [ ]  Ask 1 is the main concern here. We feel it makes sense to display the contents of the file during `--check`  informationally since this is when an admin would be actively troubleshooting any blockers. They should be made aware of the recommendations prior to having to officially accepting them during the `--start` phase. 

- [x] Ask 2 is satisfied by the described pending change to cPanel and is a great solution for which I am grateful.

We believe Ask 1 is reasonable and very low-lift request. If preferred, I could probably put together a pull request that satisfiers this ask, but since its such a low-lift ask, figured you guys would know the best place to put it into the project where as I would splice it in willy-nilly. 

Ask 2 was added as a related Ask and would have been satisfied by Ask 1 so they were included together. 

Thank you for your time and consideration and I hope we can also satisfy Ask 1 too.

**Comment by toddr** [comment]
We already block on ask 1, so this has been met.
