### ISSUE TITLE
Centos 7 to Alma 8 upgrade in a Linode - Stage 3 failure

### ISSUE THREAD

**Issue by badtux** [cpanel/elevate#212]
i attempted the script in Centos 7 installed Linode virtual server. 

now the script is failing with following bit. my logs are also empty (or may be i do something wrong).

it looks like some incompatibility with the Linode boot system. any ideas or tips to fix or reverse is much appreciated.

i tried to start the WHM manually after failing but getting the following error. 

```
rtt min/avg/max/mdev = 0.415/0.502/0.590/0.090 ms
root@ln1-daltx [~]# /usr/local/cpanel/scripts/restartsrv_*
warn [restartsrv_httpd] The system is unable to find systemd configuration for the 'httpd' service...
Cpanel::Exception::Service::BinaryNotFound
Service Status
        undefined status from Cpanel::ServiceManager::Services::Httpd

Service Error
        (XID gnc22q) The system could not find the “/usr/local/apache/bin/apachectl” binary for the “httpd” service because of an error: No such file or directory

httpd has failed. Contact your system administrator if the service does not automagically recover.
```

below is the log i can extract after the stage 3 failure.

thanks.

~viraj 

```
[linodexxxx@xxxx-xxx lish]# 
Job 403548661 - Linode Snapshot completed.
[linodexxxx@xxxx-xxx lish]# 
[linodexxxx@xxxx-xxx lish] 
* 2023-03-20 15:50:51 (4165) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
* 2023-03-20 15:50:51 (4165) [INFO]     actor_instance.run(*args, **kwargs)
* 2023-03-20 15:50:51 (4165) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
* 2023-03-20 15:50:51 (4165) [INFO]     self.process(*args)
* 2023-03-20 15:50:51 (4165) [INFO]   File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/systemfacts/actor.py", line 65, in process
* 2023-03-20 15:50:51 (4165) [INFO]     bios_grubcfg_details = systemfacts.get_bios_grubcfg_details()
* 2023-03-20 15:50:51 (4165) [INFO]   File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/systemfacts/libraries/systemfacts.py", line 326, in get_bios_grubcfg_details
* 2023-03-20 15:50:51 (4165) [INFO]     with open('/boot/grub2/grub.cfg') as fo:
* 2023-03-20 15:50:51 (4165) [INFO] IOError: [Errno 2] No such file or directory: '/boot/grub2/grub.cfg'
* 2023-03-20 15:50:51 (4165) [INFO]
* 2023-03-20 15:50:51 (4165) [INFO]
* 2023-03-20 15:50:51 (4165) [INFO] =============================================================================================
* 2023-03-20 15:50:51 (4165) [INFO] Actor system_facts unexpectedly terminated with exit code: 1 - Please check the above details
* 2023-03-20 15:50:51 (4165) [INFO] =============================================================================================
* 2023-03-20 15:50:51 (4165) [INFO] 2023-03-20 15:50:51.828 ERROR    PID: 25161 leapp: Actor system_facts unexpectedly terminated with exit code: 1
* 2023-03-20 15:50:51 (4165) [INFO] 2023-03-20 15:50:51.923 ERROR    PID: 25161 leapp: Upgrade workflow failed, check log for details
* 2023-03-20 15:50:51 (4165) [INFO]
* 2023-03-20 15:50:51 (4165) [INFO] Debug output written to /var/log/leapp/leapp-upgrade.log
* 2023-03-20 15:50:51 (4165) [INFO]
* 2023-03-20 15:50:51 (4165) [INFO] ============================================================
* 2023-03-20 15:50:51 (4165) [INFO]                            REPORT
* 2023-03-20 15:50:51 (4165) [INFO] ============================================================
* 2023-03-20 15:50:51 (4165) [INFO]
* 2023-03-20 15:50:51 (4165) [INFO] A report has been generated at /var/log/leapp/leapp-report.json
* 2023-03-20 15:50:51 (4165) [INFO] A report has been generated at /var/log/leapp/leapp-report.txt
* 2023-03-20 15:50:51 (4165) [INFO]
* 2023-03-20 15:50:51 (4165) [INFO] ============================================================
* 2023-03-20 15:50:51 (4165) [INFO]                        END OF REPORT
* 2023-03-20 15:50:51 (4165) [INFO] ============================================================
* 2023-03-20 15:50:51 (4165) [INFO]
* 2023-03-20 15:50:51 (4165) [INFO] Answerfile has been generated at /var/log/leapp/answerfile
* 2023-03-20 15:50:51 (4182) [INFO]
* 2023-03-20 15:50:52 (703) [INFO] Sending notification: Fail to update to AlmaLinux 8
* 2023-03-20 15:50:52 (708) [ERROR] The elevation process failed during stage 3.
* 2023-03-20 15:50:52 (708) [ERROR]
* 2023-03-20 15:50:52 (708) [ERROR] You can continue the process after fixing the errors by running:
* 2023-03-20 15:50:52 (708) [ERROR]
* 2023-03-20 15:50:52 (708) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel --continue
* 2023-03-20 15:50:52 (708) [ERROR]
* 2023-03-20 15:50:52 (708) [ERROR] You can check the error log by running:
* 2023-03-20 15:50:52 (708) [ERROR]
```

**Comment by danFbach** [comment]
when you say "my logs are empty" do you mean that `/var/log/leapp/leapp-upgrade.log` and `/var/log/leapp/leapp-report.txt` are empty?

**Comment by badtux** [comment]
yes. they were empty files. only the --check and --status gave some update

**Comment by badtux** [comment]
> when you say "my logs are empty" do you mean that `/var/log/leapp/leapp-upgrade.log` and `/var/log/leapp/leapp-report.txt` are empty?

is there a way to undo the Elevate script ?

**Comment by danFbach** [comment]
hi Badtux,

The fact that the logs are empty is very odd and i can't explain it. **Just to double check**, if you run a command such as `less /var/log/leapp/leapp-upgrade.log` absolutely nothing appears? If there really is nothing, someone with more extensive knowledge of leapp will need to give you an explanation.

Elevate/leapp are not reversible - hence all of the warnings to take backups/snapshots prior to running the utility. 
I am not a maintainer of this repo, i have only used it on various servers and run into various problems along the way...That said, I believe your options are now...
1. Find and trace other logs and troubleshoot where your elevation is stuck, perhaps `/var/log/leapp/archive/` has some other logs.
2. Restore from a backup or snapshot, if you have one.
3. clean install

**Comment by sloanebernstein** [comment]
Hello,

We have had problems with GRUB on Linode systems in the past. Part of this comes from the fact that their default method of booting most systems is to boot into an instance of GRUB they manage but to let it read the GRUB configuration stored on the instance. However, their instance is based on a Debian/Ubuntu build, rather than a RHEL build, so the paths GRUB checks are different from what CentOS 7 and AlmaLinux 8 expect.

That said, it is strange that `/boot/grub2/grub.cfg` went missing. If you can, please provide us with the current state of `/boot` and GRUB's subdirectories within it using `ls -l /boot{,/grub*}`. Additionally, please provide the contents of the `/var/cpanel/elevate` file.

**Comment by badtux** [comment]
i managed to set the upstream kernel via grub2 using linode control panel.

the elevate script is now in progress. will give you an update

**Comment by badtux** [comment]
hi,
i am getting following low and mid issues. do i have to fix all of them
before i continue? what are the options and if available how do i instruct
elevate to continue?


Summary:

Key: 539ccff19a53e473e2c3a660230c9062bf871893

----------------------------------------

Risk Factor: medium

Title: memcached has enabled UDP port

Summary: memcached in RHEL7 has UDP port enabled by default, but it is
disabled by default in RHEL8

Key: 0256d6f8f3b5c2add6ab2b315166c69442bfd641

----------------------------------------

Risk Factor: medium

Title: Module pam_pkcs11 will be removed from PAM configuration

Summary: Module pam_pkcs11 was surpassed by SSSD and therefore it was
removed from RHEL-8. Keeping it in PAM configuration may lock out the
system thus it will be automatically removed from PAM configuration before
upgrading to RHEL-8. Please switch to SSSD to recover the functionality of
pam_pkcs11.

Remediation: [hint] Configure SSSD to replace pam_pkcs11

Key: bf47e7305d6805e8bbeaa7593cf01e38030c23f3

----------------------------------------

Risk Factor: medium

Title: chrony using default configuration

Summary: default chrony configuration in RHEL8 uses leapsectz directive,
which cannot be used with leap smearing NTP servers, and uses a single pool
directive instead of four server directives

Key: c4222ebd18730a76f6bc7b3b66df898b106e6554

----------------------------------------

Risk Factor: low

Title: Some enabled RPM repositories are unknown to Leapp

Summary: The following repositories with Red Hat-signed packages are
unknown to Leapp:

- cpanel-plugins

- cpanel-addons-production-feed

And the following packages installed from those repositories may not be
upgraded:

- cpanel-monitoring-agent

- cpanel-banners-plugin

- cpanel-dovecot-solr-server

- cpanel-dovecot-solr-docs

- cpanel-monitoring-whm-plugin

- cpanel-analytics

- cpanel-monitoring-cpanel-plugin

- cpanel-dovecot-solr

- cpanel-wp-cli

- cpanel-wordpress-instance-manager-plugin

- cpanel-dovecot-solr-contrib

- cpanel-letsencrypt-v2

- cpanel-dovecot-solr-contrib-extraction

Remediation: [hint] You can file a request to add this repository to the
scope of in-place upgrades by filing a support ticket

Key: 8e89e20c645cea600b240156071d81c64daab7ad

----------------------------------------

Risk Factor: low

Title: Grep has incompatible changes in the next major version

Summary: If a file contains data improperly encoded for the current locale,
and this is discovered before any of the file's contents are output, grep
now treats the file as binary.

The 'grep -P' no longer reports an error and exits when given invalid UTF-8
data. Instead, it considers the data to be non-matching.

In locales with multibyte character encodings other than UTF-8, grep -P now
reports an error and exits instead of misbehaving.

When searching binary data, grep now may treat non-text bytes as line
terminators. This can boost performance significantly.

The 'grep -z' no longer automatically treats the byte '\200' as binary data.

Context no longer excludes selected lines omitted because of -m. For
example, 'grep "^" -m1 -A1' now outputs the first two input lines, not just
the first line.


Remediation: [hint] Please update your scripts to be compatible with the
changes.

Key: 94665a499e2eeee35eca3e7093a7abe183384b16

----------------------------------------

Risk Factor: low

Title: The subscription-manager release is going to be kept as it is during
the upgrade

Summary: The upgrade is executed with the --no-rhsm option (or with the
LEAPP_NO_RHSM environment variable). In this case, the subscription-manager
will not be configured during the upgrade. If the system is subscribed and
release is set already, you could encounter issues to get RHEL content
using DNF/YUM after the upgrade.

Remediation: [hint] Set the new release (or unset it) after the upgrade
using subscription-manager: subscription-manager release --set 8.6

Key: 01986584e27e85ea18929586faf614eee011a121

----------------------------------------

Risk Factor: info

Title: Authselect will be used to configure PAM and nsswitch.conf.

Summary: There is a new tool called authselect in RHEL8 that replaced
authconfig. The upgrade process suggested an authselect profile that is
similar to your current configuration and your system will be switched to
this profile. Authselect call is: authselect select sssd with-fingerprint
--force. The process will also enable "oddjobd" systemd service on startup

Key: 319689b95eb55badec00c29d53ee79534433cd7c

----------------------------------------

Risk Factor: info

Title: SElinux disabled

Summary: SElinux disabled, continuing...

Key: 4f25fea9b15b9d1d07d52cc1de02073f295dac3d

----------------------------------------

~viraj

**Comment by toddr** [comment]
The next version will block upgrades if it determines your running kernel does not match what the default is in grub. This was fixed by #247

**Comment by chrisduk112** [comment]
We had this same issue today 2nd August 2023, we use OnAPP.


`root@serv [~]# /scripts/elevate-cpanel --continue
# -------------------------> [INFO] Restarting install process (stage=3)
# -------------------------> [ERROR] # Upgrade process failed at stage=3 ; Running: tail -f /var/log/elevate-cpanel.log
* 2023-08-02 18:37:32 [INFO] Running: /usr/bin/systemctl restart elevate-cpanel.service
* 2023-08-02 18:37:32 [INFO]
* 2023-08-02 18:35:10 (4102) [INFO] A report has been generated at /var/log/leapp/leapp-report.json
* 2023-08-02 18:35:10 (4102) [INFO] A report has been generated at /var/log/leapp/leapp-report.txt
* 2023-08-02 18:35:10 (4102) [INFO]
* 2023-08-02 18:35:10 (4102) [INFO] ============================================================
* 2023-08-02 18:35:10 (4102) [INFO]                        END OF REPORT
* 2023-08-02 18:35:10 (4102) [INFO] ============================================================
* 2023-08-02 18:35:10 (4102) [INFO]
* 2023-08-02 18:35:10 (4102) [INFO] Answerfile has been generated at /var/log/leapp/answerfile
* 2023-08-02 18:35:10 (4119) [INFO]
* 2023-08-02 18:35:10 (4026) [INFO] Sending notification: Failed to update to AlmaLinux 8
* 2023-08-02 18:35:10 (4031) [ERROR] The elevation process failed during stage 3.
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR] You can continue the process after fixing the errors by running:
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel --continue
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR] You can check the error log by running:
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR] Last Error:
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR] The 'leapp upgrade' process failed.
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR] Please investigate, resolve then re-run the following command to continue the update:
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR]     /scripts/elevate-cpanel --continue
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR]
* 2023-08-02 18:35:10 (4031) [ERROR] You can read the full leapp report at: /var/log/leapp/leapp-report.txt
* 2023-08-02 18:35:10 (5135) [FATAL] The 'leapp upgrade' process failed.

Please investigate, resolve then re-run the following command to continue the update:

    /scripts/elevate-cpanel --continue
`
We did a full backup seconds before running the elevate and now running a bare metal recovery.

**Comment by afletch** [comment]
@chrisduk112 Did you get anywhere with resolving this?


> We had this same issue today 2nd August 2023, we use OnAPP.
> 
> `root@serv [~]# /scripts/elevate-cpanel --continue
> # -------------------------> [INFO] Restarting install process (stage=3)
> # -------------------------> [ERROR] # Upgrade process failed at stage=3 ; Running: tail -f /var/log/elevate-cpanel.log
> 
>     * 2023-08-02 18:37:32 [INFO] Running: /usr/bin/systemctl restart elevate-cpanel.service
> 
>     * 2023-08-02 18:37:32 [INFO]
> 
>     * 2023-08-02 18:35:10 (4102) [INFO] A report has been generated at /var/log/leapp/leapp-report.json
> 
>     * 2023-08-02 18:35:10 (4102) [INFO] A report has been generated at /var/log/leapp/leapp-report.txt
> 
>     * 2023-08-02 18:35:10 (4102) [INFO]
> 
>     * 2023-08-02 18:35:10 (4102) [INFO] ============================================================
> 
>     * 2023-08-02 18:35:10 (4102) [INFO]                        END OF REPORT
> 
>     * 2023-08-02 18:35:10 (4102) [INFO] ============================================================
> 
>     * 2023-08-02 18:35:10 (4102) [INFO]
> 
>     * 2023-08-02 18:35:10 (4102) [INFO] Answerfile has been generated at /var/log/leapp/answerfile
> 
>     * 2023-08-02 18:35:10 (4119) [INFO]
> 
>     * 2023-08-02 18:35:10 (4026) [INFO] Sending notification: Failed to update to AlmaLinux 8
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR] The elevation process failed during stage 3.
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR] You can continue the process after fixing the errors by running:
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel --continue
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR] You can check the error log by running:
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR] Last Error:
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR] The 'leapp upgrade' process failed.
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR] Please investigate, resolve then re-run the following command to continue the update:
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]     /scripts/elevate-cpanel --continue
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR]
> 
>     * 2023-08-02 18:35:10 (4031) [ERROR] You can read the full leapp report at: /var/log/leapp/leapp-report.txt
> 
>     * 2023-08-02 18:35:10 (5135) [FATAL] The 'leapp upgrade' process failed.
> 
> 
> Please investigate, resolve then re-run the following command to continue the update:
> 
> ```
> /scripts/elevate-cpanel --continue
> ```
> 
> You can read the full leapp report at: /var/log/leapp/leapp-report.txt
> 
>     * 2023-08-02 18:37:32 (4088) [INFO] Running: /usr/bin/systemctl restart elevate-cpanel.service
> 
>     * 2023-08-02 18:37:32 (4089) [INFO]
> 
>     * 2023-08-02 18:37:32 [INFO]
> 
>     * 2023-08-02 18:37:32 (4119) [INFO]
> 
>     * 2023-08-02 18:37:33 (5692) [INFO] ******************************************************************************************
> 
>     * 2023-08-02 18:37:33 (5693) [INFO] *
> 
>     * 2023-08-02 18:37:33 (5694) [INFO] * Starting stage 3 of 5
> 
>     * 2023-08-02 18:37:33 (5695) [INFO] *
> 
>     * 2023-08-02 18:37:33 (5696) [INFO] ******************************************************************************************
> 
>     * 2023-08-02 18:37:33 (5666) [INFO] Stage 3: skipping prep_for_leapp (already run)
> 
>     * 2023-08-02 18:37:33 (5816) [INFO] Running leapp upgrade
> 
>     * 2023-08-02 18:37:33 (4088) [INFO] Running: /usr/bin/leapp upgrade
> 
>     * 2023-08-02 18:37:33 (4089) [INFO]
> 
>     * 2023-08-02 18:37:41 (4102) [INFO] ==> Processing phase `configuration_phase`
> 
>     * 2023-08-02 18:37:41 (4102) [INFO] ====> * ipu_workflow_config
> 
>     * 2023-08-02 18:37:41 (4102) [INFO]         IPU workflow config actor
> 
>     * 2023-08-02 18:37:41 (4102) [INFO] ==> Processing phase `FactsCollection`
> 
>     * 2023-08-02 18:37:41 (4102) [INFO] ====> * system_facts
> 
>     * 2023-08-02 18:37:41 (4102) [INFO]         Provides data about many facts from system.
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] Process Process-217:
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] Traceback (most recent call last):
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]     self.run()
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]   File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]     self._target(*self._args, **self._kwargs)
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]     actor_instance.run(*args, **kwargs)
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/actors/**init**.py", line 290, in run
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]     self.process(*args)
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]   File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/systemfacts/actor.py", line 65, in process
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]     bios_grubcfg_details = systemfacts.get_bios_grubcfg_details()
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]   File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/systemfacts/libraries/systemfacts.py", line 326, in get_bios_grubcfg_details
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]     with open('/boot/grub2/grub.cfg') as fo:
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] IOError: [Errno 2] No such file or directory: '/boot/grub2/grub.cfg'
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] =============================================================================================
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] Actor system_facts unexpectedly terminated with exit code: 1 - Please check the above details
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] =============================================================================================
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] 2023-08-02 18:37:44.320 ERROR    PID: 3219 leapp: Actor system_facts unexpectedly terminated with exit code: 1
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] 2023-08-02 18:37:44.353 ERROR    PID: 3219 leapp: Upgrade workflow failed, check log for details
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] Debug output written to /var/log/leapp/leapp-upgrade.log
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] ============================================================
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]                            REPORT
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] ============================================================
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] A report has been generated at /var/log/leapp/leapp-report.json
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] A report has been generated at /var/log/leapp/leapp-report.txt
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] ============================================================
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]                        END OF REPORT
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] ============================================================
> 
>     * 2023-08-02 18:37:44 (4102) [INFO]
> 
>     * 2023-08-02 18:37:44 (4102) [INFO] Answerfile has been generated at /var/log/leapp/answerfile
> 
>     * 2023-08-02 18:37:44 (4119) [INFO]
> 
>     * 2023-08-02 18:37:44 (4026) [INFO] Sending notification: Failed to update to AlmaLinux 8
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR] The elevation process failed during stage 3.
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR] You can continue the process after fixing the errors by running:
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel --continue
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR] You can check the error log by running:
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR] Last Error:
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR] The 'leapp upgrade' process failed.
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR] Please investigate, resolve then re-run the following command to continue the update:
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]     /scripts/elevate-cpanel --continue
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR]
> 
>     * 2023-08-02 18:37:44 (4031) [ERROR] You can read the full leapp report at: /var/log/leapp/leapp-report.txt
> 
>     * 2023-08-02 18:37:44 (5135) [FATAL] The 'leapp upgrade' process failed.
> 
> 
> ` We did a full backup seconds before running the elevate and now running a bare metal recovery.
