### ISSUE TITLE
One or more enabled YUM repo are currently unsupported.

### ISSUE THREAD

**Issue by humrod** [cpanel/elevate#214]
I have no idea what to do to resolve a notice I received about an obstacle to update to Almalinux, an unsolicited event.  The notice says:

Elevate | The system detected the following issues which   would prevent cPanel ELevate from upgrading the system to AlmaLinux 8:        One        or more enabled YUM repo are currently unsupported. You should disable        these repositories and remove packages installed from them before        continuing the update. Consider reporting this limitation to https://github.com/cpanel/elevate/issues            Issue        with sshd configuration

Also:

Issue with sshd configuration

Which issue?  What to do?

**Comment by toddr** [comment]
Hi, We don't have enough information to advise you here. What repositories are missing?

**Comment by toddr** [comment]
Hi, I recommend you open a ticket with cPanel support for further assistance. Thanks!
