### ISSUE TITLE
Repo support - Godaddy monitoring tool panopta blocker

### ISSUE THREAD

**Issue by DavidDah** [cpanel/elevate#220]
I have server in godaddy datacenter (EU) and several blockers were detected one of them is goddady monitoring tool and second blocker are centos-sclo-rh packages.

```
# /scripts/elevate-cpanel --check --upgrade-to=almalinux
* 2023-03-27 23:27:52 [INFO] Successfully verified signature for cpanel (key types: release).
* 2023-03-27 23:27:53 [ERROR] 1 package(s) installed from unsupported YUM repo 'panopta.repo' from /etc/yum.repos.d/panopta.repo
* 2023-03-27 23:27:53 [ERROR] 26 package(s) installed from unsupported YUM repo 'centos-sclo-rh' from /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
* 2023-03-27 23:27:53 [WARN] Unsupported YUM repo enabled 'centos-sclo-sclo' without packages installed from /etc/yum.repos.d/CentOS-SCLo-scl.repo
* 2023-03-27 23:27:53 [WARN] *** Elevation Blocker detected: ***
  One or more enabled YUM repo are currently unsupported.
  You should disable these repositories and remove packages installed from them
  before continuing the update.
```
```
# yum list installed | grep sclo
devtoolset-7.x86_64                           7.1-4.el7              @centos-sclo-rh
devtoolset-7-binutils.x86_64                  2.28-11.el7            @centos-sclo-rh
devtoolset-7-dwz.x86_64                       0.12-1.1.el7           @centos-sclo-rh
devtoolset-7-dyninst.x86_64                   9.3.2-3.el7            @centos-sclo-rh
devtoolset-7-elfutils.x86_64                  0.170-5.el7            @centos-sclo-rh
devtoolset-7-elfutils-libelf.x86_64           0.170-5.el7            @centos-sclo-rh
devtoolset-7-elfutils-libs.x86_64             0.170-5.el7            @centos-sclo-rh
devtoolset-7-gcc.x86_64                       7.3.1-5.16.el7         @centos-sclo-rh
devtoolset-7-gcc-c++.x86_64                   7.3.1-5.16.el7         @centos-sclo-rh
devtoolset-7-gcc-gfortran.x86_64              7.3.1-5.16.el7         @centos-sclo-rh
devtoolset-7-gdb.x86_64                       8.0.1-36.el7           @centos-sclo-rh
devtoolset-7-libquadmath-devel.x86_64         7.3.1-5.16.el7         @centos-sclo-rh
devtoolset-7-libstdc++-devel.x86_64           7.3.1-5.16.el7         @centos-sclo-rh
devtoolset-7-ltrace.x86_64                    0.7.91-2.el7           @centos-sclo-rh
devtoolset-7-make.x86_64                      1:4.2.1-3.el7          @centos-sclo-rh
devtoolset-7-memstomp.x86_64                  0.1.5-5.1.el7          @centos-sclo-rh
devtoolset-7-oprofile.x86_64                  1.2.0-2.el7.1          @centos-sclo-rh
devtoolset-7-perftools.x86_64                 7.1-4.el7              @centos-sclo-rh
devtoolset-7-runtime.x86_64                   7.1-4.el7              @centos-sclo-rh
devtoolset-7-strace.x86_64                    4.17-7.el7             @centos-sclo-rh
devtoolset-7-systemtap.x86_64                 3.1-4s.el7             @centos-sclo-rh
devtoolset-7-systemtap-client.x86_64          3.1-4s.el7             @centos-sclo-rh
devtoolset-7-systemtap-devel.x86_64           3.1-4s.el7             @centos-sclo-rh
devtoolset-7-systemtap-runtime.x86_64         3.1-4s.el7             @centos-sclo-rh
devtoolset-7-toolchain.x86_64                 7.1-4.el7              @centos-sclo-rh
devtoolset-7-valgrind.x86_64                  1:3.13.0-11.el7        @centos-sclo-rh
```

**Comment by toddr** [comment]
Thanks for letting us know. Our standard answer is that if you're ok to remove these packages, you'd be ok to upgrade. We are evaluating repos to add support for them but I cannot tell you when we will get to these.

**Comment by RickieF63** [comment]
Hi all, long time reader first time poster.
I hit this too, same circumstances, there is a workaround I've worked on, assuming you've cleared all the other blockers and this is the only one left, see below, it's a bit rough and ready but should be complete and easy to follow, hopefully.

Planned Process on Elevate Day
-----------------------------------
Open Terminal and run commands;

python /usr/bin/panopta-agent/maintenance.py --start --duration=600

yum renove panopta-agent.x86_64

Backup all accounts and download

Stop VPS and run a manual backup (you can do this before removing the agent if you prefer)
------------------------------------------------------------------------------------------------------
Start server and go straight to run;

/scripts/elevate-cpanel --check --upgrade-to=almalinux
--------------------------------------------------------------
If all is clear (don't worry if the repo still shows the script will disable it) run;

/scripts/elevate-cpanel --start --upgrade-to=almalinux

Cross everything you can and LEAVE IT ALONE :) that's the hard bit!
---------------------------------------------------------------------------
Hopefully it all goes well and reinstall the monitoring agent

yum install panopta-agent.x86_64

Check on your hosting co. control panel that it's checking in.

The 600 duration in the python command is 10 hours just to be safe, if need be after Elevation completes and the agent is reinstalled you can run;

python /usr/bin/panopta-agent/maintenance.py --end

To end maintenance.

GOOD LUCK.

**Comment by sloanebernstein** [comment]
> Backup all accounts and download

Although having account backups is certainly better than nothing, we would also recommend taking a full system snapshot if feasible, especially if availability is an important concern.

**Comment by RickieF63** [comment]
That's in there, and like you I'd strongly recommend a full snapshot before this, account backups are a bit of an 'oh well' option but should still be done in case of complete rebuild being required with the snapshot not being viable.

"Stop VPS and run a manual backup" that's the full one, if you don't have that included then stump up the months fee for it as a one off it's not expensive and your time and lost work is.

**Comment by sloanebernstein** [comment]
Ah, leave it to me to read the details but not the headline. :)

**Comment by RickieF63** [comment]
I do it too :D it happens all the time.

**Comment by DavidDah** [comment]
Iv managed to elevate after some troubles, however I can't install panopta back to the server as suggested.
Here is the error outpute

`[root@21 ~]# yum install panopta-agent.x86_64

Last metadata expiration check: 0:07:56 ago on Sun 06 Aug 2023 03:15:41 AM CEST.
Error: 
 Problem: conflicting requests
  - nothing provides python >= 2.4 needed by panopta-agent-2019.89.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2019.91.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2019.92.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.01.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.11.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.12.6-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.14.03-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.22.1-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.22.12-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.22.13-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.22.14-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.22.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.22.4-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.22.5-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.22.6-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.22.7-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.27.1-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.31.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.37.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.37.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.37.4-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.38.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.39.1-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.39.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.49.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.49.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.50.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.50.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.58.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.58.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.63.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.63.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.69.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.69.4-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.70.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.74.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.78.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.78.4-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.86.1-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.86.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.86.3-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.91.4-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2020.91.5-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2021.15.1-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2021.32.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2021.61.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2021.78.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2022.12.1-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2022.20.1-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2022.20.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2022.20.4-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2022.20.5-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2022.37.1-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2022.46.1-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2022.46.2-0.1.x86_64
  - nothing provides python >= 2.4 needed by panopta-agent-2022.47.1-0.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)`

**Comment by toddr** [comment]
Now you're upgraded to 8, we recommend you open a ticket with support for further assistance.

**Comment by toddr** [comment]
though off the top of my head... did you upgrade the contents of `panopta.repo` before you tried to re-install?

**Comment by DavidDah** [comment]
No, I didn't upgrade it.

**Comment by toddr** [comment]
does the URL in the file have a 7 in it you need to change to an 8?

**Comment by OopyDoopy** [comment]
> Iv managed to elevate after some troubles, however I can't install panopta back to the server as suggested. Here is the error outpute
> 
> `[root@21 ~]# yum install panopta-agent.x86_64
> 
> Last metadata expiration check: 0:07:56 ago on Sun 06 Aug 2023 03:15:41 AM CEST. Error: Problem: conflicting requests
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2019.89.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2019.91.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2019.92.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.01.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.11.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.12.6-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.14.03-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.22.1-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.22.12-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.22.13-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.22.14-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.22.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.22.4-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.22.5-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.22.6-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.22.7-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.27.1-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.31.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.37.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.37.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.37.4-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.38.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.39.1-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.39.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.49.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.49.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.50.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.50.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.58.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.58.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.63.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.63.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.69.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.69.4-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.70.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.74.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.78.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.78.4-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.86.1-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.86.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.86.3-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.91.4-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2020.91.5-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2021.15.1-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2021.32.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2021.61.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2021.78.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2022.12.1-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2022.20.1-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2022.20.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2022.20.4-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2022.20.5-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2022.37.1-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2022.46.1-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2022.46.2-0.1.x86_64
> 
>     * nothing provides python >= 2.4 needed by panopta-agent-2022.47.1-0.1.x86_64
>       (try to add '--skip-broken' to skip uninstallable packages)`

This is a problem I'm running into as well. Did you find a solution?

**Comment by toddr** [comment]
Have you opened a ticket with cpanel support?

**Comment by iDanielBH** [comment]
I called godaddy support and they told me that I had to hire a new server in order to switch to Almalinux.

Too bad of godaddy.

Finally I updated to almalinux, since godaddy did not help me at all, it only told me to hire a new server with almalinux to migrate everything.

Therefore, I upgraded after:
```
python /usr/bin/panopta-agent/maintenance.py --start --duration=600
yum remove panopta-agent.x86_64
```

And at the end, when I executed:
```
yum install panopta-agent.x86_64
```
I obtained:
nothing provides python >= 2.4 needed by panopta-agent-2019.89.2-0.1.x86_64

And it wouldn't let me install panopta in any way via yum or dfn.

I even installed "python2"

```
yum install python2
```

and set it as "python" with a symlink
```
ln -s /usr/bin/python2 /usr/bin/python
```

But nothing.

So it occurred to me to make a backup and download the package manually:
[https://packages.panopta.com/rpm-stable/x86_64/panopta-agent-2022.47.1-0.1.x86_64.rpm](url)

And install it using rpm:
```
rpm -ivh --nodeps panopta-agent-2022.47.1-0.1.x86_64.rpm
```

Once that was done I was able to run it correctly:
```
python /usr/bin/panopta-agent/maintenance.py --end
```

I hope to help someone.

**Comment by lila-godel** [comment]
> So it occurred to me to make a backup and download the package manually: [https://packages.panopta.com/rpm-stable/x86_64/panopta-agent-2022.47.1-0.1.x86_64.rpm](url)
> 
> And install it using rpm:
> 
> ```
> rpm -ivh --nodeps panopta-agent-2022.47.1-0.1.x86_64.rpm
> ```
> 
> Once that was done I was able to run it correctly:
> 
> ```
> python /usr/bin/panopta-agent/maintenance.py --end
> ```
> 
> I hope to help someone.

I am trying to get the panopta-agent back working after upgrading my Godaddy VPS server to Alama 8.

I was able to get it reinstalled after downloading the .rpm file and running the rpm -ivh command above, but I cannot get it to start.

I get the following text:

Using manifest file aggregator for initial handshake: aggregator2.panopta.com:443
Handshaking with panopta servers...Handshake failed: Missing customer key, server, and fortisase data

I am wonder if I need to change the url in /etc/panopta-agent/panopta_agent.cfg to a Godday specific URL.

It currently has the contents:

[agent]
aggregator_url = aggregator2.panopta.com:443
version = 2022.47.1
plugin_blacklist = package_upgrade

Is that what your has?

**Comment by bongnith** [comment]
> I called godaddy support and they told me that I had to hire a new server in order to switch to Almalinux.
> 
> Too bad of godaddy.
> 
> Finally I updated to almalinux, since godaddy did not help me at all, it only told me to hire a new server with almalinux to migrate everything.
> 
> Therefore, I upgraded after:
> 
> ```
> python /usr/bin/panopta-agent/maintenance.py --start --duration=600
> yum remove panopta-agent.x86_64
> ```
> 
> And at the end, when I executed:
> 
> ```
> yum install panopta-agent.x86_64
> ```
> 
> I obtained: nothing provides python >= 2.4 needed by panopta-agent-2019.89.2-0.1.x86_64
> 
> And it wouldn't let me install panopta in any way via yum or dnf.
> 
> I even installed "python2"
> 
> ```
> yum install python2
> ```
> 
> and set it as "python" with a symlink
> 
> ```
> ln -s /usr/bin/python2 /usr/bin/python
> ```
> 
> But nothing.
> 
> So it occurred to me to make a backup and download the package manually: [https://packages.panopta.com/rpm-stable/x86_64/panopta-agent-2022.47.1-0.1.x86_64.rpm](url)
> 
> And install it using rpm:
> 
> ```
> rpm -ivh --nodeps panopta-agent-2022.47.1-0.1.x86_64.rpm
> ```
> 
> Once that was done I was able to run it correctly:
> 
> ```
> python /usr/bin/panopta-agent/maintenance.py --end
> ```
> 
> I hope to help someone.

Hello,

I am writing to inquire about the possibility of cPanel ELevate script (https://cpanel.github.io/elevate/) on my GoDaddy Self-Managed VPS from CentOS 7 to AlmaLinux 8. 

I have submitted support ticket inquiries with both GoDaddy support and cPanel support but have not yielded a definitive answer regarding the compatibility of cPanel ELevate with GoDaddy's Self-Managed VPS environment. GoDaddy suggested a server migration to a new server with AlmaLinux 8 service, which is not ideal due to the aforementioned reasons and super high cost.

My primary question is whether you or anyone here successfully ELevated to AlmaLinux on GoDaddy Self-Managed VPS with CentOS 7.  I am fully prepared to address any potential blockers or unsupported repo issues before the upgrade process.

I would greatly appreciate any insights or guidance you can provide on this matter.  Additionally, if there are specific limitations or considerations related to GoDaddy's environment that I should be aware of, please share those details at your earliest convenience.

Thank you for your time and assistance.

Sincerely,

**Comment by iDanielBH** [comment]
> > I called godaddy support and they told me that I had to hire a new server in order to switch to Almalinux.
> > Too bad of godaddy.
> > Finally I updated to almalinux, since godaddy did not help me at all, it only told me to hire a new server with almalinux to migrate everything.
> > Therefore, I upgraded after:
> > ```
> > python /usr/bin/panopta-agent/maintenance.py --start --duration=600
> > yum remove panopta-agent.x86_64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And at the end, when I executed:
> > ```
> > yum install panopta-agent.x86_64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I obtained: nothing provides python >= 2.4 needed by panopta-agent-2019.89.2-0.1.x86_64
> > And it wouldn't let me install panopta in any way via yum or dnf.
> > I even installed "python2"
> > ```
> > yum install python2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and set it as "python" with a symlink
> > ```
> > ln -s /usr/bin/python2 /usr/bin/python
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But nothing.
> > So it occurred to me to make a backup and download the package manually: [https://packages.panopta.com/rpm-stable/x86_64/panopta-agent-2022.47.1-0.1.x86_64.rpm](url)
> > And install it using rpm:
> > ```
> > rpm -ivh --nodeps panopta-agent-2022.47.1-0.1.x86_64.rpm
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Once that was done I was able to run it correctly:
> > ```
> > python /usr/bin/panopta-agent/maintenance.py --end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope to help someone.
> 
> Hello,
> 
> I am writing to inquire about the possibility of cPanel ELevate script (https://cpanel.github.io/elevate/) on my GoDaddy Self-Managed VPS from CentOS 7 to AlmaLinux 8.
> 
> I have submitted support ticket inquiries with both GoDaddy support and cPanel support but have not yielded a definitive answer regarding the compatibility of cPanel ELevate with GoDaddy's Self-Managed VPS environment. GoDaddy suggested a server migration to a new server with AlmaLinux 8 service, which is not ideal due to the aforementioned reasons and super high cost.
> 
> My primary question is whether you or anyone here successfully ELevated to AlmaLinux on GoDaddy Self-Managed VPS with CentOS 7. I am fully prepared to address any potential blockers or unsupported repo issues before the upgrade process.
> 
> I would greatly appreciate any insights or guidance you can provide on this matter. Additionally, if there are specific limitations or considerations related to GoDaddy's environment that I should be aware of, please share those details at your earliest convenience.
> 
> Thank you for your time and assistance.
> 
> Sincerely,

Hello,

I finally managed to migrate to AlmaLinux without any issues from cPanel Elevate (aside from the mentioned issue with Panopta). The only problem I encountered was that a package tried to download via IPv6 even though IPv6 was not configured on my machine. To solve this, I had to change something in the configuration to force package downloads via IPv4. I don't remember exactly how I did it, but it was simple.

What I highly recommend is to make a full backup of the entire machine from the GoDaddy panel, so you can restore everything if something goes wrong.

**Comment by bongnith** [comment]
Thanks for your reply. After the elevation process on your GoDaddy panel, is your display server IP will likely show AlmaLinux 8 as the operating system?  So you will only follow the instruction scripts from the Elevate page? Like you mentioned, beside Panopta, everything else is functioning properly including Launch WHM, Server Actions, and Settings on the GoDaddy Panel?

**Comment by bongnith** [comment]
> Thanks for your reply. After the elevation process on your GoDaddy panel, is your display server IP will likely show AlmaLinux 8 as the operating system? So you will only follow the instruction scripts from the Elevate page? Like you mentioned, beside Panopta, everything else is functioning properly including Launch WHM, Server Actions, and Settings on the GoDaddy Panel?



> > > I called godaddy support and they told me that I had to hire a new server in order to switch to Almalinux.
> > > Too bad of godaddy.
> > > Finally I updated to almalinux, since godaddy did not help me at all, it only told me to hire a new server with almalinux to migrate everything.
> > > Therefore, I upgraded after:
> > > ```
> > > python /usr/bin/panopta-agent/maintenance.py --start --duration=600
> > > yum remove panopta-agent.x86_64
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And at the end, when I executed:
> > > ```
> > > yum install panopta-agent.x86_64
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I obtained: nothing provides python >= 2.4 needed by panopta-agent-2019.89.2-0.1.x86_64
> > > And it wouldn't let me install panopta in any way via yum or dnf.
> > > I even installed "python2"
> > > ```
> > > yum install python2
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and set it as "python" with a symlink
> > > ```
> > > ln -s /usr/bin/python2 /usr/bin/python
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > But nothing.
> > > So it occurred to me to make a backup and download the package manually: [https://packages.panopta.com/rpm-stable/x86_64/panopta-agent-2022.47.1-0.1.x86_64.rpm](url)
> > > And install it using rpm:
> > > ```
> > > rpm -ivh --nodeps panopta-agent-2022.47.1-0.1.x86_64.rpm
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Once that was done I was able to run it correctly:
> > > ```
> > > python /usr/bin/panopta-agent/maintenance.py --end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I hope to help someone.
> > 
> > 
> > Hello,
> > I am writing to inquire about the possibility of cPanel ELevate script (https://cpanel.github.io/elevate/) on my GoDaddy Self-Managed VPS from CentOS 7 to AlmaLinux 8.
> > I have submitted support ticket inquiries with both GoDaddy support and cPanel support but have not yielded a definitive answer regarding the compatibility of cPanel ELevate with GoDaddy's Self-Managed VPS environment. GoDaddy suggested a server migration to a new server with AlmaLinux 8 service, which is not ideal due to the aforementioned reasons and super high cost.
> > My primary question is whether you or anyone here successfully ELevated to AlmaLinux on GoDaddy Self-Managed VPS with CentOS 7. I am fully prepared to address any potential blockers or unsupported repo issues before the upgrade process.
> > I would greatly appreciate any insights or guidance you can provide on this matter. Additionally, if there are specific limitations or considerations related to GoDaddy's environment that I should be aware of, please share those details at your earliest convenience.
> > Thank you for your time and assistance.
> > Sincerely,
> 
> Hello,
> 
> I finally managed to migrate to AlmaLinux without any issues from cPanel Elevate (aside from the mentioned issue with Panopta). The only problem I encountered was that a package tried to download via IPv6 even though IPv6 was not configured on my machine. To solve this, I had to change something in the configuration to force package downloads via IPv4. I don't remember exactly how I did it, but it was simple.
> 
> What I highly recommend is to make a full backup of the entire machine from the GoDaddy panel, so you can restore everything if something goes wrong.

Thanks for your reply. After the elevation process on your GoDaddy panel, is your display server IP will likely show AlmaLinux 8 as the operating system? So you will only follow the instruction scripts from the Elevate page? Like you mentioned, beside Panopta, everything else is functioning properly including Launch WHM, Server Actions, and Settings on the GoDaddy Panel?

**Comment by mattcaz** [comment]
I have the same issue so I got a new server for 1 month, set it up with Almalinux 9 and migrated my cpanel to the new server using the migration from source tool. Once I test it all, I will init my old server that still has 3 yrs left on it and install Almalinux 9 on it and then do the reverse from the 1 month temp server back to my legacy server.   After the first migration to the test server my online store etc. works fine.  My needs are very simple so it's not resource heavy.  Thanks for all the tips and info in this thread.  Too bad the "Cpanel Elevate to almalinux" script can't do the Godaddy monitoring fix for us.

**Comment by toddr** [comment]
With help from Godaddy, We've been able to add support in v52

**2024-08-22** - version 52
** Fixed case RE-43: No longer block on Panopta or FortiMonitor

**Comment by mattcaz** [comment]
So does this mean I can do an inplace elevate to the new linux on my VPS Centos Server?


Matt Caswell, SMSgt, USAF (Retired)
***@***.***
https://store.dryheatcreations.com

[A group of different items  Description automatically generated with medium confidence]

From: Todd Rinaldo ***@***.***>
Reply-To: cpanel/elevate ***@***.***>
Date: Wednesday, September 18, 2024 at 1:20 PM
To: cpanel/elevate ***@***.***>
Cc: Matt Caswell ***@***.***>, Comment ***@***.***>
Subject: Re: [cpanel/elevate] Repo support - Godaddy monitoring tool panopta blocker (Issue #220)


With help from Godaddy, We've been able to add support in v52

2024-08-22 - version 52
** Fixed case RE-43: No longer block on Panopta or FortiMonitor

**Comment by mattcaz** [comment]
So following your email I ran the elevate to Almalinux 8 on my centos 7 GD VPS and it completed but the services: nydus-ex and nydus-ex-api aren’t running so I was confused that you said with GoDaddys help you got it fixed.

Did I misunderstand what you were saying? IS there a way to get  these two to run so I can have monitoring again?

Thanks for your time,
Matt


Matt Caswell, SMSgt, USAF (Retired)
***@***.***
https://store.dryheatcreations.com

[A group of different items  Description automatically generated with medium confidence]

From: Todd Rinaldo ***@***.***>
Reply-To: cpanel/elevate ***@***.***>
Date: Wednesday, September 18, 2024 at 1:20 PM
To: cpanel/elevate ***@***.***>
Cc: Matt Caswell ***@***.***>, Comment ***@***.***>
Subject: Re: [cpanel/elevate] Repo support - Godaddy monitoring tool panopta blocker (Issue #220)


With help from Godaddy, We've been able to add support in v52

2024-08-22 - version 52
** Fixed case RE-43: No longer block on Panopta or FortiMonitor
