### ISSUE TITLE
26 package(s) installed from unsupported YUM repo 'cl7h'

### ISSUE THREAD

**Issue by bashmail** [cpanel/elevate#229]
/scripts/elevate-cpanel --check --upgrade-to=cloudlinux
* 2023-03-31 23:18:43 [INFO] Successfully verified signature for cpanel (key types: release).
* 2023-03-31 23:18:46 [ERROR] 26 package(s) installed from unsupported YUM repo 'cl7h' from /etc/yum.repos.d/cl7h.repo
* 2023-03-31 23:18:46 [WARN] *** Elevation Blocker detected: ***
  One or more enabled YUM repo are currently unsupported.
  You should disable these repositories and remove packages installed from them
  before continuing the update.

  Consider reporting this limitation to https://github.com/cpanel/elevate/issues

* 2023-03-31 23:19:50 [INFO] Checking if your system is up to date:
* 2023-03-31 23:19:50 [INFO] Running: /usr/bin/yum clean all
* 2023-03-31 23:19:50 [INFO]
* 2023-03-31 23:19:50 [INFO] Loaded plugins: fastestmirror, rhnplugin, universal-hooks
* 2023-03-31 23:19:50 [INFO] Cleaning repos: EA4 cpanel-addons-production-feed cpanel-plugins MariaDB103
* 2023-03-31 23:19:50 [INFO]               : Mysql-connectors-community Mysql-tools-community
* 2023-03-31 23:19:50 [INFO]               : Mysql57-community cl-ea4 cl7h cloudlinux-ea4-rollout-1
* 2023-03-31 23:19:50 [INFO]               : cloudlinux-ea4-rollout-10 cloudlinux-ea4-rollout-2
* 2023-03-31 23:19:50 [INFO]               : cloudlinux-ea4-rollout-3 cloudlinux-ea4-rollout-4
* 2023-03-31 23:19:50 [INFO]               : cloudlinux-ea4-rollout-5 cloudlinux-ea4-rollout-6
* 2023-03-31 23:19:50 [INFO]               : cloudlinux-ea4-rollout-7 cloudlinux-ea4-rollout-8
* 2023-03-31 23:19:50 [INFO]               : cloudlinux-ea4-rollout-9 cloudlinux-imunify360
* 2023-03-31 23:19:50 [INFO]               : cloudlinux-rollout-1 cloudlinux-rollout-10 cloudlinux-rollout-2
* 2023-03-31 23:19:50 [INFO]               : cloudlinux-rollout-3 cloudlinux-rollout-4 cloudlinux-rollout-5
* 2023-03-31 23:19:50 [INFO]               : cloudlinux-rollout-6 cloudlinux-rollout-7 cloudlinux-rollout-8
* 2023-03-31 23:19:50 [INFO]               : cloudlinux-rollout-9 cloudlinux-x86_64-server-7 epel imunify360
* 2023-03-31 23:19:50 [INFO]               : wp-toolkit-cpanel wp-toolkit-thirdparties
* 2023-03-31 23:19:51 [INFO] Cleaning up list of fastest mirrors
* 2023-03-31 23:19:51 [INFO] Other repos take up 243 M of disk space (use --verbose for details)
* 2023-03-31 23:19:51 [INFO]
* 2023-03-31 23:19:51 [INFO] Running: /usr/bin/yum check-update -q
* 2023-03-31 23:19:51 [INFO]
* 2023-03-31 23:20:54 [INFO]
* 2023-03-31 23:20:54 [INFO] Checking /scripts/sysup
* 2023-03-31 23:20:54 [INFO] Running: /scripts/sysup
* 2023-03-31 23:20:54 [INFO]
* 2023-03-31 23:20:55 [INFO] checkyum version 22.3  (excludes: bind-chroot)
* 2023-03-31 23:20:56 [INFO]   All Needed Packages are already installed.
* 2023-03-31 23:20:56 [INFO]
* 2023-03-31 23:20:56 [INFO] Checking EasyApache profile compatibility with CloudLinux 8.
* 2023-03-31 23:20:56 [INFO] Running: /usr/local/bin/ea_current_to_profile --target-os=CloudLinux_8 --output=/tmp/85uY6PNw7r/ea_profile.json
* 2023-03-31 23:20:57 [INFO] Backed up EA4 profile to /tmp/85uY6PNw7r/ea_profile.json
* 2023-03-31 23:20:58 [WARN] Please fix the detected issues before performing the elevation process.

------

Here is the list of packages installed from cl7h repo and I believe many of these packages are core packages for operating system (maybe I am wrong)

yum list installed | grep -B1 cl7h
cloudlinux-logos.noarch            70.7.0-1.el7      @/cloudlinux-logos-70.0.3-5.el7.noarch
cloudlinux-release.x86_64          7.9-2.3.el7h      @cl7h
dracut.x86_64                      049-191.git20210920.el7h.cloudlinux	@cl7h
dracut-config-generic.x86_64       049-191.git20210920.el7h.cloudlinux	@cl7h
dracut-config-rescue.x86_64        049-191.git20210920.el7h.cloudlinux	@cl7h
dracut-network.x86_64              049-191.git20210920.el7h.cloudlinux	@cl7h	@cloudlinux-x86_64-server-7
iproute.x86_64                     5.9.0-4.el7h      @cl7h
kernel.x86_64                      1:4.18.0-425.3.1.lve.2.el7h	@cl7h
kernel.x86_64                      1:4.18.0-425.10.1.lve.el7h	@cl7h
kernel.x86_64                      1:4.18.0-425.13.1.lve.el7h	@cl7h
kernel-core.x86_64                 1:4.18.0-425.3.1.lve.2.el7h	@cl7h
kernel-core.x86_64                 1:4.18.0-425.10.1.lve.el7h	@cl7h
kernel-core.x86_64                 1:4.18.0-425.13.1.lve.el7h	@cl7h
kernel-headers.x86_64              1:4.18.0-425.13.1.lve.el7h	@cl7h
kernel-modules.x86_64              1:4.18.0-425.3.1.lve.2.el7h	@cl7h
kernel-modules.x86_64              1:4.18.0-425.10.1.lve.el7h	@cl7h
kernel-modules.x86_64              1:4.18.0-425.13.1.lve.el7h	@cl7h
kernel-tools.x86_64                1:4.18.0-425.13.1.lve.el7h	@cl7h
kernel-tools-libs.x86_64           1:4.18.0-425.13.1.lve.el7h	@cl7h
kernel-triggers.noarch             1.0-5.el7         @cloudlinux-base
kexec-tools.x86_64                 2.0.20-14.el7h    @cl7h
kmod.x86_64                        2:25-19.el7h.cloudlinux.3	@cl7h
kmod-libs.x86_64                   2:25-19.el7h.cloudlinux.3	@cl7h
kmod-lve.x86_64                    1:2.0-48.el7h     @cl7h
kmod-lve.x86_64                    1:2.0-50.el7h     @cl7h
linux-firmware.noarch              20220210-108.git6342082c.el7h	@cl7h
python-perf.x86_64                 1:4.18.0-32.el7h.3	@cl7h
tuned.noarch                       2.11.0-12.el7_9   @updates
tuned-profiles-cloudlinux.noarch   0.2-2.el7h        @cl7h

------------------------------

I am hosted on Contabo VPS and originally I installed Almalinux 7 then upgraded it to Cloudlinux 7

**Comment by sloanebernstein** [comment]
Hello,

CloudLinux is not yet supported by this tool, though there appears to be work towards implementing that.

That said, we should probably be more clear about rejecting unrecognized distro values passed with `--upgrade-to=`.

Apologies for the inconvenience.
