### ISSUE TITLE
Failed Stage 3 cloud 

### ISSUE THREAD

**Issue by maisondasilva** [cpanel/elevate#231]
![image](https://user-images.githubusercontent.com/11423362/230746013-532db2b3-e5fe-4f37-aa80-47df80fe100e.png)

**Comment by atoomic** [comment]
At first glance you failed to download the elevate rpm `elevate-release-latest-el7.noarch.rpm`.

Could you confirm you can download it using the following command?
```
>  wget http://repo.almalinux.org/elevate/elevate-release-latest-el7.noarch.rpm
```

This could be a connectivity issue, or a temporary issue on the mirror you were using or maybe an invalid gpg check?

Thanks for checking if you can download the rpm.
If it works please run `/scripts/elevate-cpanel --continue` and provides us the log.

thanks

**Comment by atoomic** [comment]
@maisondasilva we've not hear from you at this point.
I will close the case, feel free to reopen it with more details if needed.
thanks

**Comment by maisondasilva** [comment]
Yes it worked, but after the reboot it lost the DNS settings, but I stopped at 4 where it asks for a cPanel license because I was testing on a copy of a VM, is it possible to get a license to test this until the end?

**Comment by atoomic** [comment]
Thanks for your confirmation.
Regarding the DNS settings issue or the license request, please contact customer support.
This is not something I can address as part of that GitHub ticket.
thanks for your understanding
