### ISSUE TITLE
unsupported yum repo

### ISSUE THREAD

**Issue by bassamNouh** [cpanel/elevate#232]
* 2023-04-12 11:50:28 [ERROR] 9 package(s) installed from unsupported YUM repo 'rpmfusion-free-updates' from /etc/yum.repos.d/rpmfusion-free-updates.repo
* 2023-04-12 11:50:28 [ERROR] 1 package(s) installed from unsupported YUM repo 'nodesource' from /etc/yum.repos.d/nodesource-el7.repo
* 2023-04-12 11:50:28 [WARN] *** Elevation Blocker detected: ***
  One or more enabled YUM repo are currently unsupported and have installed packages.
  You should disable these repositories and remove packages installed from them
  before continuing the update.

**Comment by toddr** [comment]
Hi, if that RPM is safe to remove, you can remove it and proceed with the upgrade. Then when the upgrade is done, you can restore it. Be sure that the RPM does not remove any critical data you might need.

That said, cPanel Technical Support is ready to help! Please contact [cPanel Technical Support](https://docs.cpanel.net/knowledge-base/technical-support-services/how-to-open-a-technical-support-ticket/) if you encounter problems.
