### ISSUE TITLE
TODO - re-factor

### ISSUE THREAD

**Issue by toddr** [cpanel/elevate#233]
[x] Remove HelpFul script or ship it with the product. or use Getopt::Long
[x] Rename and document purpose of each Elevate package
[x] EA4 components are incomplete.
[x] local constants for `lib/Elevate/Blockers/Distros.pm`
[x] Blocker: UptoDate and Script should be merged 
[x] Rename Yum block to Repositories 
[x] add meta helpers for grub2 components: pre / post 
[x] Add unit test to check that all blockers are plugged in Elevate::Blockers. Also check the pm is loaded by the fatpack script 
[ ] Elevate::Script review 
[ ] split Elevate::Service in two Elevate::Service and Elevate::Systemctl::Service

**Comment by atoomic** [comment]
Blocker: UptoDate and Script should be merged
