### ISSUE TITLE
[BLOCK] 

### ISSUE THREAD

**Issue by brelandr** [cpanel/elevate#242]
I am getting the following error
 One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8.
  Please remove these packages before continuing the update.
  - ea-php74-php-redis
  - ea-php80-php-redis

* 2023-04-26 10:43:37 [ERROR] 1 package(s) installed from unsupported YUM repo 'letsencrypt-cpanel' from /etc/yum.repos.d/letsencrypt.repo
* 2023-04-26 10:43:37 [ERROR] 1 package(s) installed from unsupported YUM repo 'remi-safe' from /etc/yum.repos.d/remi-safe.repo

**Comment by toddr** [comment]
Hi, 

If you would like further help, we recommend you open a ticket with cPanel support for further assistance. You can do this within WHM via "Create Support Ticket" or through https://support.cpanel.net/requests/new

Thanks!
