### ISSUE TITLE
[DOCS] We should probably mention something about EFI state potentially leading to leapp failures and how to avoid it

### ISSUE THREAD

**Issue by troglodyne** [cpanel/elevate#248]
A customer ran into a problem with leapp trying to mount `/sys/firmware/efi/vars` when the BIOS setting was in a state that would prevent it being mounted as anything other than readonly. For the Dell servers in question, it was a difference between having their EFI settings in BIOS as 'Controlled' versus 'Standard' regarding fail/success (respectively).

When we had our own technicians investigate the contents of that directory in order to see if there was anything we could glean in there that could potentially tip us off to something that would mean a blocker could be raised, we found nothing that really stood out which we could cue on.

As such, I'd say we probably should just document that if your BIOS' EFI settings are configured in a way which would frustrate bootloader updates, you should probably reconfigure the servers in question from a more locked down operating mode to a more permissive mode, maybe in an FAQ/Known Issues section?

**Comment by troglodyne** [comment]
Alternatively, we can attempt to mount this directory RW ourselves, and if it fails, block.

**Comment by toddr** [comment]
RE-88
