### ISSUE TITLE
Unknown error while checking blockers (Version 10)

### ISSUE THREAD

**Issue by philh7456** [cpanel/elevate#252]
CentOS 7.9.2009, cPanel 110

When running version 10 of the script (with --check), there is a warning:

* 2023-05-07 07:20:31 [WARN] Unknown error while checking blockers: Missing blockers at /scripts/elevate-cpanel line 102.

We did not get this warning with version 7. Additionally, version 10 is not warning that ea-php71 is installed.

Output from version 10:
* 2023-05-07 07:20:02 [INFO] Self-update of script version 10 requested.
* 2023-05-07 07:20:02 [INFO] Script is up to date.

* 2023-05-07 07:20:03 [INFO] Successfully verified signature for cpanel (key types: release).
* 2023-05-07 07:20:03 [INFO] Checking if your system is up to date: 
* 2023-05-07 07:20:03 [INFO] Running: /usr/bin/yum clean all
* 2023-05-07 07:20:03 [INFO] 
* 2023-05-07 07:20:04 [INFO] Loaded plugins: fastestmirror, universal-hooks
* 2023-05-07 07:20:04 [INFO] Cleaning repos: EA4 EA4-experimental-c7 cpanel-addons-production-feed
* 2023-05-07 07:20:04 [INFO]               : cpanel-plugins MariaDB103 base epel extras kernelcare
* 2023-05-07 07:20:04 [INFO]               : letsencrypt-cpanel updates wp-toolkit-cpanel
* 2023-05-07 07:20:04 [INFO]               : wp-toolkit-thirdparties
* 2023-05-07 07:20:04 [INFO] Cleaning up list of fastest mirrors
* 2023-05-07 07:20:04 [INFO] Other repos take up 7.4 M of disk space (use --verbose for details)
* 2023-05-07 07:20:04 [INFO] 
* 2023-05-07 07:20:04 [INFO] Running: /usr/bin/yum check-update -q
* 2023-05-07 07:20:04 [INFO] 
* 2023-05-07 07:20:29 [INFO] 
* 2023-05-07 07:20:29 [INFO] Checking /scripts/sysup
* 2023-05-07 07:20:29 [INFO] Running: /scripts/sysup
* 2023-05-07 07:20:29 [INFO] 
* 2023-05-07 07:20:29 [INFO] checkyum version 22.3  (excludes: bind-chroot)
* 2023-05-07 07:20:30 [INFO]   All Needed Packages are already installed.
* 2023-05-07 07:20:30 [INFO] 
* 2023-05-07 07:20:31 [ERROR] 1 package(s) installed from unsupported YUM repo 'letsencrypt-cpanel' from /etc/yum.repos.d/letsencrypt.repo
* 2023-05-07 07:20:31 [INFO] Unsupported YUM repo enabled 'EA4-experimental-c$releasever' without packages installed from /etc/yum.repos.d/EA4-experimental.repo, these will be disabled before ELevation
* 2023-05-07 07:20:31 [WARN] Unknown error while checking blockers: Missing blockers at /scripts/elevate-cpanel line 102.
* 2023-05-07 07:20:31 [WARN] Please fix the detected issues before performing the elevation process.

Output from version 7:
* 2023-04-23 07:20:01 [INFO] Self-update of script version 7 requested.
* 2023-04-23 07:20:02 [INFO] Script is up to date.

* 2023-04-23 07:20:02 [INFO] Successfully verified signature for cpanel (key types: release).
* 2023-04-23 07:20:04 [ERROR] 1 package(s) installed from unsupported YUM repo 'letsencrypt-cpanel' from /etc/yum.repos.d/letsencrypt.repo
* 2023-04-23 07:20:04 [ERROR] 1 package(s) installed from unsupported YUM repo 'EA4-experimental' from /etc/yum.repos.d/EA4-experimental.repo
* 2023-04-23 07:20:04 [WARN] *** Elevation Blocker detected: ***
  One or more enabled YUM repo are currently unsupported and have installed packages.
  You should disable these repositories and remove packages installed from them
  before continuing the update.
  
  Consider reporting this limitation to https://github.com/cpanel/elevate/issues
  
* 2023-04-23 07:20:12 [INFO] Checking if your system is up to date: 
* 2023-04-23 07:20:12 [INFO] Running: /usr/bin/yum clean all

* 2023-04-23 07:20:12 [INFO] 
* 2023-04-23 07:20:12 [INFO] Loaded plugins: fastestmirror, universal-hooks
* 2023-04-23 07:20:12 [INFO] Cleaning repos: EA4 EA4-experimental cpanel-addons-production-feed
* 2023-04-23 07:20:12 [INFO]               : cpanel-plugins MariaDB103 base epel extras kernelcare
* 2023-04-23 07:20:12 [INFO]               : letsencrypt-cpanel updates wp-toolkit-cpanel
* 2023-04-23 07:20:12 [INFO]               : wp-toolkit-thirdparties
* 2023-04-23 07:20:12 [INFO] Cleaning up list of fastest mirrors
* 2023-04-23 07:20:12 [INFO] Other repos take up 5.6 M of disk space (use --verbose for details)
* 2023-04-23 07:20:12 [INFO] 
* 2023-04-23 07:20:12 [INFO] Running: /usr/bin/yum check-update -q
* 2023-04-23 07:20:12 [INFO] 
* 2023-04-23 07:20:35 [INFO] 
* 2023-04-23 07:20:35 [INFO] Checking /scripts/sysup
* 2023-04-23 07:20:35 [INFO] Running: /scripts/sysup
* 2023-04-23 07:20:35 [INFO] 
* 2023-04-23 07:20:35 [INFO] checkyum version 22.3  (excludes: bind-chroot)
* 2023-04-23 07:20:36 [INFO]   All Needed Packages are already installed.
* 2023-04-23 07:20:36 [INFO] 
* 2023-04-23 07:20:36 [INFO] Checking EasyApache profile compatibility with AlmaLinux 8.
* 2023-04-23 07:20:36 [INFO] Running: /usr/local/bin/ea_current_to_profile --target-os=AlmaLinux_8 --output=/tmp/k68TLUxROm/ea_profile.json
* 2023-04-23 07:20:37 [INFO] Backed up EA4 profile to /tmp/k68TLUxROm/ea_profile.json
* 2023-04-23 07:20:37 [WARN] *** Elevation Blocker detected: ***
  One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8.
  Please remove these packages before continuing the update.
  - ea-php71
  - ea-php71-build
  - ea-php71-libc-client
  - ea-php71-pear
  - ea-php71-php-bcmath
  - ea-php71-php-bz2
  - ea-php71-php-calendar
  - ea-php71-php-cli
  - ea-php71-php-common
  - ea-php71-php-curl
  - ea-php71-php-devel
  - ea-php71-php-exif
  - ea-php71-php-fileinfo
  - ea-php71-php-fpm
  - ea-php71-php-ftp
  - ea-php71-php-gd
  - ea-php71-php-iconv
  - ea-php71-php-imap
  - ea-php71-php-litespeed
  - ea-php71-php-mbstring
  - ea-php71-php-mcrypt
  - ea-php71-php-mysqlnd
  - ea-php71-php-opcache
  - ea-php71-php-pdo
  - ea-php71-php-posix
  - ea-php71-php-sockets
  - ea-php71-php-xml
  - ea-php71-php-xmlrpc
  - ea-php71-php-zip
  - ea-php71-runtime
  
* 2023-04-23 07:20:38 [WARN] Please fix the detected issues before performing the elevation process.

**Comment by toddr** [comment]
yep looking into it. should be a quick fix. Sorry!

**Comment by troglodyne** [comment]
Pretty sure I know what the "unknown blocker" one was, as I hit this recently in development and fixed it in 2e3d977
```
[root@10-2-64-171 elevate]# git show 2e3d977 lib/Elevate/Blockers/Repositories.pm
commit 2e3d977090bfc5167d74a777cfd6de03a07999a9
Author: Andy Baugh <thomas.baugh@cpanel.net>
Date:   Fri May 5 16:09:32 2023 +0000

    Add blocker for python36 and test
    
    Also fix explosion due to bad caller of Base in InvalidYumRepo check

diff --git a/lib/Elevate/Blockers/Repositories.pm b/lib/Elevate/Blockers/Repositories.pm
index cc09834..b1c599a 100644
--- a/lib/Elevate/Blockers/Repositories.pm
+++ b/lib/Elevate/Blockers/Repositories.pm
@@ -130,7 +130,7 @@ sub _blocker_invalid_yum_repos ($self) {
             EOS
         }
 
-        if ( !Elevate::Blockers::Base->is_check_mode() ) {    # autofix when --check is not used
+        if ( !$self->is_check_mode() ) {    # autofix when --check is not used
             $self->_autofix_yum_repos();
 
             # perform a second check to make sure we are in good shape
```
Am currently making sure those ea packages are installed on test host and should have reproduced the issue momentarily

**Comment by troglodyne** [comment]
Spawned test host, v110.0.5 cPanel on CentOS 7
* Cloned elevate repository, checked out v10 tag, copied elevate-cpanel to /scripts, chmodded +x
* Provisioned suggested ea4 packages from blocker output by reporter
* Ran yum update to ensure no blocker from that. Rebooted server as kernel updates were applied.
* Ensured MySQL install was 8.0
* Ran `/scripts/elevate-cpanel --check`
Observed success:
```
[root@10-2-64-171 ~]# /scripts/elevate-cpanel --check
* 2023-05-08 16:31:33 [INFO] Checking if your system is up to date: 
* 2023-05-08 16:31:33 [INFO] Running: /usr/bin/yum clean all
* 2023-05-08 16:31:33 [INFO] 
* 2023-05-08 16:31:34 [INFO] Loaded plugins: fastestmirror, universal-hooks
* 2023-05-08 16:31:34 [INFO] Cleaning repos: EA4 cpanel-addons-production-feed cpanel-plugins base epel
* 2023-05-08 16:31:34 [INFO]               : extras imunify360 imunify360-rollout-1 imunify360-rollout-2
* 2023-05-08 16:31:34 [INFO]               : imunify360-rollout-3 imunify360-rollout-4
* 2023-05-08 16:31:34 [INFO]               : mysql-connectors-community mysql-tools-community
* 2023-05-08 16:31:34 [INFO]               : mysql80-community updates wp-toolkit-cpanel
* 2023-05-08 16:31:34 [INFO]               : wp-toolkit-thirdparties
* 2023-05-08 16:31:34 [INFO] Cleaning up list of fastest mirrors
* 2023-05-08 16:31:34 [INFO] Other repos take up 22 M of disk space (use --verbose for details)
* 2023-05-08 16:31:34 [INFO] 
* 2023-05-08 16:31:34 [INFO] Running: /usr/bin/yum check-update -q
* 2023-05-08 16:31:34 [INFO] 
* 2023-05-08 16:31:53 [INFO] 
* 2023-05-08 16:31:53 [INFO] Checking /scripts/sysup
* 2023-05-08 16:31:53 [INFO] Running: /scripts/sysup
* 2023-05-08 16:31:53 [INFO] 
* 2023-05-08 16:31:53 [INFO] checkyum version 22.3  (excludes: bind-chroot)
* 2023-05-08 16:31:55 [INFO]   All Needed Packages are already installed.
* 2023-05-08 16:31:55 [INFO] 
* 2023-05-08 16:32:09 [INFO] Checking EasyApache profile compatibility with AlmaLinux 8.
* 2023-05-08 16:32:09 [INFO] Running: /usr/local/bin/ea_current_to_profile --target-os=AlmaLinux_8 --output=/tmp/5gLPGSMjO3/ea_profile.json
* 2023-05-08 16:32:09 [INFO] Backed up EA4 profile to /tmp/5gLPGSMjO3/ea_profile.json
* 2023-05-08 16:32:10 [INFO] There is no known blockers to start the elevation process.
  You can consider running:
      /scripts/elevate-cpanel --start
```
This was not the expected result given the report, so I'll be posting some additional details about my testing host:
```
[root@10-2-64-171 ~]# cat /etc/yum.repos.d/EA4.repo 
[EA4]
name=EA4 ( EasyApache 4 )
mirrorlist=http://httpupdate.cpanel.net/ea4-c$releasever-$basearch-mirrorlist
gpgcheck=1
gpgkey=https://securedownloads.cpanel.net/cPanelPublicPkgKey.asc
enabled=1
cost=50
```
EA4 repo looking like I'd expect it to.
```
[root@10-2-64-171 ~]# rpm -q ea-php71
ea-php71-7.1.33-5.5.1.cpanel.x86_64
```
PHP version looking like what's up on mirrors. Checked other packages in set, same story.
```
[root@10-2-64-171 ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
```
A sanity check (for good measure) as by that point I was out of ideas.

Went on to run --start, to see if that operational mode (which also goes through blocker code) wound up elevating the host as expected.

Probably just something I'm missing here. If anyone can think of anything obvious I missed here for reproducing the issue, please reply to this and I'll give it another shot. Otherwise I'm not sure whether attempting to debug this will even be fruitful.

**Comment by toddr** [comment]
The error `Unknown error while checking blockers` has been confirmed to be resolved in `v11` releasing today or tomorrow.

**Comment by philh7456** [comment]
Hi, thanks for the update.
Is the ea-php71 not being reported a separate issue? I've just found out we also have ea-php74 installed, which has not been reported by either version 7 or version 10 of the script.

**Comment by philh7456** [comment]
Yes, it is being worked on :) I was just wondering if it should be reported as a blocker as was happening in version 7 of the script with ea-php7.1?

**Comment by atoomic** [comment]
I think with the fixed `v11` release you should be able to see that blocker for the unsupported php packages.
