### ISSUE TITLE
[BLOCK]

### ISSUE THREAD

**Issue by theozsnowman** [cpanel/elevate#260]
Ran the upgrade check on a couple of Centos 7.9 virtuals within the Vultr cloud and got the following error:

 2023-05-11 14:04:45 [WARN] *** Elevation Blocker detected: ***
  Your machine has multiple network interface cards (NICs) using kernel-names (ethX).
  Since the upgrade process cannot guarantee their stability after upgrade, you cannot upgrade.

  Please provide those interfaces new names before continuing the update.

spoke with Vultr support who said the NIC's are named and gave me the following output on one of the machines: (ive replaced the IP's with xxx's)

DEVICE=eth0
ONBOOT=yes
BOOTPROTO=static
IPADDR=**xxx.xxx.xxx.xxx**
NETMASK=255.255.254.0
GATEWAY=45.77.214.1
DNS1=108.61.10.10

IPV6INIT=yes
IPV6ADDR="xxxx:xxxx:xxxx:xxx:xxxx:xxx:xxx:xxxx/64"
IPV6_AUTOCONF="yes"
DNS2=2001:19f0:300:1704::6

# Private network: net5d6465db15297
DEVICE=eth1
ONBOOT=yes
BOOTPROTO=static
IPADDR=10.4.96.3
NETMASK=255.255.240.0
MTU=1450

**Comment by toddr** [comment]
Hi,

If you would like further help, we recommend you open a ticket with cPanel support for further assistance. You can do this within WHM via "Create Support Ticket" or through https://support.cpanel.net/requests/new

Thanks!
