### ISSUE TITLE
Elevate Problem The 'leapp upgrade' process failed.

### ISSUE THREAD

**Issue by lsaguiar** [cpanel/elevate#262]
Hi there,

any help on that? Server down!

2023-05-13 13:38:51 (3917) [ERROR] The elevation process failed during stage 3.
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR] You can continue the process after fixing the errors by running:
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel --continue
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR] You can check the error log by running:
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR] Last Error:
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR] The 'leapp upgrade' process failed.
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR] Please investigate, resolve then re-run the following command to continue the update:
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR]     /scripts/elevate-cpanel --continue
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR]
* 2023-05-13 13:38:51 (3917) [ERROR] You can read the full leapp report at: /var/log/leapp/leapp-report.txt
* 2023-05-13 13:38:51 (5014) [FATAL] The 'leapp upgrade' process failed.

The log is:

STDERR:

Failed to create directory /var/lib/leapp/el8userspace//sys/fs/selinux: Read-only file system

Failed to create directory /var/lib/leapp/el8userspace//sys/fs/selinux: Read-only file system

No matches found for the following disable plugin patterns: subscription-manager

Repository extras is listed more than once in the configuration

Repository extras-source is listed more than once in the configuration

Warning: Package marked by Leapp to upgrade not found in repositories metadata: gpg-pubkey

RPM: warning: Generating 6 missing index(es), please wait...

Error: Transaction test error:

  file /usr/lib64/.libcrypto.so.1.1.1k.hmac from install of openssl-libs-1:1.1.1k-9.el8_7.x86_64 conflicts with file from package openssl11-libs-1:1.1.1k-5.el7.x86_64

  file /usr/lib64/.libssl.so.1.1.1k.hmac from install of openssl-libs-1:1.1.1k-9.el8_7.x86_64 conflicts with file from package openssl11-libs-1:1.1.1k-5.el7.x86_64

  file /usr/lib64/engines-1.1/afalg.so from install of openssl-libs-1:1.1.1k-9.el8_7.x86_64 conflicts with file from package openssl11-libs-1:1.1.1k-5.el7.x86_64

  file /usr/lib64/engines-1.1/capi.so from install of openssl-libs-1:1.1.1k-9.el8_7.x86_64 conflicts with file from package openssl11-libs-1:1.1.1k-5.el7.x86_64

  file /usr/lib64/engines-1.1/padlock.so from install of openssl-libs-1:1.1.1k-9.el8_7.x86_64 conflicts with file from package openssl11-libs-1:1.1.1k-5.el7.x86_64

  file /usr/lib64/libcrypto.so.1.1.1k from install of openssl-libs-1:1.1.1k-9.el8_7.x86_64 conflicts with file from package openssl11-libs-1:1.1.1k-5.el7.x86_64

  file /usr/lib64/libssl.so.1.1.1k from install of openssl-libs-1:1.1.1k-9.el8_7.x86_64 conflicts with file from package openssl11-libs-1:1.1.1k-5.el7.x86_64

Need help.

My best regards,

Leandro

**Comment by toddr** [comment]
Hi,

We do not have the means to assist people with actively downed servers. If you would like further help, we recommend you open a ticket with cPanel support for further assistance. You can do this within WHM via "Create Support Ticket" or through https://support.cpanel.net/requests/new

Thanks!
