### ISSUE TITLE
Unknown error while checking blockers: Unable to backup EA4 profile

### ISSUE THREAD

**Issue by bashmail** [cpanel/elevate#275]
* 2023-05-30 16:40:25 [INFO] Successfully verified signature for cpanel (key types: release).
* 2023-05-30 16:41:02 [INFO] Checking if your system is up to date:
* 2023-05-30 16:41:02 [INFO] Running: /usr/bin/yum clean all
* 2023-05-30 16:41:02 [INFO]
* 2023-05-30 16:41:02 [INFO] Loaded plugins: fastestmirror, rhnplugin, universal-hooks
* 2023-05-30 16:41:02 [INFO] Cleaning repos: EA4-c7 cpanel-addons-production-feed cpanel-plugins cl-ea4
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-ea4-rollout-1 cloudlinux-ea4-rollout-10
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-ea4-rollout-11 cloudlinux-ea4-rollout-12
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-ea4-rollout-13 cloudlinux-ea4-rollout-14
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-ea4-rollout-2 cloudlinux-ea4-rollout-3
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-ea4-rollout-4 cloudlinux-ea4-rollout-5
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-ea4-rollout-6 cloudlinux-ea4-rollout-7
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-ea4-rollout-8 cloudlinux-ea4-rollout-9
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-imunify360 cloudlinux-rollout-1 cloudlinux-rollout-10
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-rollout-11 cloudlinux-rollout-12
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-rollout-13 cloudlinux-rollout-14 cloudlinux-rollout-2
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-rollout-3 cloudlinux-rollout-4 cloudlinux-rollout-5
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-rollout-6 cloudlinux-rollout-7 cloudlinux-rollout-8
* 2023-05-30 16:41:02 [INFO]               : cloudlinux-rollout-9 cloudlinux-x86_64-server-7 epel imunify360
* 2023-05-30 16:41:02 [INFO]               : wp-toolkit-cpanel wp-toolkit-thirdparties
* 2023-05-30 16:41:02 [INFO] Cleaning up list of fastest mirrors
* 2023-05-30 16:41:02 [INFO] Other repos take up 351 M of disk space (use --verbose for details)
* 2023-05-30 16:41:02 [INFO]
* 2023-05-30 16:41:02 [INFO] Running: /usr/bin/yum check-update -q
* 2023-05-30 16:41:02 [INFO]
* 2023-05-30 16:41:30 [INFO]
* 2023-05-30 16:41:30 [INFO] Checking /scripts/sysup
* 2023-05-30 16:41:30 [INFO] Running: /scripts/sysup
* 2023-05-30 16:41:30 [INFO]
* 2023-05-30 16:41:30 [INFO] checkyum version 22.3  (excludes: bind-chroot)
* 2023-05-30 16:41:30 [INFO]   All Needed Packages are already installed.
* 2023-05-30 16:41:30 [INFO]
* 2023-05-30 16:41:30 [INFO] Checking EasyApache profile compatibility with CloudLinux 8.
* 2023-05-30 16:41:30 [INFO] Running: /usr/local/bin/ea_current_to_profile --target-os=CloudLinux_8
* 2023-05-30 16:41:31 [WARN] Unknown error while checking blockers: Unable to backup EA4 profile. Failure from /usr/local/bin/ea_current_to_profile --target-os=CloudLinux_8 at /scripts/elevate-cpanel line 1817.

**Comment by atoomic** [comment]
Could you tell us more and provide the output for the command `/usr/local/bin/ea_current_to_profile --target-os=CloudLinux_8`
thanks

**Comment by bashmail** [comment]
[root@bhs2 network-scripts]# /usr/local/bin/ea_current_to_profile --target-os=CloudLinux_8
Cpanel::Exception::JSONParseError/(XID hdvuh5) The system failed to parse the JSON stream data “{
   "EA4" : {
      "CentOS_6.5_standard" : [
         "autotools-latest",
         "autotools-latest-autoconf",
         "autotools-latest-m4",
         "autotools-latest-runtime",
         "ea-apache24",
         "ea-apache24-config",
         "ea-apache24-config-runtime",
         "ea-apache24-devel",
         "ea-apache24-manual",
         "ea-apache24-mod_allowmethods",
         "ea-apache24-mod_asis",
         "ea-apache24-mod_auth_digest",
         "ea-apache24-mod_authn_anon",
         "ea-apache24-mod_authn_dbd",
         "ea-apache24-mod_authn_dbm",
         "ea-apache24-mod_authn_socache",
         "ea-apache24-mod_authnz_ldap",
         "ea-apache24-mod_authz_dbd",
         "ea-apache24-mod_authz_dbm",
         "ea-apache24-mod_authz_owner",
         "ea-apache24-mod_brotli",
         "ea-apache24-mod_buffer",
         "ea-apache24-mod_bw",
         "ea-apache24-mod_bwlimited",
         "ea-apache24-mod_cache",
         "ea-apache24-mod_cache_disk",
         "ea-apache24-mod_cache_socache",
     ” from the file “/etc/cpanel/ea4/profiles/pkg-manifest.json” because of an error: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 244747 (before "],\n      "CentOS_9"...") at /usr/local/cpanel/Cpanel/JSON.pm line 128.

 at /usr/local/cpanel/Cpanel/JSON.pm line 147.
        Cpanel::JSON::_throw_json_error("malformed JSON string, neither tag, array, object, number, st"..., "/etc/cpanel/ea4/profiles/pkg-manifest.json", SCALAR(0xf36548)) called at /usr/local/cpanel/Cpanel/JSON.pm line 128
        Cpanel::JSON::Load("{\x{a}   \"EA4\" : {\x{a}      \"CentOS_6.5_standard\" : [\x{a}         \"auto"..., "/etc/cpanel/ea4/profiles/pkg-manifest.json") called at /usr/local/cpanel/Cpanel/JSON.pm line 290
        Cpanel::JSON::_LoadFile("/etc/cpanel/ea4/profiles/pkg-manifest.json", 0, 0, undef, 0) called at /usr/local/cpanel/Cpanel/JSON.pm line 227
        Cpanel::JSON::LoadFile("/etc/cpanel/ea4/profiles/pkg-manifest.json") called at /usr/local/bin/ea_current_to_profile line 137
        ea_cpanel_tools::ea_current_to_profile::script("--target-os=CloudLinux_8") called at /usr/local/bin/ea_current_to_profile line 53

**Comment by toddr** [comment]
@bashmail, It appears you have a corrupt file on your server. If you would like further help, we recommend you open a ticket with cPanel support for further assistance. You can do this within WHM via "Create Support Ticket" or through https://support.cpanel.net/requests/new

Thanks!

**Comment by atoomic** [comment]
Would you mind providing the content of the file: `/etc/cpanel/ea4/profiles/pkg-manifest.json`
thanks
