### ISSUE TITLE
Enhance YUM blockers to be more clear about the problem

### ISSUE THREAD

**Issue by toddr** [cpanel/elevate#285]
A blocker in #129 indicated:

- System is not up to date
- yum is not stable

It was not obvious what the problem was and more importantly how the customer could reproduce the problem. Maybe we need to advise a command they can run to see the failure, which is why we're blocking. Or maybe we need to `ERROR()` when we fail to run something so it's more clear in the overall output.

**Comment by sloanebernstein** [comment]
It sounds like there are two parts to this:

1. The assessor in the Security Advisor needs to point users to run the check manually or to check the log file.
2. Some of the direct SafeRun calls in `lib/Elevate/Blockers/Repositories.pm` need replacing with `ssystem`-like calls.

**Comment by toddr** [comment]
RE-89
