### ISSUE TITLE
[BLOCK] Can't elevate on OpenVZ/Virtuozzo 7

### ISSUE THREAD

**Issue by imorandinwnp** [cpanel/elevate#286]
Hi,

I know that there is a blocker that needs GRUB to be able to elevate. But I couldn't find any info on why there is such a restriction.

We have a lot of OpenVZ 7 containers with cPanel and it would be great to have an Elevate that is complatible with this technology as Almalinux 8 works fine with openvz.

Thanks,

Ignacio

**Comment by troglodyne** [comment]
OpenVZ is usually configured in a manner which would result in the kernel Alma or Rocky 8 install and try to boot into to *not be loaded* (instead loading the one VZ has configured). This can lead to failure to boot after the LEAPP run executes. This is not an outcome we wish upon users of this project.

We're currently coordinating with Virtuozzo to try to find a solution, and should know more soon.

**Comment by imorandinwnp** [comment]
Thanks! looking forward to it

**Comment by imorandinwnp** [comment]
Hi @toddr : is there any news to elevate OpenVZ containers to AL8? Thanks

**Comment by imorandinwnp** [comment]
Found it! and seems to be working fine: https://docs.virtuozzo.com/virtuozzo_hybrid_server_7_users_guide/advanced-tasks/converting-containers-with-almaconvert8.html

**Comment by jpswade** [comment]
@toddr would it be possible to reopen this issue please? Thanks.

**Comment by jpswade** [comment]
> The package is now currently being published at https://repo.virtuozzo.com/vzlinux/vzdeploy/vzdeploy8.rpm

```
# almaconvert8 convert 901
901: Conversion aborted: Software unsupported by AlmaLinux 8 detected: cPanel
Please contact the software vendor and request AlmaLinux 8 support
```

**Comment by toddr** [comment]
> @toddr please can we reopen this issue?
The script you are reporting on is not in this project. You need to take this up with virtuozzo.
