### ISSUE TITLE
[UPG FAIL] /elevate-cpanel --start fail  stage 3

### ISSUE THREAD

**Issue by DenisCunha** [cpanel/elevate#290]
stopped at step 3 and asked to correct the errors and run `/scripts/elevate-cpanel --continue` pyton error in some library file in leapp, then as the server crashed via IPMI I ran the command `/scripts/elevate- cpanel --clean ` and I reinstalled easy apache and put the server online, but since then I haven't rebooted, if I do it, does it run the risk of the system not returning?

**Comment by toddr** [comment]
If you would like further help, we recommend you open a ticket with cPanel support for further assistance. You can do this within WHM via "Create Support Ticket" or through https://support.cpanel.net/requests/new

Thanks,

**Comment by DenisCunha** [comment]
> If you would like further help, we recommend you open a ticket with cPanel support for further assistance. You can do this within WHM via "Create Support Ticket" or through https://support.cpanel.net/requests/new

I just need to know if there is any command to cancel the upgrade that failed in stage 3, or once the process has started there is no turning back?
