### ISSUE TITLE
[BLOCK] target_userspace_creator - inconsistent error message

### ISSUE THREAD

**Issue by plt-dio** [cpanel/elevate#291]
There is no clear error message as no recomended solution about this situation.

[INFO] ====> * target_userspace_creator
* 2023-07-05 00:12:57 (4296) [INFO]         Initializes a directory to be populated as a minimal environment to run binaries from the target system.
* 2023-07-05 00:12:59 (4296) [INFO] Process Process-512:
* 2023-07-05 00:12:59 (4296) [INFO] Traceback (most recent call last):
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
* 2023-07-05 00:12:59 (4296) [INFO]     self.run()
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
* 2023-07-05 00:12:59 (4296) [INFO]     self._target(*self._args, **self._kwargs)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
* 2023-07-05 00:12:59 (4296) [INFO]     actor_instance.run(*args, **kwargs)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
* 2023-07-05 00:12:59 (4296) [INFO]     self.process(*args)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/actor.py", line 52, in process
* 2023-07-05 00:12:59 (4296) [INFO]     userspacegen.perform()
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/utils/deprecation.py", line 42, in process_wrapper
* 2023-07-05 00:12:59 (4296) [INFO]     return target_item(*args, **kwargs)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py", line 685, in perform
* 2023-07-05 00:12:59 (4296) [INFO]     target_repoids = _gather_target_repositories(context, indata, prod_cert_path)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py", line 629, in _gather_target_repositories
* 2023-07-05 00:12:59 (4296) [INFO]     _install_custom_repofiles(context, indata.custom_repofiles)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py", line 607, in _install_custom_repofiles
* 2023-07-05 00:12:59 (4296) [INFO]     context.copy_to(rfile.file, _dst_path)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/mounting.py", line 233, in copy_to
* 2023-07-05 00:12:59 (4296) [INFO]     shutil.copy2(src, self.full_path(dst))
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
* 2023-07-05 00:12:59 (4296) [INFO]     copyfile(src, dst)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib64/python2.7/shutil.py", line 69, in copyfile
* 2023-07-05 00:12:59 (4296) [INFO]     raise Error("`%s` and `%s` are the same file" % (src, dst))
* 2023-07-05 00:12:59 (4296) [INFO] Error: `/etc/yum.repos.d/cloudlinux-rollout.repo` and `/var/lib/leapp/scratch/mounts/root_/system_overlay/etc/yum.repos.d/cloudlinux-rollout.repo` are the same file
* 2023-07-05 00:12:59 (4296) [INFO]
* 2023-07-05 00:12:59 (4296) [INFO]
* 2023-07-05 00:12:59 (4296) [INFO] =========================================================================================================
* 2023-07-05 00:12:59 (4296) [INFO] Actor target_userspace_creator unexpectedly terminated with exit code: 1 - Please check the above details
* 2023-07-05 00:12:59 (4296) [INFO] =========================================================================================================
* 2023-07-05 00:12:59 (4296) [INFO] Traceback (most recent call last):
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/bin/leapp", line 9, in <module>
* 2023-07-05 00:12:59 (4296) [INFO]     load_entry_point('leapp==0.14.0', 'console_scripts', 'leapp')()
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/cli/__init__.py", line 37, in main
* 2023-07-05 00:12:59 (4296) [INFO]     cli.command.execute('leapp version {}'.format(VERSION))
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 106, in execute
* 2023-07-05 00:12:59 (4296) [INFO]     args.func(args)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 128, in called
* 2023-07-05 00:12:59 (4296) [INFO]     self.target(args)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/cli/commands/upgrade/breadcrumbs.py", line 94, in wrapper
* 2023-07-05 00:12:59 (4296) [INFO]     return f(*args, breadcrumbs=breadcrumbs, **kwargs)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/cli/commands/upgrade/__init__.py", line 104, in upgrade
* 2023-07-05 00:12:59 (4296) [INFO]     only_with_tags=only_with_tags)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
* 2023-07-05 00:12:59 (4296) [INFO]     self.gen.throw(type, value, traceback)
* 2023-07-05 00:12:59 (4296) [INFO]   File "/usr/lib/python2.7/site-packages/leapp/cli/commands/upgrade/util.py", line 304, in format_actor_exceptions
* 2023-07-05 00:12:59 (4296) [INFO]     logger.error(e.message)
* 2023-07-05 00:12:59 (4296) [INFO] NameError: global name 'e' is not defined
* 2023-07-05 00:12:59 (4313) [INFO]
* 2023-07-05 00:12:59 (742) [INFO] Sending notification: Fail to update to CloudLinux 8

**Comment by troglodyne** [comment]
I note here that this appears to be an update to CloudLinux 8 based on the failure message (presumably from CloudLinux 7?).

Though we are working on this upgrade path, that has not yet been completed, so I would not be surprised that things may fail until we add supporting code for it. A pull request is currently open about this, so more than likely support for this should be coming soon. https://github.com/cpanel/elevate/pull/283

**Comment by troglodyne** [comment]
So the only thing remaining to know here would be "how exactly did we even get to this point" as normally we block instantly if the base OS is not CentOS 7. As such there's a legitimate question about what scenario led to this as a starting condition. If you can give me more information about what the system looked like before elevate was ran that might be helpful in reproducing why we even got into the condition of failing to upgrade to *CloudLinux 8* instead of say, Alma or Rocky.

**Comment by toddr** [comment]
CL7 -> CL8 is not supported by us at this time.
