### ISSUE TITLE
[BLOCK] Cpanel/KernelCare/Availability.pm did not return a true value at /usr/local/cpanel/Cpanel/KernelCare.pm line 14.

### ISSUE THREAD

**Issue by Harwerp** [cpanel/elevate#293]
I have problem in the step 9: 
[root@cpanel ~]# /scripts/elevate-cpanel --check --upgrade-to=almalinux
Cpanel/KernelCare/Availability.pm did not return a true value at /usr/local/cpanel/Cpanel/KernelCare.pm line 14.
BEGIN failed--compilation aborted at /usr/local/cpanel/Cpanel/KernelCare.pm line 14.
Compilation failed in require at /usr/local/cpanel/Cpanel/Kernel/Status.pm line 13.
BEGIN failed--compilation aborted at /usr/local/cpanel/Cpanel/Kernel/Status.pm line 13.
Compilation failed in require at /scripts/elevate-cpanel line 387.
BEGIN failed--compilation aborted at /scripts/elevate-cpanel line 387.

**Comment by Harwerp** [comment]
no edit that kernel

OS: CentOS v7.9.2009 STANDARD kvm
cPanel Version: [110.0.8]

**Comment by atoomic** [comment]
Please open a Customer Support ticket 

In order to get support from cPanel, please open a support ticket. You can read more about requesting support from
https://docs.cpanel.net/knowledge-base/technical-support-services/how-to-open-a-technical-support-ticket/

**Comment by atoomic** [comment]
I wonder if the issue you are viewing was fixed by `CPANEL-40545` and is available in `11.112` (available since 112.0.0 and later)

**Comment by Harwerp** [comment]
I can't update the version, it asks me to have Almalinux, the most I have is this version: [110.0.9]

**Comment by Harwerp** [comment]
I did an update to my Cpanel, and I did not realize that the version had been updated from [110.0.8] to [110.0.9], and this small change did the magic, I no longer present that error: although I get other errors I'll be watching but this has already happened, thanks for the help :)
![image](https://github.com/cpanel/elevate/assets/88891043/40ec15ee-c450-46ee-89b5-f45f406d7b38)
