### ISSUE TITLE
[BLOCK]

### ISSUE THREAD

**Issue by krazykatz911** [cpanel/elevate#294]
I am installing on a VPS Centos 7.

This is the errors I am getting:

===========================================================
                           ERRORS
============================================================

2023-08-07 05:58:37.368017 [ERROR] Actor: check_installed_kernels
Message: Cannot find any installed kernel signed by Red Hat.

============================================================
                       END OF ERRORS
============================================================

============================================================
                     UPGRADE INHIBITED
============================================================

Upgrade has been inhibited due to the following problems:
    1. Inhibitor: Btrfs has been removed from RHEL8
Consult the pre-upgrade report for details and possible remediation.

**Comment by toddr** [comment]
Hi, it appears your big problem is that you're running on BTRFS which isn't available on 8. I don't think anything short of moving off of that would help. Please open a ticket with cPanel support if you need further help.
