### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by devops365** [cpanel/elevate#296]
Issue is affecting probably the vast majority of Gen 8 HPE Servers. It stops in Step 4 and needs manual actions.
The script did not generate any warnings before to alert me prior to starting the upgrade.
It will cause the server to have no connection and experience serious problems with its console.

Steps had to be taken in order to resolve this.
Relevant guide on how to remediate the issue is here : https://forums.cpanel.net/threads/elevate-on-gen-8-hp-enterprise-servers-goes-wrong.713033/

In order to reproduce it you can run it on a HPE Gen 8 server with broadcom NIC's.

Kindly upgrade the elevate script to check if this is a Gen 8 server with the specific drivers needed.
If this is the case, simply download the needed rpm before upgrade on step 3 install the needed rpm on the system.
It must also make the needed changes if it is needed on the NIC configuration as well as the grub options.

If the script takes care of the above, everything should be ok.

After we applied the fixes as we explained them in our forum post, everything worked flawlessly. The elevate was able to complete and no further errors or problems were detected.

**Comment by troglodyne** [comment]
Honestly I suspect this issue would be present even on non-cpanel elevations using leapp if the issue at hand is needing to reinstall a missing driver for a NIC.

Whatever solution we think of doing would probably be best targeted at almalinux's fork of leapp. This isn't to say we won't consider doing the work, but certainly if we do then it would be over on that side of things rather than in the scope of the cpanel-elevate script (other than perhaps a temporary workaround for this issue until a fix for that gets accepted in the upstream leapp tooling).

Any thoughts on this @toddr ?

**Comment by devops365** [comment]
Thanks for the follow up Andy @troglodyne 

Indeed the issue is more wide regarding RHEL 8 derived operating systems since RHEL left out this driver and I believe almalinux should look into this. If you have a way to communicate this issue with them it would be great.
Gen 8 servers are still very widely used , not just in the Hosting industry. And with the current vendor shortages , these machines will probably serve for at least another 3-4 years. To be honsest, since almalinux8 will have support until 2029 and these are still powerfull machines, seems reasonable.
Without this fix pleople will be stranded with servers that are inoperative in the midst of an upgrade. 
Also some data centers don't provide their customers directly with iLO , so it is important for this to be implemented as a check. You can't foresee the issue when you run the preupgrade checks. No warning will be given with the current elevate script.

Thankfully detecting a Gen8 server is very easy and reliable via dmesg
```
#dmesg | grep Gen8
[    0.000000] DMI: HP ProLiant BL460c Gen8, BIOS I31 05/21/2018
```

and the solution imho should also be relatively easy to implement.

**Comment by devops365** [comment]
I accidentally closed it.
