### ISSUE TITLE
 The elevation process failed during stage 3

### ISSUE THREAD

**Issue by moch2123** [cpanel/elevate#300]
I was using cpanel elevate script to upgrade cpanel vm to almalinux 8.x.  All went smoothly untill step 3 and then it produced the error

 The elevation process failed during stage 3

I submitted below logs to cPanel support team 

==> Processing phase `FactsCollection`
 ====> * vendor_repositories_mapping
        Scan the vendor repository mapping files and provide the data to other actors.
====> * system_facts
]         Provides data about many facts from system.

 Traceback (most recent call last):
   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
     self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
]   File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
]     self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/systemfacts/actor.py", line 65, in process
   bios_grubcfg_details = systemfacts.get_bios_grubcfg_details()
   File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/systemfacts/libraries/systemfacts.py", line 326, in get_bios_grubcfg_details
    with open('/boot/grub2/grub.cfg') as fo:
 IOError: [Errno 2] No such file or directory: '/boot/grub2/grub.cfg'

Actually the system is using centos-plus kernel and their recommendation is use to default centos kernel so that elevate will work but this is not possible now to remove it and install default kernel. Is there any modification or change can be possible in script or any other solution to fix this issue is appreciated

**Comment by moch2123** [comment]
Again...
the grub.cfg.bak is resides under /boot/grub2
 I tried rename it and started the process but no luck

**Comment by sloanebernstein** [comment]
Hello,

Do you happen to know what kind of virtualization and/or bootloader is being used? The implication of a missing `/boot/grub2/grub.cfg` is that either a different bootloader is being used, or the virtualization type doesn't use a bootloader at all.

**Comment by moch2123** [comment]
Thanks. Ticket ID 95111249

**Comment by sloanebernstein** [comment]
Hello,

I have left some notes for the next available analyst who works your support ticket. Thank you for your patience and understanding.

**Comment by moch2123** [comment]
Hello

I replied to support team. Can elevate be modify so that it can use legacy grub

**Comment by toddr** [comment]
It cannot use legacy grub. Almalinux 8 does not support this.
