### ISSUE TITLE
[REPO] Support repo - nodesource, ookla_speedtest

### ISSUE THREAD

**Issue by fahadx4** [cpanel/elevate#301]
/scripts/elevate-cpanel --check
* 2023-08-29 23:42:05 [INFO] Successfully verified signature for cpanel (key types: release).
* 2023-08-29 23:42:05 [WARN] *** Elevation Blocker detected: ***
  This installation of cPanel (11.110.0.7) does not appear to be up to date. Please upgrade cPanel to a most recent version.
* 2023-08-29 23:42:07 [WARN] Unsupported YUM repo enabled 'nodesource' without packages installed from /etc/yum.repos.d/nodesource-el7.repo
* 2023-08-29 23:42:07 [WARN] Unsupported YUM repo enabled 'ookla_speedtest-cli' without packages installed from /etc/yum.repos.d/ookla_speedtest-cli.repo
* 2023-08-29 23:42:07 [WARN] Unsupported YUM repo enabled 'ookla_speedtest-cli-source' without packages installed from /etc/yum.repos.d/ookla_speedtest-cli.repo
* 2023-08-29 23:42:07 [WARN] Unsupported YUM repo enabled 'imunify360-rollout-5' without packages installed from /etc/yum.repos.d/imunify-new-rollout.repo
* 2023-08-29 23:42:07 [WARN] Unsupported YUM repo enabled 'imunify360-rollout-6' without packages installed from /etc/yum.repos.d/imunify-new-rollout.repo
* 2023-08-29 23:42:07 [WARN] Unsupported YUM repo enabled 'imunify360-rollout-7' without packages installed from /etc/yum.repos.d/imunify-new-rollout.repo
* 2023-08-29 23:42:07 [WARN] Unsupported YUM repo enabled 'imunify360-rollout-8' without packages installed from /etc/yum.repos.d/imunify-new-rollout.repo
* 2023-08-29 23:42:07 [WARN] *** Elevation Blocker detected: ***
  One or more enabled YUM repo are currently unsupported.
  You should disable these repositories and remove packages installed from them
  before continuing the update.

  Consider reporting this limitation to https://github.com/cpanel/elevate/issues

**Comment by toddr** [comment]
* nodesource-el7.repo
* ookla_speedtest-cli.repo
* imunify360-rollout-5
* imunify360-rollout-6
* imunify360-rollout-7
* imunify360-rollout-8

**Comment by toddr** [comment]
the most recent release already supports the additional imunif360-rollout repos.

**Comment by toddr** [comment]
imunify360 is fixed. you should remove ookla_speedtest-cli RPMs manually before running elevate.
