### ISSUE TITLE
[BUG] Unsupported YUM repo 'EA4-c$releasever'

### ISSUE THREAD

**Issue by atoomic** [cpanel/elevate#307]
**Describe the bug**

Notice that using the name for ea4 yum repo show as unsupported

```
* 2023-09-06 20:49:23 (1653) [INFO] Unsupported YUM repo enabled 'EA4-c$releasever' without packages installed from /etc/yum.repos.d/EA4.repo, these will be disabled before ELevation
 ```

probably fine to simply add `EA4-c$releasever` to the vetted list

**Comment by sloanebernstein** [comment]
That's happening because we aren't evaluating YUM/DNF variables when we parse the repo ID. It shouldn't be too hard to do this, in principle.
