### ISSUE TITLE
cpanel-elevate stage 4 failure during mysql upgrade 

### ISSUE THREAD

**Issue by subz9tech** [cpanel/elevate#311]
Stage 4 failures during MySQL upgrade.

```
* 2023-09-07 08:19:33 (4119) [ESC[32mINFOESC[0m] 
* 2023-09-07 08:19:34 (5692) [ESC[32mINFOESC[0m] ******************************************************************************************
* 2023-09-07 08:19:34 (5693) [ESC[32mINFOESC[0m] *
* 2023-09-07 08:19:34 (5694) [ESC[32mINFOESC[0m] * Starting stage 4 of 5
* 2023-09-07 08:19:34 (5695) [ESC[32mINFOESC[0m] *
* 2023-09-07 08:19:34 (5696) [ESC[32mINFOESC[0m] ******************************************************************************************
* 2023-09-07 08:19:34 (5666) [ESC[32mINFOESC[0m] Stage 4: skipping sysup (already run)
* 2023-09-07 08:19:34 (5666) [ESC[32mINFOESC[0m] Stage 4: skipping restore_cpanel_services (already run)
* 2023-09-07 08:19:34 (5666) [ESC[32mINFOESC[0m] Stage 4: skipping compoment:EA4:post_leapp (already run)
* 2023-09-07 08:19:34 (5666) [ESC[32mINFOESC[0m] Stage 4: skipping upcp (already run)
* 2023-09-07 08:19:34 (5902) [ESC[32mINFOESC[0m] Removing leapp from excludes in /etc/yum.conf
* 2023-09-07 08:19:34 (5641) [ESC[1;37mDEBUGESC[0m] Running 'post_leapp' from MySQL component.
* 2023-09-07 08:19:34 (3082) [ESC[32mINFOESC[0m] Restoring MySQL 8.0
* 2023-09-07 08:19:34 (3086) [ESC[32mINFOESC[0m] Restoring /etc/my.cnf.rpmsave_pre_elevate to /etc/my.cnf...
* 2023-09-07 08:19:35 (3095) [ESC[32mINFOESC[0m] Restoring MySQL via upgrade_id mysql_upgrade.20230907-081934
* 2023-09-07 08:19:35 (3096) [ESC[32mINFOESC[0m] Waiting for MySQL installation
* 2023-09-07 08:25:04 (3126) [ESC[1;31mFATALESC[0m] Failed to restore MySQL 8.0: upgrade mysql_upgrade.20230907-081934 status 'failed'
* 2023-09-07 08:25:04 (3127) [ESC[1;31mFATALESC[0m] ---  
```

Clicking continue returns the same error. The MySQL upgrades were completed successfully, according to the API. 

```
/usr/local/cpanel/bin/whmapi1 background_mysql_upgrade_status upgrade_id=mysql_upgrade.20230907-081934
 
state: success
metadata: 
  command: background_mysql_upgrade_status
  reason: OK
  result: 1
  version: 1
```

Clicking continue over and over dies at the same spot every time. This is a non-critical failure as MySQL was able to be replaced and restarted successfully; Elevate needs a way to skip this kind of failure.

**Comment by atoomic** [comment]
Would you mind providing the logs from `/var/cpanel/logs/mysql_upgrade.20230907-081934` directory?
Thanks

**Comment by toddr** [comment]
This is a side effect of the cPanel installer output, reported in CPANEL-43253. We should probably not die on most failures in stage 4 since most of them can later be recovered by the sysadmin with help from cPanel support. Potentially we could also provide a skip option.

**Comment by subz9tech** [comment]
`-rw-------  1 root root    0 Sep  7 08:19 unattended_background_upgrade.error
-rw-------  1 root root  16K Sep  7 08:25 unattended_background_upgrade.log
-rw-------  1 root root  28K Sep  7 08:25 unattended_background_upgrade.output
-rw-------  1 root root    1 Sep  7 08:25 unattended_background_upgrade.result
`
[unattended_background_upgrade.log](https://github.com/cpanel/elevate/files/12552861/unattended_background_upgrade.log)

[unattended_background_upgrade.output.txt](https://github.com/cpanel/elevate/files/12552864/unattended_background_upgrade.output.txt)
