### ISSUE TITLE
[UPG FAIL] At stage 4 The system could not fetch the script for kernelcare_installer

### ISSUE THREAD

**Issue by caliphkhan** [cpanel/elevate#313]
![image](https://github.com/cpanel/elevate/assets/26359494/880bc2db-b19d-459e-8fea-62364b877d10)

I ran check script and it gave me ok to run now I am stuck at stage 4 each time I continue I get this error.

I have tried updating cpanel to latest version and its now updated to [114.0.6] but elevate still can't continue.

**Comment by toddr** [comment]
Please contact support for further help.
