### ISSUE TITLE
[UPG FAIL] 

### ISSUE THREAD

**Issue by mustafatahhan** [cpanel/elevate#314]
faild stage 4 

<img width="1100" alt="Scherm­afbeelding 2023-09-26 om 10 50 04 AM" src="https://github.com/cpanel/elevate/assets/129319316/17099481-f670-4b92-b8a0-646f2d26a228">

dnf not working 
<img width="752" alt="Scherm­afbeelding 2023-09-26 om 10 50 44 AM" src="https://github.com/cpanel/elevate/assets/129319316/b34b2d34-0e44-44a5-b3c5-8fcb4fa07f63">

**Comment by toddr** [comment]
Please open a ticket with support for further help if you now have access to the box. Alternatively you need to restore to backup if the system has been corrupted.
