### ISSUE TITLE
[BUG] resolve.conf changed, rocky as alma installed

### ISSUE THREAD

**Issue by agrisvv** [cpanel/elevate#316]
**Describe the bug**
1. Upgrade stuck after one of reboot then OS changed /etc/resolve.conf file. My DNS servers was removed and added 127.0.0.1.  So dns resolution disappeared and dnf can't resolve repos. I think it is because it migrated to systemd resolved.
2. Started to install rocky /scripts/elevate-cpanel --start --upgrade-to=rocky but at the end it was Alma linux installed.
3. after elevate migrate i used rockymigrate script to migrate from alma to rocky.

**2 bash history of rocky**
```` 
  912  2023-10-04 22:08:04 chmod 700 /scripts/elevate-cpanel 
  913  2023-10-04 22:08:15 /scripts/elevate-cpanel --check --upgrade-to=rocky
  922  2023-10-04 22:17:39 /scripts/elevate-cpanel --check --upgrade-to=rocky
  926  2023-10-04 22:31:22 /scripts/elevate-cpanel --start --upgrade-to=rocky
  927  2023-10-04 22:36:58 /scripts/elevate-cpanel --start --upgrade-to=rocky
  928  2023-10-04 22:37:10 /scripts/elevate-cpanel --check
  929  2023-10-04 22:37:48 /scripts/elevate-cpanel --continue
  930  2023-10-04 22:39:29 /scripts/elevate-cpanel --status
  931  2023-10-04 22:39:36 /scripts/elevate-cpanel --log
  932  2023-10-04 23:22:14 /scripts/elevate-cpanel --log
  956  2023-10-04 23:31:13 cat /usr/local/cpanel/scripts/elevate-cpanel
  959  2023-10-04 23:32:28 /usr/local/cpanel/scripts/elevate-cpanel --continue
  962  2023-10-04 23:43:39 /scripts/elevate-cpanel --log
 1066  2023-10-05 10:19:33 /scripts/elevate-cpanel --log
 1074  2023-10-05 10:24:25 history |grep elevate-cpanel

`````

**Comment by toddr** [comment]
Hi, we would need to see your log to know what occurred. The script does not modify resolv.conf. Which stage did it stick in? We suggest you open a ticket with cPanel support for further assistance.
