### ISSUE TITLE
Undo #17 workaround, issue was solved upstream in a more preferable way

### ISSUE THREAD

**Issue by drmuey** [cpanel/elevate#317]
The problem in #17 was solved properly upstream (the hard restart we suggested back then) ➜ `60662de EA-11657: Ensure nginx is hard restarted during deb/rpm transactions`

The fix for #17 in ELevate should probably be undone because a hard uninstall via `rpm --nodeps` + `dnf install` is overkill at best (just needed to do the hard restart (i.e. not soft reload) as noted back then) and problematic at worst.

**Comment by troglodyne** [comment]
Looks like just a straightforward revert based on a read of the code and what you are suggesting here

**Comment by toddr** [comment]
We've opted out of this for now because the work around appears to still be needed. Please refer to RE-62
