### ISSUE TITLE
[BUG]  LEAPP_OVL_SIZE should be able to be changed

### ISSUE THREAD

**Issue by yakatz** [cpanel/elevate#318]
**Describe the bug**
The script [sets the value of LEAPP_OVL_SIZE](https://github.com/cpanel/elevate/blob/0abeaa36acb021f64e9964a4740821a9c831101e/script/elevate-cpanel.PL#L1416) before calling leapp without checking if the admin tried to set it to something else. This means if that size isn't big enough, there is no easy way for the admin to override it.

**To Reproduce**
1. Try to upgrade a machine where 3000 isn't big enough.
2. Set the environment variable `LEAPP_OVL_SIZE=200000` and see that the actual overlay size doesn't change

**Expected behavior**
The admin should be able to increase the size if needed.

**Comment by atoomic** [comment]
Thanks for reporting this issue.
It clearly makes sense that a user should be able to increase `LEAPP_OVL_SIZE`
and we should preserve that value if set by the caller.

Right now, it does not work for you as the value is hardcoded here 
```
elevate-cpanel:6058:        local $ENV{LEAPP_OVL_SIZE} = 3000;
```

Waiting for the support for it, you can manually change the value in the script.
