### ISSUE TITLE
[BLOCK] R1Soft Server Backup Agent and R1Soft repository

### ISSUE THREAD

**Issue by stefan-popescu** [cpanel/elevate#321]
On our development server, we've got an upgrade blocker for the R1Soft repository and the R1Soft Server Backup Agent:

```
* 2023-11-02 18:36:29 [ERROR] 5 package(s) installed from unsupported YUM repo 'r1soft' from /etc/yum.repos.d/r1soft.repo
* 2023-11-02 18:36:29 [WARN] *** Elevation Blocker detected: ***
  One or more enabled YUM repo are currently unsupported.
  You should disable these repositories and remove packages installed from them
  before continuing the update.

  Consider reporting this limitation to https://github.com/cpanel/elevate/issues
```

The R1Soft repository can be found here: http://wiki.r1soft.com/display/ServerBackupManager/Install+Backup+Agent+on+CentOS%2C+RHE%2C+and+Fedora+manually

The R1Soft Server Backup Agent works fine on both, AlmaLinux and CloudLinux 8. We have production servers running it without issues. It should also be supported according to the R1Soft system requirements (Linux Kernels version 2.6.32+): http://wiki.r1soft.com/display/ServerBackupManager/System+Requirements

Thank you in advance.

**Comment by toddr** [comment]
Assuming there is no data loss in doing so, you can remove the rpms associated with r1soft.repo, upgrade, then re-install them. YMMV.

If you'd like help with this, you can open a ticket with cPanel support.

**Comment by toddr** [comment]
**2024-08-01** - version 50

* Fixed case RE-502: Enable elevate on systems with the R1Soft Backup Agent installed.
