### ISSUE TITLE
Document possible statuses in /var/cpanel/elevate

### ISSUE THREAD

**Issue by AVasiljev** [cpanel/elevate#330]
Please document possible values of stage and status set in /var/cpanel/elevate for proper integration with Virtuozzo's cPanel almaconvert script.

**Comment by toddr** [comment]
We'll update the docs but here's what it should look like.

Status can be `running`, `paused`, `success`, `failed`

Stage can be 1-6. These are documented here. https://cpanel.github.io/elevate/#sumup-of-upgrade-process

Stage 6 is when it's fully complete and it'll look like this:
```
   "stage_number" : 6,
   "status" : "success"
```
