### ISSUE TITLE
Enhance warning during: "This is your chance now to cancel the update process"

### ISSUE THREAD

**Issue by cPholloway** [cpanel/elevate#338]
We advise/mention that customers should have a full server backup multiple times in the docs, but to be safer, we should consider having them acknowledge this in the script itself.

NOTE:  This option should have a --confirm flag or a --yes flag to allow customers to avoid STDIN

**Comment by annes449** [comment]
I think we could/probably should at least add a notification like"we strongly encourage you to have a backup/snapshot of your server" right before we offer the option to abort.

The current wording is:

```
On failures after fixing them you can continue the elevation process by running:

    /scripts/elevate-cpanel --continue

This is your chance now to cancel the update process.
You can hit CTRL-C to abort, otherwise the install starts in a few seconds.
```

**Comment by toddr** [comment]
Let's enhance the message to talk about backup suggestions and maybe ask for an enter before proceeding unless they pass something on the command line. Maybe: `--non-interactive`

**Comment by toddr** [comment]
> Let's enhance the message to talk about backup suggestions and maybe ask for an enter before proceeding unless they pass something on the command line. Maybe: `--non-interactive`

or is `--yes` what the cool kids use instead of `--non-interactive` ?

**Comment by cPholloway** [comment]
Obviously, this would need better strings, but something like this would do the trick here:

```
--- a/script/elevate-cpanel.PL
+++ b/script/elevate-cpanel.PL
@@ -604,13 +604,26 @@ EOS
     Elevate::Notify::warn_skip_version_check() if $self->getopt('skip-cpanel-version-check');    # give one last reminder

     say <<EOS;
-This is your chance now to cancel the update process.
-You can hit CTRL-C to abort, otherwise the install starts in a few seconds.
+
+Backups are cool
+Snapshots are better
+Do now or hold breath that nothing gets detroited
+k, thanks bye
+
 EOS

-    do { sleep 1; print '.' }
-      for 1 .. 6;
-    print "\n";
+    if ( !$self->getopt('yes') || !$self->getopt('non-interactive') ) {
+        print "Proceed with the upgrade process? (yes/no) ";
+        my $reply = lc <STDIN>;
+        chomp $reply;
+
+        if ( $reply !~ m/^y(?:es?)?$/ ) {
+            FATAL "I HAVE THE HIGH GROUND";
+            exit 1;
+        }
+    }
+
+    INFO "UPDATING STARTS NOW";

     return;
 }
```

**Comment by toddr** [comment]
I'd encourage the use of `IO::Prompt` over STDIN.
