### ISSUE TITLE
Provide helpful information when a 'cPanel $version does not appear to be up to date' Blocker is encountered

### ISSUE THREAD

**Issue by annes449** [cpanel/elevate#339]
- **Provide helpful information when a 'cPanel $version does not appear to be up to date' Blocker is encountered**

- This is the Blocker the client sees when their server is not running the most recent version of cPanel v110:

```
......
* 2024-01-08 21:43:45 [INFO] Successfully verified signature for cpanel (key types: release, development).
* 2024-01-08 21:43:45 [ERROR] This installation of cPanel (11.110.0.18) does not appear to be up to date.
  Please upgrade cPanel to a most recent version.
* 2024-01-08 21:43:45 [WARN] Please fix the detected issues before performing the elevation process.
  Read More: https://cpanel.github.io/elevate/blockers/
```

- For v102 the information is the same:

```
......
info [elevate-cpanel] Successfully verified signature for cpanel (key types: release, development).
* 2024-01-08 22:55:59 [ERROR] This installation of cPanel (11.102.0.36) does not appear to be up to date.
  Please upgrade cPanel to a most recent version.
* 2024-01-08 22:55:59 [WARN] Please fix the detected issues before performing the elevation process.
  Read More: https://cpanel.github.io/elevate/blockers/

```

- Maybe, we could tell them what version we are looking for, suggest they make certain updates are enabled in `/etc/cpupdate.conf` and provide a command to perform the upcp, like, If updates are not disabled on your server, then, you may execute the update now using `/usr/local/cpanel/scripts/fix-cpanel-perl; /usr/local/cpanel/scripts/upcp --cron`

**Comment by toddr** [comment]
@annes449 do we have a public document on this we can refer them to? No matter how detailed we are, this is a complicated thing. maybe we should refer people to support for help?

**Comment by annes449** [comment]
@toddr We might want to link `/etc/cpupdate.conf` to https://docs.cpanel.net/knowledge-base/cpanel-product/the-cpanel-update-configuration-file-cpupdate-conf/ and link `/usr/local/cpanel/scripts/upcp` to https://docs.cpanel.net/whm/cpanel/upgrade-to-latest-version/ and recommend that if they still have problems upgrading, they should open a support ticket.

**Comment by annes449** [comment]
We might consider telling them the version we are looking for, then, suggest they go to WHM: Upgrade to Latest Version to resolve the issue?

**Comment by toddr** [comment]
Explicitly telling them what version we think they should be on would be an improvement. Also linking to the above docs would be good!
