### ISSUE TITLE
Document/fix enforce and document sane command line argument combinations

### ISSUE THREAD

**Issue by annes449** [cpanel/elevate#342]
- *Document/fix enforce and document sane command line argument combinations*

- For instance:

_`--no-leapp` is not required for helper commands like `--continue` or `--status`_ is stated in the  **Advanced Options** section of the help output

However, if the first instance of `elevate-cpanel` was `/scripts/elevate-cpanel --start`, then, even though the tool will currently accept the following command line arguments, none of these will prevent `elevate-cpanel` from attempting the actual distro upgrade:

```
/scripts/elevate-cpanel --start --no-leapp
/scripts/elevate-cpanel --continue --no-leapp
/scripts/elevate-cpanel --status --no-leapp
```

**Comment by toddr** [comment]
Closing for RE-57
