### ISSUE TITLE
`/scripts/elevate-cpanel --check` should check for fatal errors before checking for issues the client can resolve

### ISSUE THREAD

**Issue by annes449** [cpanel/elevate#347]
- **`/scripts/elevate-cpanel --check` should check for fatal errors before checking for issues the client can resolve**

- When the client runs `/scripts/elevate-cpanel --check` on a v100.0.12 binary build running on CloudLinux 6.10, they are told the following:

```
# /scripts/elevate-cpanel --check
You need to upgrade your cPanel server to version 102or later before running this script.
```

- But, if the client updates the cPanel version to v102.0.36. and, again runs `/scripts/elevate-cpanel --check`, the following is displayed:

```
# /scripts/elevate-cpanel --check
Use of uninitialized value in split at /usr/local/cpanel/Cpanel/RestartSrv/Systemd.pm line 32.
* 2024-01-11 19:17:20 [FATAL] This script is designed to only run on CentOS 7 servers.
```

- **_We probably should have told the client that ELevate wasn't going to work on this server before giving them instructions on how to make it work._**

**Comment by cPholloway** [comment]
We should probably move the OS check up to BEGIN block just before the cPanel version check.

**Comment by toddr** [comment]
Ideally nothing should be happening in the BEGIN block :\

**Comment by cPholloway** [comment]
```
 185 BEGIN {
 186     # sanity check before loading the script
 187     eval { require Cpanel::Version::Tiny } or do {
 188         warn(qq[This script is designed to only run on cPanel servers.\n]);
 189         exit 1;
 190     };
 191
 192     $Cpanel::Version::Tiny::major_version >= Elevate::Constants::MINIMUM_LTS_SUPPORTED
 193       or do {
 194         warn qq[You need to upgrade your cPanel server to version ] . Elevate::Constants::MINIMUM_LTS_SUPPORTED    #
 195           . qq[ or later before running this script.\n];
 196         exit 1;
 197       };
 198 }
```

Then this issue essentially amounts to remove the BEGIN block from `script/elevate-cpanel.PL` and let `Elevate::Blockers::WHM` do its job.  The blocker handles both of the cases in the BEGIN block.

**Comment by toddr** [comment]
I'm ok with that. Though I think detecting you're not on a cPanel server (and thus might not have enough perl modules to run the script) probably is the only thing that needs to stay in BEGIN.
