### ISSUE TITLE
[UPG FAIL] 

### ISSUE THREAD

**Issue by RickieF63** [cpanel/elevate#352]
If you were able to upgrade but something has gone wrong, the quickest way to get help is to open a ticket with [cPanel Technical Support](https://docs.cpanel.net/knowledge-base/technical-support-services/how-to-open-a-technical-support-ticket/). 

NOTE:
 * During stage 3, a reboot will happen and the server will be inaccessible from the network for an extended period of time while distro packages are upgraded. [We recommend you have console access](https://cpanel.github.io/elevate/#before-updating) prior to start so you can know if it is hung or simply running slow.
 * If an error occurs during the elevation process, once you have fixed it, you can resume
the update process by running: `/scripts/elevate-cpanel --continue`

*We cannot provide support on individual server issues. We have to refer you to technical support.*

**Comment by RickieF63** [comment]
Upgrade has failed multiple times now, can't login to my cPanel account to log a support ticket as it keeps going to store login not my root cPanel account (well done new owners, even 2018 copyright still on site).

Loops continuously with the following (images are run from WHM terminal then from VNC from server provider), this needs solved as we have a critical vulnerability due to not being able to update WHM/cPanel.

Latest script pulled before upgrade;
![pre](https://github.com/cpanel/elevate/assets/139263097/0a0618d0-508c-4c04-b4f5-f92e69a0d176)
![1](https://github.com/cpanel/elevate/assets/139263097/3af337ab-a088-48a1-8394-7dda520a822f)
![2](https://github.com/cpanel/elevate/assets/139263097/bd022851-c09b-4d27-9f87-f669d0aebfbd)

**Comment by toddr** [comment]
@RickieF63 if you add your email address to your profile, we can email you and try to sort things out. We're unable to help here.
