### ISSUE TITLE
[BLOCK] Add hints & FAQ for network blocker: more than one ethnic* interface

### ISSUE THREAD

**Issue by atoomic** [cpanel/elevate#404]
Using more than a single interface like `eth0`, `eth1`, ... is a common pattern we could expect from more than one customer 

We should consider:
1. Provide a more friendly error message and provide some hints on how to rename and what are the good practice to rename a NIC
2. Add one FAQ entry for Renaming `eth1` 

```
        Your machine has multiple network interface cards (NICs) using kernel-names (ethX).
        Since the upgrade process cannot guarantee their stability after upgrade, you cannot upgrade.

        Please provide those interfaces new names before continuing the update.
```

but what's next?

Some naming convention: 
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-consistent_network_device_naming

```
en → Ethernet
ib → InfiniBand
sl → Serial line IP (SLIP)
wl → WLAN
ww → WWAN
```

How to rename a NIC: https://www.baeldung.com/linux/rename-network-interface

**Comment by toddr** [comment]
RE-276
