### ISSUE TITLE
[UPG FAIL]  be2net drivers missing on hp gen 8 server and kvm issues

### ISSUE THREAD

**Issue by devops365** [cpanel/elevate#443]
Hello,

All checks will pass normally. However when rebooting on stage 3 the machine loses networking and there are some other kvm issues as well.
The reason for the loss of networking is its missing the be2net module for emulex nic's that are used in hp servers gen8.
The issue could in some cases be fixed by installing the needed driver via rpm.

However in the last elevate this was not able to complete and there was an error during rpm installation.
<img width="924" alt="unable-to-install-driver" src="https://github.com/cpanel/elevate/assets/31511639/5c34e30a-b1f7-4897-ab7d-df02bed839b6">

The only way to continue with the upgrade (thankfully) and to have a usable server afterwards, was after stage 3 to keep selecting kernel 3.10 on each reboot.
Otherwise if it boots on kernel 4.x there is no networking and there are issues with the iLO console as well , that can be addressed by adding commands on boot.

Since HP Gen8 servers are still widely used by the hosting industry and not only, I strongly suggest for some additional checks and ideally to add support for those drivers.
I read in a forum post that these drivers will be added on almalinux 8.10 but they are not still there , and this leads to failed elevate's without any warning.

Kindly create a solution where the driver is installed on kernel 4.x during the upgrade and also to include these options 
intremap=nosid and intel_iommu=off

Thank you

**Comment by toddr** [comment]
We can block on this, but the fix would need to go into the upstream leapp utility. We'll see about reporting it there and update this ticket when we do.

**Comment by cPholloway** [comment]
RE-397 has been filed internally for this issue.

**Comment by devops365** [comment]
Well the solution isn't to block it. Theoretically Almalinux 8.10 must be ok now after their last additions in drivers.
Can you confirm that this has been resolved ?

Thanks

**Comment by toddr** [comment]
Sorry, we don't have the hardware to confirm. If you think it's fixed, then you should try it. We wrap around the leapp and almalinux tools, but have no influence on their support.
