### ISSUE TITLE
Any plans to include an upgrade from RHELv8 to RHELv9 distros in the cPanel elevate tool?

### ISSUE THREAD

**Issue by Ferguson230** [cpanel/elevate#448]
Hi, for general ALmaLinux8 to ALmaLinux9, there's an elevate for that as documented here https://wiki.almalinux.org/elevate/ELevating-CentOS7-to-AlmaLinux-9.html#migrating-almalinux-8-to-almalinux-9 , however, for people that have cPanel/WHM installed on their servers, the cPanel Elevate tool does not yet support this.
Do you plan to include this feature in the cPanel Elevate tool soon?
As listed here https://endoflife.date/almalinux active support for AlmaLinux8 ended about a month ago, though security updates will continue for another 4+ years.

**Comment by toddr** [comment]
Yes. We'll be taking a brief pause to work on ubuntu 20->22 but then will be coming back to add support for 8->9
