### ISSUE TITLE
[UPG FAIL] Database upgrade prevented by read_only flag (which is not set)

### ISSUE THREAD

**Issue by al3xxx** [cpanel/elevate#469]
Upgrade failed at stage 4. 

* 2024-07-10 02:47:21 (8772) [ESC[1;37mDEBUGESC[0m] Running 'post_leapp' from MySQL component.
* 2024-07-10 02:47:21 (4253) [ESC[32mINFOESC[0m] Restoring MySQL 10.6
* 2024-07-10 02:47:21 (4257) [ESC[32mINFOESC[0m] Restoring /etc/my.cnf.rpmsave_pre_elevate to /etc/my.cnf...
* 2024-07-10 02:47:53 (6735) [ESC[32mINFOESC[0m] Sending notification: Failed to update to AlmaLinux 8
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] The elevation process failed during stage 4.
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] 
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] You can continue the process after fixing the errors by running:
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] 
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m]     /usr/local/cpanel/scripts/elevate-cpanel --continue
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] 
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] You can check the error log by running:
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] 
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m]     /usr/local/cpanel/scripts/elevate-cpanel
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] 
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] Last Error:
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] 
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] Cannot find upgrade_id from start_background_mysql_upgrade:
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] --- 
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m] metadata: 
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m]   command: start_background_mysql_upgrade
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m]   reason: "API failure: (XID unynep) The system cannot upgrade your version of MySQL or MariaDB because of at least one impediment: \nFatal: Your databaseâ<U+0080><U+0099>s â<U+0080><U+009C>read_onlyâ<U+0080><U+009D> flag is enabled. Disable this flag, then try again.\n   Critical: The system failed to query the MySQL server to check for the presence of pre-4.1-style MySQL passwords. ((XID gxncze) The system failed to connect to the â<U+0080><U+009C>MySQLâ<U+0080><U+009D> database â<U+0080><U+009C>mysqlâ
<U+0080><U+009D> because of an error: CR_CONNECTION_ERROR (Can't connect to local server through socket '/var/lib/mysql/mysql.sock' (2))) This issue could also hinder mysql_upgrade's ability to run, which could potentially leave MySQL in an unusable state if you proceed.\n   Normal: The selected MariaDB version (10.6) is the same as the currently installed MariaDB version (10.6). No upgrade will be performed at this time, though the normal upgrade steps will still be executed. This is only useful if a previous upgrade failed while partially completed.\n"
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m]   result: 0
* 2024-07-10 02:47:53 (6740) [ESC[31mERRORESC[0m]   version: 1

 I had to manually add mariadb 10.6 repo and install MariaDB-server and MariaDB-common to bring server to working state, but now I am still getting this read-only problem and can not continue. I have couple more servers like this and now I am stuck.

**Comment by mdesouki** [comment]
copy /etc/my.cnf.rpmsave_pre_elevate to /etc/my.cnf.rpmsave_pre_elevate.org
echo >/etc/my.cnf.rpmsave_pre_elevate
/scripts/elevate-cpanel --continue
after MySQL start 
mv /etc/my.cnf.rpmsave_pre_elevate.org /etc/my.cnf

**Comment by cPholloway** [comment]
Can you provide us with the contents of `/etc/my.cnf` and `/etc/my.cnf.rpmsave_pre_elevate` after the failure?

**Comment by al3xxx** [comment]
original /etc/my.cnf.rpmsave_pre_elevate
```
[mysqld]
log-error=/var/lib/mysql/ns.err
performance-schema=0
default-storage-engine=MyISAM
innodb_file_per_table=1
max_allowed_packet=1073741824
open_files_limit=21000
connect_timeout=600
tmpdir=/dev/shm
bind-address = 127.0.0.1
local-infile=0
sql_mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
innodb_read_only_compressed=OFF
read-only=0
unix_socket=OFF

```
after emptying it and running elevate-cpanel --continue, I've got this /etc/my.cnf
```
[mysqld]
log-error=/var/lib/mysql/ns.err
performance-schema=0
innodb_file_per_table=1
unix_socket=OFF
max_allowed_packet=268435456
```

**Comment by cPholloway** [comment]
Thank you for this information.  I see why elevate is failing to restore/install MySQL/MariaDB in stage 4 due to this my.cnf file. 

Specifically, it is failing because of this line in `/etc/my.cnf.rpmsave_pre_elevate`:

```
read-only=0
```

I have filed RE-543 for us to address this issue.

**Comment by al3xxx** [comment]
@cPholloway 
The error message specifically mentions 'read_only', not 'read-only', also I tried to remove this line
```read-only=0```
and run **elevate-cpanel --continue** and it didn't work out - got the same error message. I suspect that the problem is in `read_only` line.
