### ISSUE TITLE
Alma 8.10 to Alma 9.3 upgrade failed using "leapp upgrade"

### ISSUE THREAD

**Issue by crvhc** [cpanel/elevate#471]
This is a leapp issue. As the Server console output said: "Please open a support case with /sysroot/var/log/leapp/leap-upgrade.log attached".
System is back to Alma 8.10. 
Attached is /var/log/leapp/leapp-upgrade.log file
[leapp-upgrade.log](https://github.com/user-attachments/files/16176647/leapp-upgrade.log)

**Comment by sloanebernstein** [comment]
Hello,

The script provided by this particular project does not support upgrading AlmaLinux 8 to AlmaLinux 9. We have not yet looked into that upgrade path on cPanel servers, so we can't provide any guidance as to what steps are needed to make `leapp upgrade` result in a fully functional system.

If accounts hosted on an AlmaLinux 8 server running cPanel need capabilities only provided by AlmaLinux 9, we recommend provisioning a new server with AlmaLinux 9 and cPanel and copying the accounts using the [Transfer Tool in WHM](https://docs.cpanel.net/whm/transfers/transfer-tool/).

If your server is not a cPanel system, or it is but you wish to proceed anyway, you may want to open an issue under the [AlmaLinux leapp-repository](https://github.com/AlmaLinux/leapp-repository/issues) project instead.
