### ISSUE TITLE
[BLOCK] Unknown error while checking blockers: command failed. Fix it and run command. at /scripts/elevate-cpanel line 7617.

### ISSUE THREAD

**Issue by SoLoR1** [cpanel/elevate#478]
Hello,

past night i tried to update 3 of our cPanel servers from CL 7 to 8. And well i encountered some problems. Long story short, on one it went without a hiccup. On other 2 however for one reason or another i had to restore from snapshot (one i forgot to take backup of postgres DB and web UI acted funky, on other after first boot in to CL8 i got stuck in emergency console and couldnt proceed). Anyway i said to my self, lets try again so i restored from snapshot. This is where problems begin... While i did snapshot JUST before elevation process now i cant get past:

* 2024-07-19 02:29:20 [INFO] --> Finished Dependency Resolution
* 2024-07-19 02:29:20 [INFO] Error: Package: leapp-deps-0.14.0-1.el7.noarch (elevate)
* 2024-07-19 02:29:20 [INFO]            Requires: python-requests
* 2024-07-19 02:29:20 [INFO] Error: Package: leapp-upgrade-el7toel8-deps-0.16.0-10.el7.cloudlinux.noarch (elevate)
* 2024-07-19 02:29:20 [INFO]            Requires: python-requests
* 2024-07-19 02:29:20 [INFO]  You could try using --skip-broken to work around the problem
* 2024-07-19 02:29:20 [INFO] Error: Package: leapp-upgrade-el7toel8-deps-0.16.0-10.el7.cloudlinux.noarch (elevate)
* 2024-07-19 02:29:20 [INFO]            Requires: dnf >= 4
* 2024-07-19 02:29:20 [INFO] Error: Package: leapp-deps-0.14.0-1.el7.noarch (elevate)
* 2024-07-19 02:29:20 [INFO]            Requires: python-six
* 2024-07-19 02:29:23 [INFO]  You could try running: rpm -Va --nofiles --nodigest
* 2024-07-19 02:29:23 [INFO]
* 2024-07-19 02:29:23 [WARN] Unknown error while checking blockers: command failed. Fix it and run command. at /scripts/elevate-cpanel line 7617.
* 2024-07-19 02:29:23 [WARN] Please fix the detected issues before performing the elevation process.
 Read More: https://cpanel.github.io/elevate/blockers/

On both is the same, have no idea why and how since it was literally snapshot just before i started update procedure. I understand this errors might be repos related, however no idea how this is possible,

**Comment by SoLoR1** [comment]
This might be issue from this: https://cloudlinux.zendesk.com/hc/en-us/articles/8763029890716-CloudLinux-8-repository-is-being-used-in-spite-CloudLinux-7

it makes sense... there was CL8 repo on CL7... probably will solve the issue, will report if it does, however i do think it should be a check for this case

**Comment by SoLoR1** [comment]
Im just doing another update and i can confirm this indeed was an issue.

**Comment by toddr** [comment]
glad this is now working for you!
