### ISSUE TITLE
[ERROR] 103 package(s) installed from unsupported YUM repo 'centos7-els' from /etc/yum.repos.d/centos7-els.repo

### ISSUE THREAD

**Issue by timyal** [cpanel/elevate#491]
How can I correct this error to continue upgrading CloudLinux7 to 8?

[ERROR] 103 package(s) installed from unsupported YUM repo 'centos7-els' from /etc/yum.repos.d/centos7-els.repo

I have already upgraded Centos7 to CloudLinux7.

Can I simply remove /etc/yum.repos.d/centos7-els.repo ?

Would it cause any problems? It is not enabled though...

**Comment by toddr** [comment]
Hi Tim, 

`ELS for CentOS 7` is new and not required on CloudLinux. However, they've not yet adjusted `cldeploy` to remove it when you convert to CloudLinux. This is somewhat rightly angering `elevate-cpanel`, which knows how to handle `ELS for C7` but not if you're on cloudlinux.

It's a little overkill, but to solve your current problem in the cleanest way possible, I would recommend disabling that repo and then running `yum reinstall ...` on all of the rpms that are currently coming from that repo. That should convert them to cloudlinux provided packages, which will assure the safest conversion to 8 for you. 

you should be able to do `yum list all |grep '@centos7-els`

Good luck!

**Comment by timyal** [comment]
Hi Todd,

Thank you very much for your detailed reply.

There are 103 packages in that repository. How can I find the ones used by CloudLinux? Or I will have to install all one by one?

Regards,
Tim

**Comment by timyal** [comment]
<img width="604" alt="2024-08-12 21_10_02-Termius - 3 8 17 158" src="https://github.com/user-attachments/assets/5f106d2e-7ee5-4054-938b-8696e81d5d1e">

Are these @cloudlinux-x86_64-server ones the ones I need to reinstall?

There are also a couple @updates like;

rpm-python.x86_64                          4.11.3-48.el7_9             @updates
