### ISSUE TITLE
[UPG FAIL] Fatal Error Stage 3

### ISSUE THREAD

**Issue by cultd3ad** [cpanel/elevate#525]
Hello,
I get a fatal error with this code at status stage 3!

`# use Log::Log4perl qw(:easy);
    INIT { Log::Log4perl->import(qw{:easy}); }

    BEGIN {
        my @_DELEGATE_TO_CPEV = qw{
          getopt
          should_run_distro_upgrade
          ssystem
          ssystem_and_die
          ssystem_capture_output
          ssystem_hide_and_capture_output
          remove_rpms_from_repos
        };

        foreach my $subname (@_DELEGATE_TO_CPEV) {
            no strict 'refs';
            *$subname = sub ( $self, @args ) {
                my $cpev = $self->cpev          or Carp::confess(qq[Cannot find cpev to call $subname]);
                my $sub  = $cpev->can($subname) or Carp::confess(qq[cpev does not support $subname]);
                return $sub->( $cpev, @args );
            }
        }
    }`

The line that causes the error is this:
2024-10-12 20:55:51 (7592) [ERROR] Program is not an executable absolute path.                                                                                                                              at /usr/local/cpanel/scripts/elevate-cpanel line 2622.
* 2024-10-12 20:55:51 (9278) [FATAL] Program is not an executable absolute path.                                                                                                                              at /usr/local/cpanel/scripts/elevate-cpanel line 2622.
`return $sub->( $cpev, @args );`

The error I'm getting is related to the Perl script trying to call a method on an object declared as **cpev**, however the object doesn't appear to be initialized correctly. The error message indicates that the script is accessing an **undefined or invalid object**, resulting in an error.

How can I solve the problem?

thanks in advance

**Comment by cultd3ad** [comment]
Ok here in Stage 4

Installed is MariaDB 10.5 ! and this on centos 7 , i dont no install MariaDB 10.5 again

`/scripts/elevate-cpanel --continue

to complete the ELevation process.
* 2024-10-13 16:51:07 (8885) [INFO] Self-update of script version 55 requested.
* 2024-10-13 16:51:07 (8907) [INFO] Script is up to date.
* 2024-10-13 16:51:41 (7542) [INFO] Running: /usr/bin/systemctl restart elevate-cpanel.service
* 2024-10-13 16:51:41 (7543) [INFO]
* 2024-10-13 16:51:41 (7573) [INFO]
* 2024-10-13 16:51:41 [INFO]
* 2024-10-13 16:51:41 (9669) [INFO] ******************************************************************************************
* 2024-10-13 16:51:41 (9670) [INFO] *
* 2024-10-13 16:51:41 (9671) [INFO] * Starting stage 4 of 5
* 2024-10-13 16:51:41 (9672) [INFO] *
* 2024-10-13 16:51:41 (9673) [INFO] ******************************************************************************************
* 2024-10-13 16:51:41 (9643) [INFO] Stage 4: skipping component:RpmDB:post_distro_upgrade (already run)
* 2024-10-13 16:51:41 (9643) [INFO] Stage 4: skipping restore_cpanel_services (already run)
* 2024-10-13 16:51:41 (9643) [INFO] Stage 4: skipping component:Imunify:post_distro_upgrade (already run)
* 2024-10-13 16:51:41 (9643) [INFO] Stage 4: skipping component:EA4:post_distro_upgrade (already run)
* 2024-10-13 16:51:41 (9643) [INFO] Stage 4: skipping upcp (already run)
* 2024-10-13 16:51:41 (9768) [INFO] Removing leapp from excludes in /etc/yum.conf
* 2024-10-13 16:51:41 (9618) [DEBUG] Running 'post_distro_upgrade' from MySQL component.
* 2024-10-13 16:51:41 (4297) [INFO] Restoring MariaDB 10.5
* 2024-10-13 16:51:41 (6547) [INFO] Beginning upgrade to MariaDB 10.5
* 2024-10-13 16:51:56 (6556) [FATAL] FAILED to upgrade to MariaDB 10.5
* 2024-10-13 16:51:56 (4309) [FATAL] Unable to install MariaDB 10.5.  To attempt to
install the database server manually, execute:

/usr/local/cpanel/bin/whmapi1 start_background_mysql_upgrade version=10.5

To have this script attempt to install MariaDB 10.5
for you, execute this script again with the continue flag

/scripts/elevate-cpanel --continue

Or once the issue has been resolved manually, execute

/scripts/elevate-cpanel --continue

to complete the ELevation process.
* 2024-10-13 16:51:56 (7462) [INFO] Sending notification: Failed to update to AlmaLinux 8
* 2024-10-13 16:51:56 (7467) [ERROR] The elevation process failed during stage 4.
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] You can continue the process after fixing the errors by running:
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel --continue
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] You can check the error log by running:
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR]     /usr/local/cpanel/scripts/elevate-cpanel
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] Last Error:
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] Unable to install MariaDB 10.5.  To attempt to
* 2024-10-13 16:51:56 (7467) [ERROR] install the database server manually, execute:
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] /usr/local/cpanel/bin/whmapi1 start_background_mysql_upgrade version=10.5
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] To have this script attempt to install MariaDB 10.5
* 2024-10-13 16:51:56 (7467) [ERROR] for you, execute this script again with the continue flag
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] /scripts/elevate-cpanel --continue
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] Or once the issue has been resolved manually, execute
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] /scripts/elevate-cpanel --continue
* 2024-10-13 16:51:56 (7467) [ERROR]
* 2024-10-13 16:51:56 (7467) [ERROR] to complete the ELevation process.
* 2024-10-13 16:51:56 (9154) [FATAL] Unable to install MariaDB 10.5.  To attempt to
install the database server manually, execute:

/usr/local/cpanel/bin/whmapi1 start_background_mysql_upgrade version=10.5

To have this script attempt to install MariaDB 10.5
for you, execute this script again with the continue flag

/scripts/elevate-cpanel --continue

Or once the issue has been resolved manually, execute

/scripts/elevate-cpanel --continue

to complete the ELevation process.
^C
[root@****** ~]# /usr/local/cpanel/bin/whmapi1 start_background_mysql_upgrade version=10.5
---
data:
  upgrade_id: mysql_upgrade.20241013-165217
metadata:
  command: start_background_mysql_upgrade
  reason: OK
  result: 1
  version: 1`

**Comment by toddr** [comment]
I'm 90% certain this was fixed in #563
