### ISSUE TITLE
Can we authorize upgrades with elastic search?

### ISSUE THREAD

**Issue by toddr** [cpanel/elevate#63]
https://support.cpanel.net/hc/en-us/articles/360055446413-How-To-Install-Run-Elasticsearch

23-22:36:18 (2767) [ERROR] 1 package(s) installed from unsupported YUM repo 'elasticsearch-7.x' from /etc/yum.repos.d/elasticsearch.repo

**Comment by toddr** [comment]
I'm pretty sure it's java and we just need to whitelist the repo.

**Comment by chopinesque** [comment]
Elastic Search still appears to be blocked?

https://github.com/cpanel/elevate/issues/115
https://github.com/cpanel/elevate/issues/108
