### ISSUE TITLE
Send all output through log4perl?

### ISSUE THREAD

**Issue by sloanebernstein** [cpanel/elevate#83]
Currently, most logging to file is done by piping the output of a command through `tee(1)`, which is only invoked through the systemd service. This means that some output is not captured in the log file, such as the entirety of stage 1. It also makes logging of some events (_e.g._, use of `--continue` in #71) awkward and ad-hoc.

Since much of the internal diagnostic output is being routed through `Log::Log4perl`, it would be ideal to also route external program output through it and use a native appender to handle logging to file.

Issues:
- `ssystem` needs to call something that lets it capture output (_i.e._, not `system`).
- There doesn't seem to be an easy way to colorize output to a file via log4perl: `ScreenColoredLevels` won't write to a file, and `File` can't do colors.

**Comment by toddr** [comment]
log4perl can provide different output per stream so we've got some stuff to work with there.

**Comment by sloanebernstein** [comment]
For now, logging consistency is more important than fancy colored text, so this feature is likely being sacrificed.
