### ISSUE TITLE
Restore colorized screen output

### ISSUE THREAD

**Issue by sloanebernstein** [cpanel/elevate#87]
#86 removed colorized screen output as a side effect of converting logging to a file using native log4perl mechanisms. Colorized output is useful for users who may not fully understand how to read the existing output, so it is desirable to restore this feature. Doing this for direct invocation is easy enough, so output during `--check` and stage 1 of `--start` is trivial to restore, but all other output is not.

Instead of directly tailing the log file, one way of solving this might be to have the script invoked as a service use a socket or named pipe to relay the logging information to the script invoked with `--log` or otherwise listening to the service.

**Comment by toddr** [comment]
Would prefer text to the right of debug/warn/error be not colorized.
