### ISSUE TITLE
Normalize logging levels and behaviors across the program

### ISSUE THREAD

**Issue by sloanebernstein** [cpanel/elevate#97]
Now that colorized logging has been restored by #96, it is becoming apparent that better decisions need to be made about which logging levels certain messages should use. The primary example is that most external programs are having their output printed at the `INFO` level, which is colored green. Before recent changes, `ssystem` used `system` directly, so Log4perl was bypassed, and such text always rendered with the default terminal color; only the header stating what program was being run was colored. Now, large portions of the output are green, leading to fatigue when reading the output.

Additionally, `die` statements are often being used both for fatal error reporting and for exception handling. However, now that Log4perl handles all log-worthy output, many—but not all—of these statements should be replaced with `LOGDIE`, so that Log4perl does the appropriate thing with them.

**Comment by atoomic** [comment]
#155 should provide an improvement and avoid color flood :-)

**Comment by toddr** [comment]
BC-6489
