### ISSUE TITLE
DimeNOC repo

### ISSUE THREAD

**Issue by dxisto** [cpanel/elevate#98]
I have a bare metal server in Dime Noc and when I ran pre-check script I got this errors:

* 28-11:12:37 (2971) [ERROR] 356 package(s) installed from unsupported YUM repo 'base' from /etc/yum.repos.d/DimeNOC.repo
* 28-11:12:37 (2971) [ERROR] 206 package(s) installed from unsupported YUM repo 'updates' from /etc/yum.repos.d/DimeNOC.repo
* 28-11:12:37 (2971) [ERROR] 1 package(s) installed from unsupported YUM repo 'extras' from /etc/yum.repos.d/DimeNOC.repo
* 28-11:12:37 (2971) [ERROR] 22 package(s) installed from unsupported YUM repo 'DimeNOC' from /etc/yum.repos.d/DimeNOC.repo

**Comment by toddr** [comment]
Yep elevate doesn't know what packages are in this or if they need upgrading after elevate. If you want to proceed with the upgrade, it wants you to remove these packages and these repos and then put them back after the upgrade. 600 packages is a lot though, can you give me more insight as to what they are?

**Comment by dxisto** [comment]
> Specifically, can you confirm whether this setup with `/etc/yum.repos.d/DimeNOC.repo` is something your provider included when the system was provisioned, whether this is a custom change you made on recommendation of your provider, or some other origin?

Basically this repo install puppetd and axond, which are DimeNOC management agents so user can control and monitor theirs servers using DimeNOC control panel

`[base]
name=CentOS-$releasever - Base
baseurl=http://repo1.dimenoc.com/centos/$releasever/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5

#released updates
[updates]
name=CentOS-$releasever - Updates
baseurl=http://repo1.dimenoc.com/centos/$releasever/updates/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5

#packages used/produced in the build but not released
#[addons]
#name=CentOS-$releasever - Addons
#baseurl=http://repo1.dimenoc.com/centos/$releasever/addons/$basearch/
#gpgcheck=1
#gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5

#additional packages that may be useful
[extras]
name=CentOS-$releasever - Extras
baseurl=http://repo1.dimenoc.com/centos/$releasever/extras/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5

[DimeNOC]
name=CentOS-$releasever - DimeNOC
baseurl=http://repo1.dimenoc.com/dimenoc/centos/$releasever/$basearch/
enabled=1
gpgcheck=1
gpgkey=http://repo1.dimenoc.com/dimenoc/DIMENOC-RPM-GPG-KEY
priority=10

[DevNOC]
name=CentOS-$releasever - DimeNOC Development
baseurl=http://repo1.dimenoc.com/dimenoc/development/centos/$releasever/$basearch/
enabled=0
gpgcheck=1
gpgkey=http://repo1.dimenoc.com/dimenoc/DIMENOC-RPM-GPG-KEY
priority=10`

**Comment by toddr** [comment]
@dxisto, this repo file appears to be a custom repo file provided by hostdime. The contents appear to be the same as what one would find in the repo files provided by the rpm `centos-release`. It's unclear to us why this was done this way. It is possible to bypass this check, but we are unsure what would happen when the AlmaLinux elevate code upgrades to  AlmaLinux 8. Would this confuse it? Would it skip over and crash during the reboot where you only have console access? Not sure!

We're also a  little nervous about any testing here, given the server you're on appears to be bare metal, so if something does crash, you won't be able to restore the VM to its pre-upgrade state.

My assessment is that this tool is correctly stopping you so you can take a closer look. Proceed with caution!

**Comment by toddr** [comment]
We do not have plans to address the custom repo files for dimenoc at this time.
